### ISSUE TITLE
add-in sharing modal when Question is published

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#10]
This is for Walter & Steve both -- goal is to finish styling the social sharing prompt when a Q is published. Right now that's not yet hooked-up. 

Aim is to basically replicate petition sites, where when a question is previewed and the publish button is shared, to immediately pop-up a modal window above question page :: 

http://oglocal.herokuapp.com/ny/questions/51eedf080724cd8621000007

... w/ elements for email sharing, FB sharing & Twtr sharing, as on Change ::

http://cl.ly/image/3w1x080X311z

... or on We The People ::

http://cl.ly/image/1E2F0u313K1p

... that's more understated. 

Or SignOn ::

http://cl.ly/image/310Y1j3O1L1T

... I'm partial to that layout, I think. So does this go to Walter first, then Steve to style?  Realize it needs copy, but some placeholder copy is fine for now.

**Comment by walter** [comment]
@kidfribble this seems mostly frontend (except the trigger for the modal to be open).

Do you want to just implement it where all views of the question page get the modal and then I'll come back and implement the detection for whether it should be open or not after you are done?

**Comment by kidfribble** [comment]
Yeah that sounds good to me

**Comment by davidmooreppf** [comment]
Just assigning this - 8(a) on dev roadmap - to Steve, adding-in the banner as on Change with prompts to email/share a just-published Q/petition. Reassign to Walter to implement the next step of course.

**Comment by davidmooreppf** [comment]
Piggyback on modal designs & handoff to Amanda, new front-end dev

**Comment by acacheung** [comment]
Hey Derek, the styles should be all set for the modal. I put them on questions show page. Passing it on so you can wire up the backend for this. Let me know if you have any questions.

**Comment by derekeder** [comment]
@acacheung cool! @evz and I will dive in to it tomorrow.

**Comment by walter** [comment]
@derekeder & @evz, I think your tying together of the modal work (frontend styles/js with controller/view logic) should allow us to get our tests back passing.

In other words, if "questions #show when displaying signature information allows new user to register and sign on to a question" is still failing after you finish your work, please adjust it to accurately describe our new expectations for the feature (a user should get a modal for sharing after asking a question).

**Comment by walter** [comment]
@derekeder & @evz, if you can add screenshots of things here as you go, that would be handy.

**Comment by evz** [comment]
Overlay is now showing when there is a `created=true` query parameter. I'll take a look at the specs next.

![screen shot 2013-08-22 at 9 51 58 am](https://f.cloud.github.com/assets/551491/1009533/75bad322-0b3a-11e3-9dfd-4b3f092c06bc.png)

**Comment by walter** [comment]
Closed with #64.
