### ISSUE TITLE
sharing copy from splash page

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#102]
Didn't know exactly how to change these on splash page layouts :: 

Clicking email button opens new email w/ subject : 

Get notified when AskThem launches 

... and in the body, copy :: 

AskThem is a new question-and-answer website with public figures. It's free, open-source, and not-for-profit.

Sign up here to be notified when it launches this Fall and be the first to ask a question to the people who represent you in government :: 

www.askthem.io

... it's like a version of the "We The People" petition platform for every elected official. You can target over 100,000 elected officials nationwide with questions and petitions, from local city council members all the way up to U.S. senators.

AskThem is a project of the Participatory Politics Foundation, the 501(c)3 non-profit organization that created OpenCongress.org and OpenGovernment.org. 

---

For FB share :: 

AskThem is a new question-and-answer website with public figures. It's free, open-source, and not-for-profit.

Sign up here to be notified when it launches this Fall and be the first to ask a question to the people who represent you in government :: 

www.askthem.io

---

For Twitter share :: 

Get notified when AskThem launches, for question-and-answer and petitions with public figures: askthem.io.

**Comment by acacheung** [comment]
@davidmooreppf I made most of these edits, but there were a few things I couldn't do.

For email: the way we are doing it is through a mailto link and I cannot ensure that the email client will turn the url's into links. Something like Gmail will try and do it automatically though. Also there may be character limits to the body copy that varies browser to browser and email client to email client. If you want to guarantee all this, maybe @walter can do a mailer? but that might mean that the user cannot customize the text.
