### ISSUE TITLE
try different color on logotype, and / or glow hover-over effect

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#106]
Have additional questions re: the header design - I know this is a lot of tweaking, so let me know if you're OK with this ::

can we try different colors on the logo to make it livelier? The gray type isn't seeming exciting to some of my test group.

Amanda suggested glow on hover-over.

**Comment by acacheung** [comment]
@davidmooreppf Different colors aren't looking that good to me. The best option might be to do a little animation similar to how http://www.snowdenindustries.com/ does. We most likely won't have time to do it this week, but maybe in the future?

**Comment by davidmooreppf** [comment]
I hear that, but my team would like to at least see screenshots w/ different colors. Please try a couple so we can see.

And a brighter-colored ribbon, is that worth considering?

**Comment by kidfribble** [comment]
Chiming in for a moment here: the ribbon is a bad idea IMO - it's a cheap gimmick used by millions of sites trying to add 'flair'. I don't want OG falling into that trap last minute. I hope you'll agree.

Colors could make a difference, though we're not sure what would work best. @acacheung will work on some variations today.

**Comment by davidmooreppf** [comment]
Rightyo Steve - I hear that on the ribbon. I was just throwing it out there.

I'm not pushing to deploy a color change, but my team def def wants to see some variants, two or three or whatever, just to know.

**Comment by kidfribble** [comment]
Sounds good, David!

**Comment by acacheung** [comment]
@davidmooreppf Here are a few variations along with the original. What do you think? 

![light-blue](https://f.cloud.github.com/assets/1054686/1134463/83b4fa12-1bf1-11e3-811e-f7ba7f8c0b6b.png)
![original](https://f.cloud.github.com/assets/1054686/1134464/83b82494-1bf1-11e3-97be-4ea7be627f21.png)
![red](https://f.cloud.github.com/assets/1054686/1134465/83bafb1a-1bf1-11e3-9e11-f6c86846e6f0.png)
![white-glow](https://f.cloud.github.com/assets/1054686/1134466/83bb20c2-1bf1-11e3-9053-c25c51e3cffe.png)

**Comment by davidmooreppf** [comment]
Let's go with orange for a test.
