### ISSUE TITLE
on question creation page, question input, issues on length of text fields

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#109]
On page 2 of 4 of Q creation process, when a visitor inputs a Q title, she has 60 characters. After 38 characters, she can still enter text, but the text field itself doesn't expand, so she can only see the end of the Q. 

Goal is for her to be able to see and edit the whole question title at once - either by making the field longer, enough to accommodate 60 chars, or for it to expand, whichever is nicer. 

http://cl.ly/image/2i3L313c0O2s

---

On the full question field, I see it can be expanded from the bottom-right corner, but I really feel like the three lines that are shown are too little. It doesn't feel quite welcoming when it's so small; but maybe that was with mobile in mind. 

Think it can be expanded to be five or six lines tall? 

And is there a character limit on it? 

Formatting tips? e.g. Hyperlinks? 

---

Last, we need a placeholder for a "help" or "tips" or "FAQ" option here. Without getting into it, we need to suggest the types of Q's that are most effective here, without discouraging the user or bouncing her from this page. 

Earlier versions had a text column on the right with three bullet points, under title, "What kind of questions work best here?" We need to steer users away from city-services questions (311), legal questions (judicial branch), and inappropriate questions, somehow. 

Open to input here, cc @walter - I think we can either re-implement the right-hand bullet points, or put a smaller link at the bottom of the page that opens a modal, w/ link copy "What kind of questions work best here?". What do you think, Amanda? I mean, a little Clippy character could be in order, haha.

**Comment by acacheung** [comment]
@davidmooreppf I don't think we can do hyperlinks (http://stackoverflow.com/questions/6895109/how-to-add-link-to-appear-inside-the-textarea-box) What you could do instead is have a markdown editor like https://bitbucket.org/davidchambers/hashify-editor

**Comment by walter** [comment]
@davidmooreppf I think we should give "how can we improve question input" dedicated focus after MVP as its own milestone.

Let's be careful of overloading ourselves with too much tinkering before we have real feedback. We have other priorities at the moment.

**Comment by davidmooreppf** [comment]
On page 2 of /questions/new ::

http://cl.ly/image/0d1q0q0Y0D29

... I think the first Q Summary field should display in two or three rows, showing the full amount allowed.
