### ISSUE TITLE
create an example of a prominent "verified" elected official

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#11]
Goal is to show elected officials how they'll look if they verify their account on the site. 

So here, for example :: 

http://oglocal.herokuapp.com/ny/people?type=Person

... let's take second person listed, Thomas Abinanti. Just at random at the top of the page.

Design-wise, I'd like him to have a fairly-big green check mark overlaid atop his profile photo. Bottom-right-ish of circle avatar, n'est-ce pas? 

Hover-wise, it should read "AskThem Verified". Could be longer I guess, but that should work. 

If it's easier than picking a real elected official, we could create a sample page of a sample legislator, some stock photo, unverified on the left & verified on the right. We can loop in Walter if need be.

**Comment by walter** [comment]
Done during lead up to launch.
