### ISSUE TITLE
embed .pdf of slide deck on AskThem.io

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#110]
Goal is to place this 5 MB doc. on the AskThem site, where it can be viewed by elected officials :: 

https://www.dropbox.com/s/t7151wkoybmcuj8/OpenGoverment-presentation-electeds.pdf

... e.g. at askthem.io/elected_officials

... I haven't added it yet to assets, though I can. We can hand off to Rob in ops if that's easier.

**Comment by walter** [comment]
Yeah, I think this should be moved to ops.
