### ISSUE TITLE
on question creation page, Twitter view, strip out extraneous copy 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#113]
On /questions/_recipient_step.html.erb, strip out :: 

"Your address information is private and safe!" and "Twitter users" label. 

... I could delete it in that file, just want to make sure it looks OK... 

... and I changed the copy to: Ask a question to any verified Twitter account.

**Comment by acacheung** [comment]
@davidmooreppf should we say Ask a question to any elected official's verified Twitter account?

**Comment by davidmooreppf** [comment]
No, b/c when we get there in the coding, we'll support (theoretically) any verified Twtr acc't. Good Q though.
