### ISSUE TITLE
on question composition page, bring over avatar & title of question target

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#115]
On 2nd of 4 pages in question composition process, currently after you select an elected official on the first page, the second page reads, "To: Jerrold Nadler". 

http://cl.ly/image/0j413b163i1N

... preferred behavior is to bring over the title & avatar photo for the elected official, so it reads, e.g. :: 

To: Rep. Jerrold Nadler (D, NY-10)

... with a photo somewhere in there.

@walter, this relates to #69 w/r/t the titles of elected officials from our APIs.

**Comment by walter** [comment]
@acacheung, please deal with the avatar and then assign this to me. The "(D, NY-10)" going to require some data munging and I don't think you'll be able to get to it tomorrow.

**Comment by acacheung** [comment]
reassigning to @walter to make avatar image and title dynamic

**Comment by walter** [comment]
@davidmooreppf - let's deal with titles and their formats separately. It's a larger issue.
