### ISSUE TITLE
display "recent signatures" on question detail pages in right-hand sidebar

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#116]
Maybe not MVP. But as with :: 

http://www.change.org/petitions/stand-against-russia-s-brutal-crackdown-on-gay-rights-urge-winter-olympics-2014-sponsors-to-condemn-anti-gay-laws

.... below the signup form on right on Q pages ::

http://oglocal.herokuapp.com/ny/questions/5230d8f0d3cffc9785000005?created=true#

... add in list of Recent Signatures, displaying firstname, lastname, city & state, and a timestamp. 

Re-assign to @acacheung if she can start this for you to hook up.

**Comment by walter** [comment]
@acacheung if you have time, a mockup with static data would be great.

**Comment by acacheung** [comment]
@davidmooreppf can people visit other user profile pages? If so I will make their names clickable
