### ISSUE TITLE
export a screenshot of every elected officials' profile page in the app? 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#120]
Just wondering - this isn't vital - on the outreach / marketing side, goal is to include a screenshot of elected official's profile page in individual outreach emails to them, to get them to sign up. 

Does there exist a Rails plugin or simple solution for taking a screenshot of every page in the app, specifically person profile pages, 

... then uploading to Dropbox, either with or without a unique ID attached so that we could match email addresses w/ screenshots? There can be some manual clicking in here, that's fine. 

Wonder if you know any solutions, @walter @derekeder @acacheung. 

I know a lot of city electeds & exec branch electeds (state & city) aren't loaded into the app, so this would primarily be for federal members of Congress & state legislators at first.

**Comment by walter** [comment]
What we use for interacting with things in our automated integration tests has the ability to take screenshots (PhantomJS). I've heard people use it as a "crawler" as well to capture full text of JavaScript only web apps (thus leaving a Google crawlable copy of the site).

I imagine we can put something together to do it, but it will take a little bit of work.

If anyone knows of a service that does this, it might be a cheaper option compared to the labor necessary.

**Comment by davidmooreppf** [comment]
Good to know - customizing a crawler is not priority now - unless anyone else knows a service / other solution.

**Comment by walter** [comment]
Moving this to a product issue (opengovernment/product#9).
