### ISSUE TITLE
Sort potential recipients by type of office on questions#new

### ISSUE THREAD

**Issue by walter** [opengovernment/askthem-legacy#121]
As mentioned in #114...

Right now the sorting of officials that are potential recipients is somewhat arbitrary. If possible, sort by office held and group senators with senators, etc.

**Comment by walter** [comment]
@acacheung what I could use are some design/frontend code of how we would differentiate those holding different offices.

I.e. what are some ways that we could visually distinguish Senators from Representatives, etc.?

**Comment by davidmooreppf** [comment]
Walter, any way to display in descending levels, from federal to state to municipal? If not, that's not vital for launch.

**Comment by walter** [comment]
Possible, but it's kind of a hassle and I wouldn't add it before launch.
