### ISSUE TITLE
question sorting and listing

### ISSUE THREAD

**Issue by derekeder** [opengovernment/askthem-legacy#124]
On question listing page (http://oglocal.herokuapp.com/pa/questions):

![screen shot 2013-09-16 at 4 37 25 pm](https://f.cloud.github.com/assets/919583/1153013/3f6b7f46-1f18-11e3-8cea-90dd0a84f4ab.png)

Add ability to filter questions that:
- NEED SIGNATURES 
- HAVE ANSWERS 
- NEED ANSWERS 
- RECENT

**Comment by evz** [comment]
@walter Just getting started on this today. I think I get the intent behind the first three filters but what's the idea behind the "Recent" filter? Isn't the page sorted in reverse chronological order by default?

**Comment by walter** [comment]
Good question. I would think "latest" questions would be the default, yes. @davidmooreppf how do you feel about the "recent" button? I would simply drop it from filters.

**Comment by walter** [comment]
@davidmooreppf is @evz still finishing this last thing for us? If so, I think it should stay assigned to him.

Still need an answer about "recent" button.

**Comment by davidmooreppf** [comment]
Last I heard from Derek, @evz was gonna try! Over to him to update. 

I think 'recent' is worth keeping, b/c ideally our algorithm for default display of Q listings will weight Qs with more questions. So let's keep it for now please. 'Recent' is exactly that, latest submitted by users.

**Comment by evz** [comment]
Hey guys, sorry about the delay on this. I was able to get a start on this on Friday and am still hoping to finish it up.

**Comment by walter** [comment]
Ok, assigned back to @evz.

So "recent" should stay and the default should be descending by number of signatures (aka popular questions)... hmm. 

@davidmooreppf, I would actually say that is counterintuitive as questions with the most signatures are likely to be older than new questions. If we say that any questions that have already reached their threshold are dropped from the list of "popular" questions it might weed out the very old questions.

**Comment by evz** [comment]
@walter I'm getting kinda stuck on this one (probably mainly due to the fact that I'm still ramping up my Rails skills). Any chance I contact you offline (maybe via email) to get a bit of help with the inner workings of the various moving parts here?

**Comment by evz** [comment]
@walter I think I may have a working implementation going over [here](https://github.com/datamade/askthem/tree/sorting). Still need to get some specs going. I'm also not sure how efficient some of the queries in the controller will be once the app scales up a bit (in particular [this one](https://github.com/datamade/askthem/blob/sorting/app/controllers/questions_controller.rb#L18) and [this one](https://github.com/datamade/askthem/blob/sorting/app/controllers/questions_controller.rb#L23). Any recommendations there would be appreciated.
