### ISSUE TITLE
from homepage, upon address entry, direct to question listing

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#126]
From homepage, when user enters zip code, we've been playing around with either going to question listing or showing elected profiles. 

I think we need to direct visitors to interesting content, so let's go with former. Direct visitor to federal questions near that address. Sound good?

The elected dashboards can still be used in a separate issue of course. They look great too.

**Comment by walter** [comment]
Made this switch during work on #119.
