### ISSUE TITLE
add-in "ask question" button on results page for "questions near you"

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#128]
Follow-up to #119, from homepage, visitor now gets list of Q's and elected officials in another tab, ::

http://oglocal.herokuapp.com/locator?q=10013

... but we just need to add the "ask a question" button back to that page as well, up top in usual place, as on ::

http://oglocal.herokuapp.com/ny/questions

... assuming we have room. You can reassign to Amanda if you prefer.

**Comment by davidmooreppf** [comment]
Amanda, please add button.

**Comment by acacheung** [comment]
@walter this is what we were talking about earlier. to add the "Nobody has asked any questions yet!" partial to the bottom when there are no questions near you
