### ISSUE TITLE
AskThem logotype at 652x113

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#129]
Need a version of AskThem logotype at 652x113 px for CiviCRM email template header. 

I have an old Photoshop on my other laptop but was looking to not have to boot that up. Tried image resizing in Preview and it's not production-ready, haha.

**Comment by davidmooreppf** [comment]
(This was a note-to-self, I'll open Photoshop tmw morning and use the svg on the local app.)

**Comment by acacheung** [comment]
In case you haven't done this already

![logo](https://f.cloud.github.com/assets/1054686/1237899/cd1a81b2-29df-11e3-87cf-e3be79cb2085.png)

![logo](https://f.cloud.github.com/assets/1054686/1237908/e397b9e6-29df-11e3-86a9-d27f671dd0ee.jpg)
