### ISSUE TITLE
create link for /electeds on splash

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#131]
On splash page, goal is to create a link ::

askthem.io/electeds

... which goes to the "elected officials" view on splash. As opposed to having to click that 'tab'. This has been requested by our outreach team.

**Comment by davidmooreppf** [comment]
Hmm, not showing up yet :: http://askthem.io/electeds , or at http://oglocal.herokuapp.com/electeds

We'd like the plaintext link askthem.io/electeds to work when clicked from an email.

cc @rchekaluk - didn't yet see a link to /electeds in the HTML for the splash page layout. If that helps, don't know.

**Comment by rchekaluk** [comment]
The /electeds page currently defaults to notify_type "individual", should be "elected_official"

**Comment by davidmooreppf** [comment]
Gahhhh - can I fix that? /electeds should go to elected official group in CiviCRM. But I don't see /electeds on layouts /splash.
