### ISSUE TITLE
Adjust design of questions/officials near address results page

### ISSUE THREAD

**Issue by walter** [opengovernment/askthem-legacy#132]
On the homepage or in the header of most other pages, if you enter an address or zipcode into the "near you" form, you arrive at list of questions near you along with tabs for elected officials:

E.g. http://oglocal.herokuapp.com/locator?q=148+Lafayette%2C+NY%2C+NY+10013

The placement and prominence of the Questions/Elected Officials tabs and the Federal and State tabs could use work.

**Comment by acacheung** [comment]
@walter Do you think we should just say "Questions Near You" and "Your Elected Officials" instead of the full address?

**Comment by walter** [comment]
In theory someone could be searching for an address other than where they are/live, but that seems less common... so I'm ok with "Near You" and "Your...".

**Comment by davidmooreppf** [comment]
So Amanda this still lives with you. 

Placement & prominence of the two tabs OK? 

I think the Federal & State tabs under elected officials look nice. Over to you.

**Comment by acacheung** [comment]
@davidmooreppf This looks fine, but we could make Federal and State more prominent like how Questions and Government are on state pages. Thoughts?
