### ISSUE TITLE
When we have more than one city for a state, how will the navigation work?

### ISSUE THREAD

**Issue by walter** [opengovernment/askthem-legacy#133]
Our shared navigation main tabs are split into the following list of tabs:

[State Name] Federal    [State Name] State    [City Name]

E.g. http://oglocal.herokuapp.com/pa-philadelphia/

What should the right most tab look like when we introduce more than one city for a state?

**Comment by davidmooreppf** [comment]
Does our local-electeds API lookup return a presumably- 'definitive' city name for every five digit US ZIP?

**Comment by davidmooreppf** [comment]
Reassigning this to you, Walter, as we won't have it figured out before Amanda drops off again.

**Comment by walter** [comment]
Here's my current proposal:
- at the level that we list "(State name) Federal" and "(State name) State", show the "closest" city to the user if we can make a guess (e.g. someone is looking at New York pages and lives in Albany, show them "Albany") based on either registered location or IP address
- if we can't determine "closest", pick an arbitrary city (state capitals?)
- either way, next to the city name have a <sup>[change]</sup> link that triggers a modal menu of the state's cities and counties where the user can change to a city or county of their choice and the application will remember the choice for the duration of their session

**Comment by davidmooreppf** [comment]
Those are good among available options; I wonder if for now it's best not to show cities in the nav, unless we have them pretty well (Philly, San Jose, Chicago, NY). Least confusing for visitors. So status quo in nav is my suggestion. 

Can we load county electeds to show only through the /questions/new process?

**Comment by walter** [comment]
> Those are good among available options; I wonder if for now it's best not to show cities in the nav, unless we have them pretty well (Philly, San Jose, Chicago, NY). Least confusing for visitors. So status quo in nav is my suggestion.

Yeah, the idea would be to only show the city and the <sup>[change]</sup> if we have cities and/or counties for the state.

> Can we load county electeds to show only through the /questions/new process?

I wouldn't overcomplicate things by excluding them at this point. Or more accurately, let's see if we have problem with county officials being too much information before figure out how to handle it. Let's see if it is a problem first.

**Comment by walter** [comment]
> either way, next to the city name have a [change] link that triggers a modal menu of the state's cities and counties where the user can change to a city or county of their choice and the application will remember the choice for the duration of their session

Slight amendment. Not necessary to remember choice for session, but otherwise <sup>[change]</sup> as proposed.
