### ISSUE TITLE
reduce signup fields to firstname, lastname, email & ZIP Code

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#135]
I think we do want to encourage lots of signups on Q's, so I think we should strip down the fields required for signing a Q, if we can, to simply ::

http://oglocal.herokuapp.com/ny/questions/52155a0c27b71b1536000004

First Name

Last Name

Email

ZIP Code

... then the sign button.

... no street address, no password. I'll write a new issue handling that; e.g. if a visitor has already signed a Q but not yet registered a street address with AskThem.

**Comment by walter** [comment]
On the backend side we need to turn off the requirement for address, etc. Will do that shortly.

**Comment by walter** [comment]
Hmm. Password has also been dropped. That's a problem for allowing the user to login later.

I'll see if devise gives us a way of handling this scenario.

**Comment by walter** [comment]
Ok, I'm not seeing a quick "flip-a-switch" way to handle not requiring a password at sign up.

So here are the options as far as password:
- reinstate it in the form for signing a question as an unregistered user (easiest route technically, but perhaps bad UX)
- auto-generate a placeholder password for the user, but immediately trigger a "reset password" email notification as per https://github.com/opengovernment/askthem/blob/master/app/views/devise/mailer/reset_password_instructions.html.erb for them to set it to their own password

I think the second option is the best, but we'll need to change the notification email's wording to handle the case of someone clicking "forgot password" as well as the new user that needs to set their password.

@davidmooreppf & @acacheung what do you think?

**Comment by davidmooreppf** [comment]
Second option is best - I can help w/ copy. Change doesn't req. pw upon petition signature. Good update Walter.

**Comment by walter** [comment]
@davidmooreppf the second option is now in place. Keep an eye out for anything weird having to do with user accounts though. We may have a few places that rely on user's state/city being set that I may not have caught.
