### ISSUE TITLE
intake form for elected officials signup on askthem? 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#137]
We've been collecting elected official signups via G-form ::

https://docs.google.com/forms/d/1iCRzEuDL6bGEkmMsTVrlH-DlQYnMX4KhSF32_tPgT8o/viewform

... can we embed that same intro copy and those same input fields on a page on AskThem? E.g. at :: 

askthem.io/elected_signup

... this isn't a huge priority, but if there's an easy way to create HTML page for that form, we can add them to our CiviCRM. 

cc @walter, @rchekaluk - Rob, they'd be a new category in CiviCRM, "elected official committed" or something. Different from elected officials, who just want to be contacted.

**Comment by davidmooreppf** [comment]
This is a good one to do, still, let me know if I can help with the G-form.

**Comment by davidmooreppf** [comment]
<iframe src="https://docs.google.com/forms/d/1iCRzEuDL6bGEkmMsTVrlH-DlQYnMX4KhSF32_tPgT8o/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

760 x 500 , that is

**Comment by davidmooreppf** [comment]
Sign up for AskThem as a leader in transparent, accountable and engaged government.

AskThem is a new question-and-answer platform for elected officials. It's free, open-source, and non-partisan, from the Participatory Politics Foundation, a registered 501(c)3 non-profit organization. By signing up here, you agree to participate in AskThem by responding to questions from the public that reach the signature threshold. The signature threshold will start at .1% of the total population you represent, with at least half of the total coming from constituents. We'll be continually experimenting with and changing signature thresholds so you can expect your threshold to be altered several times during the first few months after launch. Our goal is to set thresholds so that approximately three questions per month reach the threshold. Feedback is welcome, and we'll let you know how many of your constituents have signed every question.

You also agree that AskThem can include your planned participation in public statements and press releases about our upcoming launch & user community. Your profile page on AskThem will receive a "verified" check mark and you'll be able to regularly contact by email all of your constituents who ask you questions. We'll send you the simple registration process and site Terms of Service in the next few weeks, so you can see a site preview well before we launch.

**Comment by acacheung** [comment]
can't style it tho grrrr
