### ISSUE TITLE
image for email header including AskThem logotype & copy & link

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#138]
As in the email I forwarded you, goal is an email header image that's 652x113 total. 

Blue background, as in the site. 

Top, central element, is AskThem logotype in orange. 

Below, copy (color can be whatever, the gray is fine), centered :: 

The new non-profit project from the creators of OpenCongress.org - http://askthem.io

If you can commit it to folder /images/CiviCRM_email_assets, that's great, and let me know the filename here. Suggestion :: AskThem_email_header_Oct.png 

... should be optimized for display in emails, of course. Thanks!

**Comment by acacheung** [comment]
The file names are: email-header-symbol.jpg and email-header-no-symbol.jpg. wasn't sure which one you wanted, so I gave you both! Let me know if these work out

**Comment by acacheung** [comment]
@davidmooreppf ^

**Comment by davidmooreppf** [comment]
Ah word - may need @walter to deploy in order to see these, as this isn't showing up yet.

http://oglocal.herokuapp.com/images/CiviCRM_email_assets/email-header-symbol.jpg

**Comment by walter** [comment]
Actually it is, but your URL is wrong:

http://oglocal.herokuapp.com/assets/CiviCRM_email_assets/email-header-symbol.jpg
