### ISSUE TITLE
experiment with placing Question Mark logo in header

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#139]
Once handed-off from Logan, interested in your input - options seem to be :: 

http://oglocal.herokuapp.com/ny/questions/5232378a29dc1e110c00001a

(realize the header is crowded, with the Ask A Question link & search-box there in the header on Q detail pages)

a) Fairly big on left-hand side, with logotype next to it coming off the right edge? Trying that again. 

b) Keeping logotype far-left, moving logo to far-right - maybe above "Sign up" options, or just to the left. I mean, worth checking out a few places. 

c) I guess the third option would be more centered, haha, separating Ask a Question link and "See questions & petitions near you" field. 

Interested in your input on whether the logo should be white in a dark background, or be dark itself, and on colors.

**Comment by acacheung** [comment]
@davidmooreppf what do you think? not bad...

![symbol](https://f.cloud.github.com/assets/1054686/1240785/17dc88bc-2a12-11e3-9619-fababbae91fb.png)

**Comment by acacheung** [comment]
but i think i like it best with just the type in the navy

**Comment by davidmooreppf** [comment]
I like the placement of the logo, actually, and I'm hearing from my Board that they prefer the orange logotype too. 

cc @walter for his input. I know the plain navy logotype is nicest from design POV, but some of my team thinks the orange mark helps. 

Does navy logo work alongside orange logotype? 
- while we're in the header, is this the best spacing? 

http://cl.ly/image/3Q3C0G1F1g2g

... or can we right-justify the "Search" part, and center the "Ask a Question" link?

**Comment by walter** [comment]
Have y'all settled on the question mark being inside a circle?

One thing I like about the text is that is slightly slanted and implies speed. I wonder of having the question mark in a slanted parallelogram (kinda /?/, but with the question with matching slant) might be something to try.

The orange is growing on me.

**Comment by davidmooreppf** [comment]
This is the version that Logan, designer, was able to get to Amanda. I would like to also have a version where it's not white in a circle, but rather dark color on top, with the dot at the bottom of the question mark being dark and the star being white. i.e. the reverse. Is that straightforward for you, Amanda? 

The slant idea is cool & good, Walter, but might have to be a next iteration, unless Amanda has time to try it. 

Amanda, not to be tiresome, but tmw I'd like to please try :: 
1. Blue logo dark / orange mark
2. Blue logo in-circle / orange mark 
3. Orange logo dark / orange mark 
4. Orange logo in-circle / orange mark 
5. ... and blue-or-orange logo, in or out of cirlce, with the blue mark, if you think it looks good.

**Comment by acacheung** [comment]
![logo1](https://f.cloud.github.com/assets/1054686/1246667/6cd01f98-2ab0-11e3-8dd0-533a83b94136.png)
![logo2](https://f.cloud.github.com/assets/1054686/1246668/6cd7fd9e-2ab0-11e3-8d62-01b0d4db1532.png)
![logo3](https://f.cloud.github.com/assets/1054686/1246669/70e05b70-2ab0-11e3-9793-73a9f7d702cf.png)
![logo4](https://f.cloud.github.com/assets/1054686/1246670/70e0076a-2ab0-11e3-809d-d988b7996000.png)
![logo5](https://f.cloud.github.com/assets/1054686/1246671/70e9e8ac-2ab0-11e3-94c0-14728af3e3ed.png)
![logo6](https://f.cloud.github.com/assets/1054686/1246673/7472bf26-2ab0-11e3-9e2b-aca6e864299f.png)
![logo7](https://f.cloud.github.com/assets/1054686/1246674/7473ef54-2ab0-11e3-8b85-7d5d729754bc.png)

**Comment by acacheung** [comment]
@davidmooreppf thoughts?

**Comment by davidmooreppf** [comment]
Thanks for these, getting input. 

I think, fifth and second versions are best, in that order. I.e., generally the logo in-circle, and same color logo & mark.

... seventh isn't bad though.  

What do you & Steve think? Fifth version?

**Comment by LoganFaerber** [comment]
I personally would simply keep the "AskThem" portion of the logo up there without the question mark icon or the orange. I think the logo looks best in the dark blue and if the user is here already here using the site we don't need to remind them so prominently of the brand. When you add orange I think it commands too much attention to itself and starts to distract the user from the rest of the page, including the calls to action where you actually want the user to go and begin participating. The more subtle and clean we can make this area of the page, the better. That way the user can get right to the content. I think we can still use this question mark icon elsewhere, but I don't think this is the right location.

**Comment by davidmooreppf** [comment]
Good stuff Logan, I hear that. We're considering. But that makes a lot of sense. 

@acacheung please try one more variant, orange & white in-circle logo & blue AskThem logotype. Thx.

**Comment by davidmooreppf** [comment]
@LoganFaerber, forgot to add - sites like Change & Kickstarter can be counted on to generally have a strong user-generated image element in the page. Questions on AskThem may not have any media, and other than faces of elected officials, and the signature threshold progress bar, we don't have much to draw on by default. (In the future we could have city-specific imagery, or issue area icons, or more related info such as vote graphs or agenda documents or campaign donations - but at first it's just text. Hence the feeling of needing something more exciting.

**Comment by walter** [comment]
+1 @LoganFaerber's "this branding doesn't need to be prominent, because they are on the site already and want to get to the content".

People want to get down to the content of the page. I wouldn't worry about it not being that exciting. If the content is something they are interested in, they will be engaged. If not, it's a problem with the content, not the site design.

Now, places like the splash page, or other areas where the purpose is to highlight the brand, it may make sense to amp the logo up.

**Comment by acacheung** [comment]
![logo8](https://f.cloud.github.com/assets/1054686/1249275/179ccb34-2add-11e3-8e7b-ddf520bb63cc.png)
![logo9](https://f.cloud.github.com/assets/1054686/1249276/1797f5b4-2add-11e3-9c3f-e634a044dbe6.png)

@davidmooreppf

**Comment by davidmooreppf** [comment]
Checking with the PPF Board friends - I think the second one looks nice. Will update. Thx for your patience everyone.

**Comment by walter** [comment]
@davidmooreppf is this done?

**Comment by acacheung** [comment]
@davidmooreppf can we close this out?

**Comment by davidmooreppf** [comment]
We can close this for now. My core team of Nick, Tiffiniy & Holmes may have some input on the logo in the header or not. But I think blue type is best over orange. Good to have tried these though.
