### ISSUE TITLE
two additions to /questions/new page (2 of 4) - media link & custom hashtag

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#141]
[Ahh began writing this up and realized it's more programming-intensive than first seemed, so assigning to myself. But like these goals, still, for public launch.]

Ohh @walter you're gonna slap me on the wrist for outrunning our UX planning, but I feel it's important to add two options to bottom of page 2 of 4 of question creation - while we have Amanda tmw ::

http://cl.ly/image/2k3T3X2s3937

a) As mentioned in #68, let's offer the option to include a media link - just as on Change ::

http://cl.ly/image/2O3t3C1b1f1T

... should be marked as optional, but we'll use the same help copy as they do for now. We'll tweak it shortly. 

Will require display of media on Q detail pages, which currently we haven't allowed for though. 

b) As mentioned previously, not sure about an issue - let's add an optional user hashtag to be able to track a personalized campaign, e.g. "#NSAreform" or "#HoustonSchools". We'll have to build out the views / search on hashtags on AskThem, but having it in there is impt. for users to track their campaigns, and for Twtr integration. 

Should also be marked as optional, and be a text field with a set character limit - say around 100 characters at most? (Allowing for goofy ones). 

Text as :: Optional: set a custom hashtag for your question or petition. 

.... would then have to search to see that we can allow it, and that it's not duplicate, etc. ... ah jeez. 

Again, Walter, sorry to be pushing on this, we can discuss! But let's aim to support both for now. I put them both here so that Amanda can add them to /questions/new, I'm thinking just above the "next" button. On their own rows is fine, I think, they're both pretty long.

**Comment by walter** [comment]
Closing as this is a duplicate of #183.
