### ISSUE TITLE
Page title for AskThem.io somehwere in HTML still holds "OpenGovernment" 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#143]
When you enter landing page http://askthem.io into Facebook, just as you would add a link, it comes up as OpenGovernment, with a screenshot of Steve's handsome mug. 

OpenGovernment isn't in the /splash page layout anywhere - the page title in the chrome of the browser is correctly AskThem - for questions and petitions etc. etc..... 

... so somewhere it's grabbing OpenGovernment. It's not in pages/index or pages/splash either. 

Goal is to have the link titled, when entered into FB, AskThem - questions and petitions with public figures, and for the image associated to be the AskThem logotype in orange. cc @walter in case Amanda can't find this.

**Comment by walter** [comment]
@rchekaluk, any chance this is hardcoded in your code somewhere?

**Comment by rchekaluk** [comment]
Yes the confirmation page hardcodes OpenGovernment per previous request; will revert that now.

**Comment by walter** [comment]
@davidmooreppf can you close this if problem is now resolved, please.

**Comment by walter** [comment]
Found another hardcoded source of "OpenGovernment". Will be included in larger commit.
