### ISSUE TITLE
confirmation page after user signup / registration

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#144]
on users/sign_up, after submitting the info, currently the app directs to homepage. 

Should have a different flow here. cc @walter

**Comment by davidmooreppf** [comment]
Re-directing to homepage is fine, actually - we just need a banner or a modal with copy such as :: 

We've sent an email to [email] to verify your account. To complete your registration, click on the link in your email.

**Comment by walter** [comment]
On the design side, we may need styles for handling this type of banner. Basically, how should it look?

If I remember correctly we can simply "turn it on" as far as the programming side (and set text), but I want make sure that the we can accommodate the banner design wise.

**Comment by walter** [comment]
Since @acacheung is coming back next week, I can prepare the programming side for it and then have her style it next week.

**Comment by davidmooreppf** [comment]
Currently, /users/sign_up redirects to homepage w/ no banner.

Should display banner or modal w/ copy as above.

**Comment by davidmooreppf** [comment]
I wasn't thorough and I didn't get this issue in to Amanda during our time with her. My fault. 

Can you implement the banner in this case Walter? When a new visitor arrives on homepage, clicks "sign up" in top-right, then fills out & submits users/sign_up, can we re-direct to homepage as current, but show small banner w/ confirmation copy as above from four months ago?  

We've sent an email to [email] to verify your account. To complete your registration, click on the link in your email.

... just to reflect that the info was saved & another step will be required in confirming email.  

... the banner can be closed w/ an 'x', ideally, so the user can get started w/ the site.

**Comment by walter** [comment]
Done, except for the x to dismiss. Not worth the trouble as the banner disappears upon moving to next page and is not intrusive.
