### ISSUE TITLE
state elected official profile page tweaks

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#146]
remove extra 'ask' button

fix formatting

http://oglocal.herokuapp.com/ny/people/NYL000112/committees

**Comment by acacheung** [comment]
weird thing happening here. extra 'ask' button only appears sometimes.

**Comment by walter** [comment]
Just noting that I fixed the extra ask question button in 253ff834b8620c1bae7d20d47d28551668dfb8ca.
