### ISSUE TITLE
info & page formatting on user dashboard

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#147]
Needs some spacing ::

http://oglocal.herokuapp.com/dashboard

https://www.dropbox.com/s/55jjxp5kzq4h9ay/Screenshot%202013-10-01%2014.54.55.png

Question titles 
- if possible, with recipient avatar & title 
- date 
- progress bar (will this fit?) 
- Anything else? 
- questions you've signed

Ideally we could show elected officials here, but that's more lookup, so not MVP.

cc @walter

**Comment by davidmooreppf** [comment]
Actually holding off on this, as profile pages may be sufficient, if dashboard doesn't have elected officials. 

Change has "My petitions" and "profile", so we could have "my questions" and "profile", where the latter is just personal info. 

Over to you @walter.  

http://oglocal.herokuapp.com/users/5205100e9a43d51b97000003

**Comment by walter** [comment]
To be clear, as a logged in user my user specific navigation should change as follows, correct?
- dashboard goes away (as it is duplicate or "my questions" - aka profile)
- "profile" link is changed to "my questions"
- "account" link is changed to "profile"?

As far as "account", I think I would stick with either "account" or change it to "settings".

**Comment by davidmooreppf** [comment]
Exactly - Dashboard goes away, profile is "My Questions", "account" becomes "profile", and let's go with settings.
