### ISSUE TITLE
on questions listing page, increase size of recipient avatars?

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#149]
On pages of Q listings ::

http://oglocal.herokuapp.com/ny/questions?type=FederalLegislator

... I think the faces of the targets are a bit small. I understand they're on the same line as a username, which usually won't have an avatar, but can we either 

a) make them bigger than username, or 

b) make both bigger? Maybe this isn't advisable.

**Comment by acacheung** [comment]
made both bigger!
