### ISSUE TITLE
QA & UX on social sharing modal - 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#151]
On pages of submitted Q's ::

http://oglocal.herokuapp.com/ny/questions/524b3023e56965f10c000003?created=true

... social sharing modal QA :: 
1. Email link results in subject heading "help get an answer...", which is fine, but body is currently blank. Should include link to question and help copy, e.g. "Sign on to my question at AskThem, a free website for questions and petitions with public figures: [Link]. The more signatures it gets, the higher it rises in the ranks, and the greater chance that it will receive a public answer. 
2. FB link results in :: “What is position on shutdown of gov't? ” - New York - AskThem, http://oglocal.herokuapp.com/ny/..., Show your support for this question by adding your signature 

... that's all pretty fine. I'd argue we can drop the geographic location. Obvs. we can test this. It could also be titled, Help get an answer to my Q on AskThem, with the Q summary in the second field on FB.
1. Twtr link results in: Help get my question answered on AskThem: What is position on shutdown of gov't?  http://oglocal.herokuapp.com/ny/questions/524b3023e56965f10c000003?created=true 

... I just turned AskThem into @AskThemPPF (for Twtr linking to our account). Future enhancement: add in custom hashtag when set by user. 

@acacheung I can see the modal-content in /questions/show, but didn't know how to set the email body & FB content.

**Comment by davidmooreppf** [comment]
http://css-tricks.com/snippets/html/mailto-links/ thx Amanda

**Comment by walter** [comment]
Superseded by #270, #295, & others.
