### ISSUE TITLE
Add-in font image of all 50 states on far right of site header

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#152]
where clicking on a state defaults to federal view Q listing :: 

http://oglocal.herokuapp.com/ny/questions?type=FederalLegislator

... let's try using this font pls. that @Walter suggested ::

http://intridea.github.io/stately/

...Goal here is to enable view of all federal NY state Q's that's separate from "by location" view :: 

http://oglocal.herokuapp.com/locator?q=10013

**Comment by walter** [comment]
Have talked about this with @acacheung and fitting in states map into top right of header is not do-able size wise.

We talked about having a trigger that reveals the map for navigation. I'm thinking of a combination approach:
- have "go to x", where x is the state name that we detect the user's ip address is from as well as the state's icon
- have a "go to another state" (better language?) next to it that triggers the full map being shown in a slide down reveal

Thoughts?

**Comment by walter** [comment]
@acacheung note that you can use the default_jurisdiction method in controllers and views to get the current_user's state:

https://github.com/opengovernment/askthem/blob/master/app/controllers/application_controller.rb#L5

**Comment by walter** [comment]
@davidmooreppf here's the issue where I discussed the alternative UX with the "expand down to show map to choose state" UX.

**Comment by davidmooreppf** [comment]
OK we'll talk more about this Amanda - as above, goal is to provide a user a view to these pages ::

http://preview.askthem.io/ny/questions/

... through a link in upper-right of header. That when clicked, would drop down and reveal a larger national map, allowing the user to click on each state name and go to /questions there. 

So what do you think, Amanda - copy as "See All States" ? How time-intensive is such a drop-down?

**Comment by walter** [comment]
@acacheung see ^. Can we repurpose the work done in #158 to accomplish this?

#158 is exactly what I had in mind visually and functionally. All we seem to need is be able to have "slide down" or animate into place some other way (or a modal).

**Comment by acacheung** [comment]
![screen shot 2013-12-18 at 2 04 30 pm](https://f.cloud.github.com/assets/1054686/1776454/4516ecee-6817-11e3-9160-eda616271fbf.png)

**Comment by walter** [comment]
In Safari for me, the "See the Map" is dropped down to a new line and on the left.

I also think the idea for this is to have a JavaScript backed animation to reveal the map (and also make it possible collapse it).

The copy should also indicate that it is a navigation tool. E.g. "Pick another state to view", but more succinct.

**Comment by acacheung** [comment]
discussed with @davidmooreppf earlier to have it as just a link
thoughts?

**Comment by walter** [comment]
I'm alright with it than.

**Comment by walter** [comment]
Oops. The copy and placement still need work.
