### ISSUE TITLE
add logo to social sharing modal

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#157]
Open to options

https://www.dropbox.com/s/ah31yh0vpzrgwi2/Screenshot%202013-10-09%2014.45.06.png

**Comment by davidmooreppf** [comment]
Just the question mark somewhere

**Comment by acacheung** [comment]
@davidmooreppf 
![modal](https://f.cloud.github.com/assets/1054686/1308382/b133f834-31cd-11e3-9d04-8398ebbc86bc.png)
