### ISSUE TITLE
national overview map with stats on number of Q's asked & answered

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#158]
Goal is to create a national map with question stats overlaid - any solution is fine. 

Realize I need to specify the types of stats that will go on the states. 

Page can be /US_states or something.

Lower priority.

**Comment by acacheung** [comment]
@davidmooreppf how about /map?

**Comment by davidmooreppf** [comment]
Page title: Questions and Petitions in All 50 U.S. States

Sub-title: Click on a state to see popular questions and petitions awaiting a public response.

**Comment by acacheung** [comment]
@walter reassigning to you to pass in states number of questions asked and number of questions answered under each states' hover tip.

**Comment by walter** [comment]
@acacheung current-state (e.g. current state is "ny" if you are on /ny/map), is now added for the state links. Would be good to make use of it to indicate current state for links.

It would also be great to have the map indicate the current state. Any idea on how to do that?

@davidmooreppf for now I'm skipping indicating number of answers as it's computationally expensive and I think we should hold off until we see we need it.

**Comment by walter** [comment]
Skipping the indication of current state for now. Doesn't have any real value with static page.
