### ISSUE TITLE
possible bug from Q publishing involving email already in database?

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#159]
Need to try to replicate. 

From last page of Q publishing process ::

http://oglocal.herokuapp.com/ny/questions/new?person=V000081

...  went back to this page ::

http://oglocal.herokuapp.com/ny/questions

... but with weird styling. Think it may have had to do w/ archived email address?

**Comment by walter** [comment]
Duplicate of #59. See there for more details. Closing this.
