### ISSUE TITLE
users signing questions get an email to confirm registration

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#16]
Just an issue for 6(c) on dev roadmap. 

When a new user signs a question, she gets an email to confirm her registration, then a follow-up email to share that question with her social network to push for an answer. 

Needs fleshing out.

**Comment by davidmooreppf** [comment]
Previous: with registration process to end users. (NOW IN OPS ISSUES)

**Comment by walter** [comment]
This looks like another good one for the Datamade crew. Divvy up (i.e. reassign) as you see fit.
