### ISSUE TITLE
Display of person's votes

### ISSUE THREAD

**Issue by walter** [opengovernment/askthem-legacy#161]
What makes sense to show here?

http://oglocal.herokuapp.com/ar/people/ARL000238/votes

The fields available per vote are here:

https://github.com/sunlightlabs/billy/wiki/Votes-fields

Here's what I think makes sense:

vote.session (e.g. 2013)
vote.bill.title (with link to bill using bill.id and bill.state)
vote.date (see formatting code for bill dates on bill template)
vote.value_voted_by(person) (e.g. "yes")
vote.yes_count
vote.no_count
vote.other_count
vote.passed?

@davidmooreppf, any thoughts on this?

Note that this only work for state legislators at the moment.

**Comment by walter** [comment]
@acacheung I've added some placeholder data for votes you'll need to import locally.

You'll need to get from the ops repository (clone it if you haven't already). It's under data_dumps/vote_dump.json.

Then import it, like so:

```
mongoimport -db askthem_development --collection votes --file votes-dump.json # note, change file path as necessary
```

**Comment by acacheung** [comment]
@walter i need help setting up the votes section

**Comment by walter** [comment]
This is a low priority for the moment.
