### ISSUE TITLE
code up design elements for emails from app

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#163]
From mockups

**Comment by acacheung** [comment]
@davidmooreppf here's the design from logan 
![screen shot 2013-10-10 at 1 30 16 pm](https://f.cloud.github.com/assets/1054686/1308628/dfacf932-31d1-11e3-8b29-11f05a6fb731.png)

**Comment by davidmooreppf** [comment]
Yep w/ AskThem logo & mark. 

Change header tagline to "Questions and petitions with public figures."
