### ISSUE TITLE
after new visitor signs a Q, show sharing modal, not "confirm email" message

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#164]
When a new visitor signs a Q, e.g. ::

http://oglocal.herokuapp.com/ny/questions/5255a417792169d952000002

... resulting message currently reads ::

https://www.dropbox.com/s/pnnvkzx1tjea8v9/Screenshot%202013-10-10%2014.40.32.png

.... instead, new visitor should receive the sharing modal, with a different version of copy up top: 

Thanks for signing. Check your email to confirm your signature with AskThem. First, share this and help it get more signatures for a public response. 

(... eventually, we'll probably refer her to partner-org questions.) 

As comparison, Change does a gallery ::

https://www.dropbox.com/s/kdni6xhi5qq1khm/Screenshot%202013-10-10%2014.49.27.png

**Comment by walter** [comment]
I think we want styles for what are commonly called "flash messages", i.e. the banner with the "You will receive..." message.

These type of messages may show up in many instances. I'll create a specific issue for styling them.

**Comment by walter** [comment]
So I can handle the setting up for the modal, but if @acacheung has the time it would be good if she took care of #165 first or perhaps point us in the right direction.

**Comment by walter** [comment]
Here's how it stands now (after other work around this process):
- logged out user visits question, fills out min-sign up form, clicks "sign" button
- they get sharing modal that reports how many signatures remain to deliver the question
- if they dismiss they modal, a banner is at the top that reads "We have sent an email with instructions about how to confirm your account."

I actually think this covers our bases (encouraging sharing, separating the confusing "confirm email" stuff out) and is good enough for now.

If we find it problematic, let's open a new issue to refine this later.
