### ISSUE TITLE
Style banner messages when we confirm or thank a user for taking an action

### ISSUE THREAD

**Issue by walter** [opengovernment/askthem-legacy#165]
As mentioned in #164, we need styles for flash messages.

Even though in the scenario mentioned #164 the banner will go away in favor of the modal, we still need these styles generally for banner messages.

**Comment by davidmooreppf** [comment]
Assigning to Amanda.

**Comment by davidmooreppf** [comment]
Still need this :: https://www.dropbox.com/s/kzavsesmiiul3o0/Screenshot%202013-10-18%2012.57.43.png

**Comment by acacheung** [comment]
@davidmooreppf What do you think?
![screen shot 2013-10-22 at 3 20 30 pm](https://f.cloud.github.com/assets/1054686/1384518/27db252c-3b4f-11e3-928a-b8eaff10917d.png)

**Comment by davidmooreppf** [comment]
Good! Think I can close it.
