### ISSUE TITLE
login w/ FB 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#168]
Changed, fix

**Comment by walter** [comment]
Looking into how to change our application as registered with Facebook's site name…

Have contacted @jpmckinney about it.

**Comment by jpmckinney** [comment]
Is this you on Facebook? https://www.facebook.com/walter.mcginnis If so, I'll make you admin on the app.

**Comment by walter** [comment]
Yep, that's me. Thanks.

**Comment by jpmckinney** [comment]
Should be good now. Feel free to remove me (I may need to remove myself, not sure).

**Comment by walter** [comment]
@jpmckinney done. :+1:

**Comment by walter** [comment]
Updated the application settings on developer.facebook.com for preview.askthem.io and everything came right.

Will have to update the application's site url again for askthem.io when we go live. However, that should be done as an issue in the ops repository as it doesn't require any coding changes.
