### ISSUE TITLE
customize sharing copy on social media services & email 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#169]
http://preview.askthem.io/pa-philadelphia/questions/525c14c6d2a57d8b13000009?created=true

**Comment by walter** [comment]
@davidmooreppf meaning that [question detail page](http://preview.askthem.io/pa-philadelphia/questions/528d0074d2a57ddd63000005) should have some "share this question" button/link that opens the standard modal?

How should the copy in the sharing modal differ when the person is not the original asker of the question?

Relates to #171.

**Comment by davidmooreppf** [comment]
Changing this to focus on personalizing the individual ask of the Q creator, post-Q-creation, e.g. "I made this". 

Seems it's not best practice to have social sharing icons atop pages when prompt is to sign.

**Comment by walter** [comment]
Closing in lieu of #240.
