### ISSUE TITLE
expand social sharing modal to split

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#171]
left hand side with thank-you copy & image (e.g. the logo) that I'll write momentarily 

right hand side with social sharing buttons as they exist 

thx @walter

**Comment by walter** [comment]
@davidmooreppf copy for this before @acacheung's time with us?

**Comment by walter** [comment]
@davidmooreppf ^ 

(i.e. pinging on the above mentioned copy)

**Comment by walter** [comment]
#191 mentions the copy "Share your Q".

**Comment by davidmooreppf** [comment]
As in :: 

https://www.dropbox.com/s/pgf9yt6bqgpo34v/Screenshot%202013-12-18%2015.14.13.png

**Comment by walter** [comment]
@acacheung I think the design can be a bit simpler than what is show above and as we discussed, less info from the question. Just an area for copy on the left, signature stats, and the sharing buttons on the right.

**Comment by davidmooreppf** [comment]
Copy on left will be something like :: 

Get more signatures and ask for a response! If this question reaches its signature threshold, we'll deliver it to the person's official contact information and promote it on social media. 

AskThem is free, open-source, and non-profit. Help us encourage open public dialogue by sharing this question now.  

---

... testing diff. value propositions, but about why-to-share, basically.

**Comment by acacheung** [comment]
![screen shot 2013-12-19 at 2 46 03 pm](https://f.cloud.github.com/assets/1054686/1785540/3fae313e-68e6-11e3-8521-21f8c0a2785e.png)

**Comment by davidmooreppf** [comment]
This is great, but instead of it being a modal, should it be its own page, Walter? 

Impt. to track click-throughs from here, obvs. Which is maybe easier on its own page?

**Comment by davidmooreppf** [comment]
Ahh also I forgot to include one necessary component here: this page (or modal) needs to remind the sharer of how many more signatures are needed. 

This should go above the "Get more signatures" copy. It can be the threshold bar again, or a different info display. 

Sorry for late-breaking addition to design. Need to remind sharer of this here.

**Comment by walter** [comment]
At this point I don't think we should switch from a modal to its own page for UX reasons (I.e. It's less hassle to return to the question's content).  I take your point about tracking, but I think we can figure out another way of doing that.

**Comment by acacheung** [comment]
![screen shot 2013-12-19 at 3 27 40 pm](https://f.cloud.github.com/assets/1054686/1785910/0abf2a36-68ec-11e3-86b2-2412fa0d1723.png)

@davidmooreppf do you think we need copy to go with the signature stats?

**Comment by walter** [comment]
I think it's pretty self-explanatory.

**Comment by davidmooreppf** [comment]
Looks great to me Amanda. Understood, Walter.
