### ISSUE TITLE
add email designs to emails confirming acc't registration

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#172]
When you're back on AskThem, whenever that will be, 

Please add-in email CSS however / wherever you did with other emails, @Walter & I couldn't find it offhand but he thinks you know where it lives.

I'll add copy tweaks to /devise/confrimation_instructions

**Comment by acacheung** [comment]
@davidmooreppf this has been pushed to http://preview.askthem.io/ Let me know what you think of the email styles.  We can't get too crazy here though, it wouldn't even pick up my border styles...
