### ISSUE TITLE
on homepage, default for right-hand side of "questions near you" when null

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#174]
Improve

**Comment by walter** [comment]
@davidmooreppf, shouldn't this be a call to action? I.e. a big ole "ask the first question in your neighborhood!" kind of thing.

**Comment by davidmooreppf** [comment]
Yeah - we'll aim to have a Q from Fight For the Future to every Cong. district, and I think probably at least one or two other national orgs. at launch... that's the goal, so we should be able to achieve three Q's for homepage, even if we have to place one of them ourselves... 

-- but ideal is, below that, for there to be copy as :: 

Ask one of the first questions in your area! 

.. then the "ask your own question" button, if we have it in a smaller size, or a link to /questions/new. I'll keep this with me for now, though, as it might not be necessary.
