### ISSUE TITLE
on pages of Questions Near you, add elected official faces

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#177]
On http://preview.askthem.io/locator?q=19106# , add-in one or two elected official faces to the right of "Your Elected Officials"

**Comment by davidmooreppf** [comment]
This may be for @walter, but mentioning it here in case you get to it, Amanda.

**Comment by acacheung** [comment]
@davidmooreppf will this be confusing? it might seem like those one or two are your only elected officials. Thoughts?

**Comment by davidmooreppf** [comment]
Hmm I hear that. We could either have a tiny "View all", or a "...". 

The goal was to emphasize that valuable info. Since we default to a q view from a homepage zip code lookup, a new visitor might not even see that she can see all her elected officials. 

Which is great info! And we spent a lot of time & resources on assembling, and it's a unique value proposition. How do highlight this link then. 

![screenshot_2013-10-22_15 09 23](https://f.cloud.github.com/assets/116819/1384449/8e65b55c-3b4d-11e3-9cb1-872001f15190.png)

**Comment by davidmooreppf** [comment]
Change to "See Questions Near You" and  "See Your Elected Officials" 

... and try the default person image.

**Comment by acacheung** [comment]
![screen shot 2013-10-23 at 10 50 59 am](https://f.cloud.github.com/assets/1054686/1390756/967ac26e-3bf2-11e3-8488-b0cab5798cef.png)
