### ISSUE TITLE
Add copy from FAQ page to site

### ISSUE THREAD

**Issue by maryamgunja** [opengovernment/askthem-legacy#179]
https://docs.google.com/a/askthem.io/document/d/1oA552J5GFOo9I6fAUoCWtzAyjnEJqjKykpqEZkV1Ixw/edit

**Comment by davidmooreppf** [comment]
@maryamgunja cc

**Comment by walter** [comment]
This is already listed in #41. Closing this, will add copy shortly and reassign #41 for styling.
