### ISSUE TITLE
HTML fix on Google Form /elected_signup

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#180]
Hunh, somehow on ::

http://askthem.io/elected_signup

... bug up top w/ the way the permanent site header search-box interacts with G-Form. 

Works OK here, from where it's scraped ::

http://oglocal.herokuapp.com/elected_signup

... maybe this is a trivial HTML thing, I haven't looked.

**Comment by acacheung** [comment]
@davidmooreppf for some reason the header form is missing a class of "slogan", but it's there in application.html.erb...
