### ISSUE TITLE
add-in name search field on question creation page

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#182]
On page ::

http://preview.askthem.io/ny/questions/new

... we need a third "locate by" option, which is: Search by name. 

... I'm thinking a text field with copy in it, "Their Name".

... if it can be the second option, before "their Twitter name", that's great. So I'm not sure if the "Their Twitter name" button will have to be on a third line. 

@walter will hook up the search functionality obvs.

**Comment by davidmooreppf** [comment]
Assigning to AC.

**Comment by acacheung** [comment]
reassigning to walter for functionality

**Comment by acacheung** [comment]
@davidmooreppf 

![screen shot 2013-10-22 at 3 05 24 pm](https://f.cloud.github.com/assets/1054686/1384403/f69242e0-3b4c-11e3-972a-505c255625ea.png)

**Comment by davidmooreppf** [comment]
Cool - I can't see this yet (http://oglocal.herokuapp.com/ny/questions/new), but clicking Their Name should pop open a search box (kinda like with the Twitter button) and Walter will need to hook it up to our DB of electeds' names.

**Comment by walter** [comment]
Previous commit finished this work.
