### ISSUE TITLE
two additions to /questions/new page (2 of 4) - media link & custom hashtag - for Amanda

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#183]
After clearing this with @walter, - as mentioned in #68, let's offer the option to include a media link on second page of Q creation process :: 

https://www.dropbox.com/s/zwjl7b3s0tq6aez/Screenshot%202013-10-22%2011.18.43.png

... UI basically as on Change ::

http://cl.ly/image/2O3t3C1b1f1T

... should be marked as optional, but we'll use the same help copy as they do for now. 

So: "Paste a link to a photo or video" is fine. 

I do guess we should allow users to upload a photo as well. 

---

Add'l issue to discuss here is whether we can display these user-generated images in the question listing pages somewhere, e.g. ::

http://preview.askthem.io/pa/questions/

---

Second is ability to add an optional custom hashtag w/ campaign. Goal is to find a campaign across the site, or to be findable on Twtr. Character limit of 50 I think.  I'm imagining the hashtag is a permanent design and the text field allows users to enter copy. Can be either to the side of the media box or below it.

**Comment by acacheung** [comment]
@davidmooreppf so only links to media or can people upload?

**Comment by davidmooreppf** [comment]
I'd like it so that people can upload .jpg's or .png's, whatever is standard best-practice - but I don't know how time-intensive that is on your end. Do you have HTML handy for that? @walter can hook it up to our code, obvs.

**Comment by acacheung** [comment]
@walter put in a todo for you in questions/_content_setp.html.erb

**Comment by walter** [comment]
Cool. I'll have a look when I get a chance.

**Comment by davidmooreppf** [comment]
Currently on preview, adding media isn't supported :: 

http://preview.askthem.io/ny/questions/52b23e419d29c9216a000001?share=true

Walter, guess it's to you to hook-up when you get a chance. Needs a bit of product att'n, for what size images are permissible. 

It should display on preview screen -- 

-- and on Q page, as in link above, display below target but above Q content? E..g :: 

http://www.change.org/petitions/stop-digging-up-our-vegetable-gardens

**Comment by walter** [comment]
Closed duplicate #141. I'm going to cover the media and media link with this issue. The hashtag support doesn't have UX implemented yet and should really be split to its own issue.
