### ISSUE TITLE
on question listing pages, make "sign" button more visible? 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#184]
On pages: http://preview.askthem.io/pa/questions/

... would you advise we make "Sign" buttons more active? I'm concerned they don't compel a user to click as much as they could. 

... stronger color? 

... signature image element, perhaps? Or is that overkill. 

... the AskThem logo, even?

**Comment by acacheung** [comment]
@davidmooreppf what do you think? darkened the button a bit

![screen shot 2013-10-22 at 1 39 47 pm](https://f.cloud.github.com/assets/1054686/1383644/fc3e47ea-3b40-11e3-87b6-ffd2be996129.png)

**Comment by davidmooreppf** [comment]
Better!
