### ISSUE TITLE
re-size email header image to 652 wide

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#186]
Please replace image :: 

http://askthem.io/AskThem_email_header_Oct.jpg

... with one that's 652 px wide x 113, as in :: 

http://www.opencongress.org/images/email_header_default.jpg

... I could do it but faster on your machine, haha, my Illustrator is on my old MacBook. Then reassign back to me and I'll get Rob to deploy again.

**Comment by acacheung** [comment]
@davidmooreppf placed in app > assets > images > CiviCRM_email_assets as email-header-blue.jpg or email-header-orange.jpg

**Comment by davidmooreppf** [comment]
@rchekaluk believes we need to deploy code to oglocal, then he can take it.

**Comment by walter** [comment]
@rchekaluk sorry, didn't see this. It has been deployed some time ago. Please close once you have made the last step needed.

**Comment by rchekaluk** [comment]
AFAIK this has already been done; the nightly scrape of oglocal is configured to specifically grab email-header-blue.jpg and email-header-orange.jpg. Reopen if production http://askthem.io/ is not as expected.
