### ISSUE TITLE
fix /donate and /thank-you pages on Ppolitics.org WP site? 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#189]
Hi Amanda, realize you're not on our clock today, just a friendly ping to see if you can help apply more Wordpress styles for a major announcement we have coming today. 

On /donate, I accidentally nudged one of the donation fields into the center a bit :: 

http://www.participatorypolitics.org/donate/

... not terrible, but could be fixed. 
## 

On new page /thank-you, I don't know where to apply the styles :: 

http://www.participatorypolitics.org/thank-you/

**Comment by walter** [comment]
Think this has either been taken care of already or no longer relevant. Reopen if I'm wrong!
