### ISSUE TITLE
Copy for Orgs. on landing page

### ISSUE THREAD

**Issue by maryamgunja** [opengovernment/askthem-legacy#193]
For Organizations: 

The AskThem platform enables organizations to push elected officials across the country on their signature issues. It’s a great place for members to get their supporters asking key questions to local legislators. 

AskThem is a valuable outlet for organizations to broadcast their key advocacy work. AskThem promotes dialogue between coalition members who collaborate on popular questions and petitions. You can encourage others to sponsor, vote up, and share issue-based petitions as well as on questions directed at elected officials nationwide. At AskThem, we harness the power of social media to spread the word about your advocacy work with those who might not normally initiate contact with your organization.

In addition, AskThem displays official government data about their elected officials actions: votes, bills, issue group ratings, city council agendas & minutes, and more.

Sign up now to be among the first organizations to ask a question when we launch, see site previews, and promote your question towards a public response.
## 

Organization Profile

Name of Organization:

Website Address:

Phone:

Description of organization: 
(Please keep your description to one short paragraph.)

Full Name of Primary Contact: 

Title:

Email:

Privacy Request:
(Of the contact information provided above, is there anything you would prefer us not make public?)

Additional Contacts:

Email(s):

**Comment by walter** [comment]
@davidmooreppf what's the status on this?

**Comment by davidmooreppf** [comment]
OK so goal is to make /organization a link off splash page, just as /electeds is now. 

Finally added simple HTML, below, to bottom of views/pages/splash. Walter, assigning back to you for that, I'm not sure how to make the request.path = ='/organization'%> link actually deliver the correct page, I think maybe you have to add a route or something. Maybe not? 

In any case, Maryam, the longer copy above will have to go in a blog post, it's not worth putting it all in another version of views/layouts/splash. OK hope this works. 

<li class="<%= request.path == '/organization' ? 'active' : '' %>"data-type="organization">
        <a href="#" id="organization-signup">Organization or Media</a>
        <i class="icon-angle-down"></i>
      </li>

... then at bottom :: 

  <p id="dynamic-text">
    <%- if request.path == '/organization' %>
     The AskThem platform enables organizations to push elected officials across the country on their signature issues.<br><br>It’s a great place for membership groups and media partners to ask and deliver key questions to local & national elected officials.
    <%- else %>
      Over 8 million people have taken action on the White House's "We The People" petition platform. Now it's not just for Presidents anymore. We're bringing it nationwide, free and open for everyone.<br><br>Ask questions to over 100,000 elected officials. Petition your local government. Also, question and petition any verified Twitter account.
    <%- end %>
  </p>
