### ISSUE TITLE
only show federal & state electeds in nav

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#197]
Nav options for https://wtem.fwd.wf/ny-brooklyn :: 

https://www.dropbox.com/s/7bcb6sixbvheh9w/Screenshot%202013-12-02%2016.00.34.png

... only show fed & state levels now. 

Comment out county & city.

**Comment by walter** [comment]
I've attacked this from a couple different angles:
- only show city navigation if it is one of our seed cities or New York
- don't import county data from google civic info api at all

This allows us to have some some cities in navigation while we sort out the navigation UI for the long term.
