### ISSUE TITLE
add Google Analytics to AskThem production site

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#201]
No rush on this this week. 

I'm davidrussellmoore w/ G-analytics. cc @rchekaluk

**Comment by walter** [comment]
We already have the following:

https://github.com/opengovernment/askthem/blob/master/app/views/layouts/application.html.erb#L145-L154

Perhaps only access needs to your account on the Google Analytics side?

**Comment by walter** [comment]
Ping @davidmooreppf. See my last comment.

**Comment by davidmooreppf** [comment]
This is appearing in my Google Analytics account now, I'm seeing pages on Preview, so all good.
