### ISSUE TITLE
Add styling and branding to error pages & maintenance page

### ISSUE THREAD

**Issue by walter** [opengovernment/askthem-legacy#202]
Basically all the html files under public:

https://github.com/opengovernment/askthem/tree/master/public

As well as https://github.com/opengovernment/askthem/blob/master/app/views/layouts/maintenance.html.erb.

As mentioned in #195, these should probably not rely on assets stored locally in the application, but in S3. Coordinate w/ @rchekaluk.

**Comment by acacheung** [comment]
![screen shot 2013-12-19 at 4 51 24 pm](https://f.cloud.github.com/assets/1054686/1786582/bb633e30-68f7-11e3-995d-ed1927d4a654.png)

super simple
