### ISSUE TITLE
from homepage location box, refine copy for acceptable input options

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#209]
From homepage box, zip code and (city, state) are accepted entries that refer to pages of Q's, but state name ("California") or abbreviation (CA) causes error. 

So current copy "City, State or Zip" is confusing, b/c seems to allow State. Change to :: 

Enter a city and state, or a ZIP code

... unless we can have CA direct users to :: 

http://preview.askthem.io/ca/questions/

... which would be ideal, but maybe isn't MVP. Walter, your call. 

If state isn't supported, a better error page would be good before launch other than the Rails error page. You can reassign back to me if that's the realistic approach now - and I can finish some 'error' page that links to FAQ / support. 

cc @acacheung @maryamgunja

**Comment by walter** [comment]
Changing text to be more intuitive and created a new issue for better error handling for bad address input.
