### ISSUE TITLE
on question pages, set off "are you (elected official) copy"

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#210]
On question pages ::

http://preview.askthem.io/pa-philadelphia/questions/529f4059d2a57dafb7000017

... currently copy, "Are you Bill Green?" is in body content of Q. 

Let's separate that out in the gray answer box as in design :: 

https://www.dropbox.com/s/qelbw52cv4zgm1c/answers_loggedin%20copy.jpg

... where if the question is answered, that's where answer copy goes; and if it's it's not answered, that's where "Are you Bill Green?" goes. Obvs. in latter case, the gray box for response copy is smaller. 

If this doesn't look good I'm not married to it. cc @walter. Amanda, I'm not certain you've coded up those designs for responses to Q's, so maybe we missed that step.

**Comment by davidmooreppf** [comment]
Gray box - no watermark - copy as :: 

Are you Bill Green? Sign up to answer this question. AskThem is free, open-source, and non-profit.

If this question reaches its signature threshold, we'll deliver it to Bill Green's official contact information for a public response.

**Comment by acacheung** [comment]
![screen shot 2013-12-19 at 11 39 09 am](https://f.cloud.github.com/assets/1054686/1784018/211e8314-68cc-11e3-8e2a-0327215023c5.png)

**Comment by davidmooreppf** [comment]
Looks good! @walter any comments? I know it's a bit text-heavy, but it can be a placeholder for other value-proposition tests.

**Comment by walter** [comment]
I like it, too. Yeah, it think we can see later if it can be optimized. Good work.
