### ISSUE TITLE
add Google Plus button to sharing modal after signing

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#211]
After signing a Q, user sees modal ::

https://www.dropbox.com/s/nie192rpe9q8jqa/Screenshot%202013-12-17%2019.17.04.png

... we need to add G+ button for social sharing there. Have it handy? 

https://developers.google.com/+/web/badge/

**Comment by acacheung** [comment]
I think the modal only pops up after you write a question, but all the styles are in there is you want to wire it up to pop up after signing on to a question as well. Copy would have to change as well.

**Comment by acacheung** [comment]
![screen shot 2013-12-18 at 2 05 56 pm](https://f.cloud.github.com/assets/1054686/1776470/814a7a96-6817-11e3-9de0-3f9485d00ffc.png)
