### ISSUE TITLE
re-arrange buttons in sharing modal after Q is signed 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#212]
In sharing modal ::

http://preview.askthem.io/pa-philadelphia/questions/529f4059d2a57dafb7000017?share=true

... list in descending order: Facebook, Twitter, Google Plus, Email. Stacking them vertically is fine for now. I can help locate a button icon if that's helpful.

**Comment by acacheung** [comment]
![screen shot 2013-12-18 at 2 05 56 pm](https://f.cloud.github.com/assets/1054686/1776469/77710544-6817-11e3-8530-daa7084c50be.png)
