### ISSUE TITLE
add AskThem logotype as default image on FB sharing

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#213]
Right now from a completed Q page, clicking the FB button in the sharing modal goes to :: 

https://www.dropbox.com/s/4r8d75982xaqvns/Screenshot%202013-12-17%2020.26.28.png

... picking up the Open North logo, actually - we should add the AskThem logotype as the default image, and enhance w/ different images in the future ones based on factors such as category & target & user.

Know where FB picks this image up in the code? I can help research, or maybe @walter knows. Maybe you told me this already by pointing me to where the sharing copy is for FB, I'd have to go back & look, just wanted to have this in the queue for tmw.

**Comment by walter** [comment]
See commits for #270. All good now.
