### ISSUE TITLE
on question creation form, reformat height of elected official boxes

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#215]
Since Oct., @walter integrated with new data sources, so on first page of Q creation form :: 

http://preview.askthem.io/pa/questions/new

... or entering 19106 on homepage, or 239 Arch St., Philadelphia PA 19106 as an example ... 

... more targets are appearing, and they appear too crowded in their boxes :: 

https://www.dropbox.com/s/44wfohfmmlalbtv/Screenshot%202013-12-17%2020.42.19.png

https://www.dropbox.com/s/jgww0cmbenn4ab6/Screenshot%202013-12-17%2020.42.56.png

... I don't know if Walter knows the height requirements here programtically - there will be some long titles, for sure - I wish I could help more in researching a "max characters" or "max height" to accommodate - how to tackle? Open to input. Not sure what's most efficient.

**Comment by acacheung** [comment]
![screen shot 2013-12-18 at 4 13 57 pm](https://f.cloud.github.com/assets/1054686/1777691/64f1fb32-6829-11e3-8d36-781b4a1bbd88.png)

@davidmooreppf what do you think?

**Comment by davidmooreppf** [comment]
Works for me. Good job.
