### ISSUE TITLE
Make Disqus account for askthem

### ISSUE THREAD

**Issue by acacheung** [opengovernment/askthem-legacy#217]
Not sure if there is one already, but on the questions show page, the disqus_shortname is set to 'dobot'

**Comment by walter** [comment]
Disqus integration was before my time. So I'm not sure what is going on there. Probably best to have any new account set up be by @rchekaluk or @davidmooreppf and moved to an environmental variable.

**Comment by davidmooreppf** [comment]
Assigning to Rob in ops.
