### ISSUE TITLE
make "loading" more visible in Q creation form

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#219]
When a visitor enters her address, the word "loading" appears while her electeds are looked-up ::

https://www.dropbox.com/s/stxtxe922i4gptf/Screenshot%202013-12-18%2012.21.44.png

...goal is to make that more visible somehow, by animating it more or setting it off with a different color font or design. Or we could add a "find my reps" button, but having it fill-in after zip code entry is nice too. cc @walter

**Comment by davidmooreppf** [comment]
Forgot to assign Amanda.

**Comment by davidmooreppf** [comment]
This is important for today, please, Amanda. Right now, as elected officials are being looked-up, there's no indication that anything happens after a visitor enters her zip code.

**Comment by walter** [comment]
@acacheung from IRC:

> what would be good to get from acheung is a styling loading indicator that is more prominent... then i can adjust the logic to show it when it should (hopefully)
