### ISSUE TITLE
complete process for verified response

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#22]
Issue for 9(a) on dev roadmap. 

As we discussed, for launch - a logged-in verified user can visit a page of any Q to herself, whether it's reached threshold or not, and have ability to enter an answer. 

Ideal would be to allow verified responder to reply in the body of an email, but that may not be necessary if it's time-intensive. 

It is not necessary for verified users to be able to add answers on other pages of Q's that are not to them. They can simply add comments if they desire.

**Comment by walter** [comment]
> Ideal would be to allow verified responder to reply in the body of an email, but that may not be necessary if it's time-intensive.

Let's come back to this as a separate issue later. It requires some ops set up for accepting incoming emails, etc.

We'll do the web UI version first for this issue (as per #45 design, I believe) for now.

**Comment by walter** [comment]
Should close this when #72 is merged into master.

**Comment by walter** [comment]
#72 merged to master. This work is done.
