### ISSUE TITLE
include social sharing on question detail pages

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#220]
cc @walter On pages ::

http://preview.askthem.io/pa-philadelphia/questions/528d0074d2a57ddd63000005

... including sharing options under sign button. 

My recommendation is that "share this" link opens up the current modal.

**Comment by acacheung** [comment]
![screen shot 2013-12-18 at 5 12 44 pm](https://f.cloud.github.com/assets/1054686/1778247/8de23658-6831-11e3-9322-dc6aadc132a4.png)
