### ISSUE TITLE
email header image for ActionNetwork

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#223]
cc @maryamgunja 

Our email custom template is as pasted below, so looks like we need a 600x wide header image. (Footer image in next issue.) 

So somewhat like this :: 

http://askthem.io/AskThem_email_header_Oct.jpg

... (it's called AskThem_logo_email_header.png in my local files if that helps locate it) ...  

Two versions - both with the logo & logotype up top, as in .jpg above. One in all orange type & one in all blue type. 

The copy underneath should read:: 

Questions and petitions with public figures nationwide - http://askthem.io

... that correct from the below, 600 wide? Then Maryam can paste it into our CRM mailings. 

(Click 'edit' to see HTML below I guess). 

---

<table border="0" cellpadding="10" cellspacing="0" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;">
  <tr>
    <td valign="top" style="border-collapse: collapse; background-color: #FFFFFF; padding:10px 10px 40px;">
      <table border="0" cellpadding="10" cellspacing="0" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;">
        <tr>
          <td valign="top" style="border-collapse: collapse;" width="600">
            <div style="color: #505050;font-family: Arial;font-size: 14px;line-height: 150%;text-align: left;">

**Comment by davidmooreppf** [comment]
Confirmed, so in each orange type & blue type, 

-- we'd like one version of the above 600 px wide -- the logo, logotype & tagline "Questions and petitions with public figures nationwide - http://askthem.io." 

-- and also one version 300 wide,

--  and the Photoshop file in /assets please. So we can tweak the tagline if need be in the future.

**Comment by acacheung** [comment]
In /assets/images/email_assets/ActionNetwork

**Comment by acacheung** [comment]
![email_headers-01](https://f.cloud.github.com/assets/1054686/1880356/1ee7eb08-7957-11e3-8e07-cff647ad256e.jpg)
![email_headers-02](https://f.cloud.github.com/assets/1054686/1880357/1eed3f54-7957-11e3-87e1-d423fb23c803.jpg)
