### ISSUE TITLE
email footer image for ActionNetwork

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#224]
cc @maryamgunja 

Building off previous issue for email header, need an image for email footer in our ActionNetwork CRM, also 600px wide. 

Footer should be an image including our social sharing icons, maybe in a little row, with copy as :: 

Connect with AskThem 

a) Facebook :: https://www.facebook.com/pages/Askthem/538576652878135?ref=hl

b) Twitter :: https://twitter.com/askthemPPF

c) Google Plus :: https://plus.google.com/b/109173535723087289312/109173535723087289312/about?hl=en

d) Email: Maryam Gunja, Community Manager - maryam@askthem.io

e) On the web: http://askthem.io - http://participatorypolitics.org

... below that including copy :: 

This email is from the Participatory Politics Foundation, a 501(c)3 non-profit organization.

Unsubscribe here: http://crm.aws.ppolitics.org/civicrm/mailing/optout?reset=1&jid=307&qid=610621&h=5dbef189f90b1fb3

148 Lafayette St., 12th Floor
New York, NY 10013
United States

... footer can include the logo & logotype again. I can do a sketch, but whatever seems basic is fine.

**Comment by acacheung** [comment]
![email_footer_high-res](https://f.cloud.github.com/assets/1054686/1881485/e605d952-7966-11e3-84c6-7655389425cc.jpg)
