### ISSUE TITLE
on question detail pages, make target avatar & name & title bigger

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#225]
On pages :: 

http://preview.askthem.io/ny/questions/52b23e419d29c9216a000001?share=true#

... the Q target is impt. for the site. 

Avatar, name & title should all be bigger - or just avatar & name, if not title.

Realize that's a cost/benefit calculation, but think we should.

**Comment by acacheung** [comment]
![screen shot 2013-12-19 at 3 44 51 pm](https://f.cloud.github.com/assets/1054686/1786074/7faa45fe-68ee-11e3-9190-b2a90c39c6d2.png)

@davidmooreppf thoughts?

**Comment by davidmooreppf** [comment]
Looks good to me !
