### ISSUE TITLE
make site header less tall

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#227]
Let's reduce vertical padding in header, if we can. Seems tall. 

I'll simplify the copy up there in a related issue. 

Compare heights :: 

http://preview.askthem.io/ny/questions/52b23e419d29c9216a000001?share=true#

http://www.change.org/petitions/stop-digging-up-our-vegetable-gardens

... agree?

**Comment by acacheung** [comment]
shortened it by 30px

**Comment by acacheung** [comment]
![screen shot 2013-12-19 at 5 37 10 pm](https://f.cloud.github.com/assets/1054686/1787018/7d3eadf4-68fe-11e3-84a4-487ea5f760b9.png)

didn't want to shorten it by too much because I didn't want it to look to compact
