### ISSUE TITLE
copy change for header - change "See questions & petitions near you" to "Search"

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#228]
Related to #227, let's change "See questions & petitions near you" in header to just "Search". Less copy, less crowded. Not married to this, as it's helpful, just crowded. 

Sorry, couldn't find header in app/views. If it's not helpful, we can stick with current.

**Comment by acacheung** [comment]
@davidmooreppf it's in app/views/layouts/application.html.erb

**Comment by walter** [comment]
"Search" is NOT a good change. It gives a false impression of what the functionality is. So I'm happy to see this closed.

I would simply drop "petitions" from the copy as it confuses things.

**Comment by davidmooreppf** [comment]
I'm gonna try: "Questions near you:" in my next deploy. Simper, anyway.
