### ISSUE TITLE
email alerts of answered questions

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#23]
Issue for 9(b) on dev roadmap. 

Whenever a Q receives a response, goal is to deliver email alerts to ::
- Question-creating user
- All signatories of that Q. 

---

We could differentiate b/w questions that reached threshold and were answered, as well as questions that are near threshold and may be answered by a verified responder, but that may not be possible for launch. Would be sweet though. 

---

... DRM can write copy for subject heading & body.

**Comment by davidmooreppf** [comment]
Just assigning to Walter. Of course this could be enhanced to getting site-wide alerts of answered questions, by any elected official in your state or any public figure, but that's a separate story.

**Comment by walter** [comment]
Seems a good piece of work for @evz or @derekeder reassigning. If y'all don't have the bandwidth, reassign back to me.

**Comment by davidmooreppf** [comment]
@loganfaerber is checking, thx dude. I recall seeing images of this, but not sure if it's in PSD or in HTML or what.

**Comment by walter** [comment]
@davidmooreppf not sure your comment is on the right issue... if it is, can you give context on image needed, please?

**Comment by davidmooreppf** [comment]
Moved to opengovernment/product#69
