### ISSUE TITLE
sharing modal enhancements

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#241]
Disregard the copy on this image example, but please follow the basic design, if that's all right :: 

![pastedgraphic-2](https://f.cloud.github.com/assets/116819/1845499/48a536ac-758e-11e3-9b48-7dc14fafb316.png)

---

Top copy :: 

We need (number) more signatures to deliver this question! 

(then progress bar, with no. of signatures above the bar to the left, and number needed below the bar to the right.) 

Below copy :: 

When this question reaches the threshold, we'll deliver it to (target name). 

---

If you need code for (target name), @walter can help when he's online. 

Was this going to become a page, a la Change, instead of a modal? I think it was, but we may have closed the issue for that last week?

**Comment by acacheung** [comment]
![screen shot 2014-01-08 at 11 35 46 am](https://f.cloud.github.com/assets/1054686/1870117/299bb978-7883-11e3-8b1e-61e11988e093.png)

@davidmooreppf ^

**Comment by davidmooreppf** [comment]
Let's make it more personal to our site by adding the question mark logo at bottom? As on preview now.

**Comment by acacheung** [comment]
![screen shot 2014-01-08 at 1 50 05 pm](https://f.cloud.github.com/assets/1054686/1871375/d30982f8-7895-11e3-8571-6ee1369b95cb.png)
