### ISSUE TITLE
design enhancements to state landing pages

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#242]
On :: http://preview.askthem.io/wi

Make chamber highlighting more prominent - right now it's just the orange underline, but I'm hearing that's not clear enough. Could we use the upside-down arrow? 

https://www.dropbox.com/s/ye2j1kmkrfwifl4/Screenshot%202014-01-07%2017.07.17.png

---

Include one sample electeds' photos in the diff. chamber boxes - viz. where it says "8 representatives" in /wi above --  to indicate there's a reason to click over there on that box? Maybe that's more clutter, but maybe worth a try. 

Can explain more voice tmw if helpful.

**Comment by acacheung** [comment]
![screen shot 2014-01-09 at 3 00 22 pm](https://f.cloud.github.com/assets/1054686/1881604/b6d8921c-7968-11e3-8296-1852cbc4f51d.png)
