### ISSUE TITLE
after selecting a target, avatar displays a bit low

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#244]
Is this the correct level for the photo of the target? Seems low, yes? 

https://www.dropbox.com/s/nj2d9os32rcl0bg/Screenshot%202014-01-07%2018.56.50.png

**Comment by acacheung** [comment]
![screen shot 2014-01-08 at 1 07 04 pm](https://f.cloud.github.com/assets/1054686/1870962/d997b8e8-788f-11e3-9ae2-2aef6091f843.png)
