### ISSUE TITLE
copy for sidebar around sharing 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#246]
On individual Q pages :: 

http://preview.askthem.io/ri/questions/52b231f39d29c9439c000002
50 signatures 

(threshold bar) 

150 more needed to deliver this question 

.... I'll tweak this in questions/show once the styling is in there.

**Comment by davidmooreppf** [comment]
Almost - now on ::

http://preview.askthem.io/ri/questions/52b231f39d29c9439c000002

above: 5 signatures

195 needed to deliver this question

**Comment by acacheung** [comment]
![screen shot 2014-01-08 at 5 33 07 pm](https://f.cloud.github.com/assets/1054686/1873135/e0cb8cc8-78b4-11e3-83b3-dea25bcfcf59.png)

**Comment by acacheung** [comment]
@davidmooreppf what do you think?

**Comment by davidmooreppf** [comment]
Hmm. I like the overall pitch "to deliver this question" but still looks awkward on two lines. 

Let's try just "92 needed to deliver", and right justified, please.

**Comment by acacheung** [comment]
![screen shot 2014-01-09 at 11 44 35 am](https://f.cloud.github.com/assets/1054686/1879667/5b52c496-794d-11e3-81f3-9055e14e43d3.png)

@davidmooreppf ^

**Comment by davidmooreppf** [comment]
Works for me! We can tweak from here to please the eye. Thx.
