### ISSUE TITLE
new array of six elected officials for marketing materials

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#25]
Can you grab these from the app? If not, I can get them, but I'd have to first look up street addresses in each state, and then query their pages on staging. 

WA US Rep Jaime Herrera Beutler (R)
MD US Rep John Delaney (D)

NH State Sen Bob Odell (R)
AR State Sen Stephanie Flowers (D)

San Jose Councilwoman Madison Nguyen (non-partisan elections)
US Senator Deb Fischer (R)

**Comment by walter** [comment]
> WA US Rep Jaime Herrera Beutler (R)
> http://oglocal.herokuapp.com/wa/people/H001056
> 
> MD US Rep John Delaney (D)
> http://oglocal.herokuapp.com/md/people/D000620
> 
> NH State Sen Bob Odell (R)
> http://oglocal.herokuapp.com/nh/people/NHL000019
> 
> AR State Sen Stephanie Flowers (D)
> http://oglocal.herokuapp.com/ar/people/ARL000040
> 
> San Jose Councilwoman Madison Nguyen (non-partisan elections)
> http://oglocal.herokuapp.com/ca-san-jose/people/CA-SAN-JOSEL000008
> 
> US Senator Deb Fischer (R)
> http://oglocal.herokuapp.com/ne/people/F000463

I'll look into why Deb Fischer's avatar isn't coming up.

**Comment by davidmooreppf** [comment]
Yeah, on this I was just looking to get their headshots & titles for Steve to incorporate into new image in Photoshop. We have some possible replacements if we hit snags. They don't have to actually live on a webpage together.

**Comment by walter** [comment]
Weird. It looks like OpenCongress does not have an image for Deb Fischer in what they scrape:

http://sunlightlabs.github.io/congress/index.html#bulk-data/legislator-photos

I could cook up something to find the image or would it be better to use someone else that has an avatar?

**Comment by walter** [comment]
Ok, yeah I would recommend just choosing someone else besides Deb Fischer than.

**Comment by davidmooreppf** [comment]
U.S. Senator Lisa Murkowski of Alaska - she show up, @walter?

**Comment by walter** [comment]
http://oglocal.herokuapp.com/ak/people/M001153

Think that does it.

**Comment by davidmooreppf** [comment]
Haha this should stay open until Steven confirms he has access to them. 

Steven, my dude Josh is working on the copy he'd like in a G-doc, I'll lay it out for you in issues. Going to work on revised versions of three slides: the six-person array, an answered question, and a user profile (with the questions he or she's signed). Will detail in G-doc.
