### ISSUE TITLE
on question pages, behavior for new visitor just clicking "sign" 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#250]
On pages, e.g. :: 

http://preview.askthem.io/pa-philadelphia/questions/529f3a8fd2a57dafb7000001

... define non-logged in visitor clicking "sign".

**Comment by walter** [comment]
Really not sure what you mean. Can you spell it out @davidmooreppf, please?

**Comment by davidmooreppf** [comment]
Ahh yeah this was still self-directed. Just thought a visitor might arrive on the page and not fill in the form, but just click "sign" to see what happened, and we can pop-up a special modal in this edge case. Not pressing.

**Comment by walter** [comment]
@davidmooreppf close if no longer relevant.
