### ISSUE TITLE
more data-partner logo images in footer

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#251]
In footer ::

One row of two logos, PPF's and Knight Foundation as current. 

Let's remove Open North logo now. 

Second row of two logos, under title, Data Partners, for Google & Democracy Map ::

http://deployment.googleapps.com/Home/user-resources/google-icons-and-logos

http://api.democracymap.org/demo

... for Democracy Map we don't have a logo file, so just grab a screengrab pls. 

---

Last, this isn't for footer at the moment , just for some other pages, but let's put this in assets as well, the Sunlight Fdn. logo :: 

http://sunlightfoundation.com/press/logos/

... I'll apply that where necessary.

**Comment by acacheung** [comment]
![screen shot 2014-01-09 at 5 42 28 pm](https://f.cloud.github.com/assets/1054686/1883036/5dad2f42-797f-11e3-97a2-ca3f5fac2212.png)
