### ISSUE TITLE
image badges for social media sharing

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#252]
cc @maryamgunja 

We'll send these to users via CRM if they asked a Q, as a follow-up to sharing the link to the Q page itself :: 

I asked a question on AskThem! Support my question and help me get a public response.

My question was answered on AskThem! See the public response and comment on it. 

My question needs answering on AskThem! It reached the signature threshold and was delivered to its target, so now we need to ask the person to respond publicly. 

... if we have time.

**Comment by acacheung** [comment]
![badge](https://f.cloud.github.com/assets/1054686/1883155/cea2c214-7981-11e3-8085-8e5f9ecb7a76.jpg)

**Comment by davidmooreppf** [comment]
Works for us for now! Thx.
