### ISSUE TITLE
user profiles, "state" option not saving, stuck on Alaska

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#257]
From user profile pages, regular level ::

http://preview.askthem.io/users/52b36ca89d29c9ef27000007

... clicking settings, then selecting "NY" in state drop-down, and clicking "update" button at bottom, doesn't save NY :: 

https://www.dropbox.com/s/tsjxe1f4m0b5zpb/Screenshot%202014-01-15%2017.28.39.png

... reverts back to AK. Maybe a known issue.

**Comment by walter** [comment]
It's actually saving, but the options drop down in editing of the profile doesn't reflect it properly.

In other words it's always defaulting to Alaska, even if the state for the person is known to the database to be something different.

If you look at [your profile](http://preview.askthem.io/users/52b36ca89d29c9ef27000007), you can see that it says "New York, NY" under your name.
