### ISSUE TITLE
When creating a question in Firefox,  very long load time for recipients & can't get past the "select a recipient" stage

### ISSUE THREAD

**Issue by maryamgunja** [opengovernment/askthem-legacy#260]
@davidmooreppf

**Comment by walter** [comment]
@maryamgunja, could you give the address that were using please?

The second part of the problem is actually covered by #54.

**Comment by maryamgunja** [comment]
re: 1st part of problem, I was experiencing long load time intermittently, but now It's loading on time again. I'll make sure to provide address if I run into this problem again

**Comment by walter** [comment]
Ok, I'm going to go ahead and close this. You can open a new issue if long load times recur after we have done some more thorough stress testing of the production server and we have done the work on #237.
