### ISSUE TITLE
Delete 10 dummy Q's on backend

### ISSUE THREAD

**Issue by maryamgunja** [opengovernment/askthem-legacy#261]
@davidmooreppf 

http://preview.askthem.io/tx/people/C001098

http://preview.askthem.io/pa-philadelphia/questions/528d0074d2a57ddd63000005

http://preview.askthem.io/ri/questions/52b231f39d29c9439c000002

http://preview.askthem.io/ny/questions/52b353b99d29c9f0c7000004

http://preview.askthem.io/ny/questions/52b36de39d29c9ef27000009

http://preview.askthem.io/ny/questions/52b0f9a79d29c9058a000008

http://preview.askthem.io/ny/questions/52b23e419d29c9216a000001

http://preview.askthem.io/ny/questions/52b1ff749d29c9192600000a

http://preview.askthem.io/ny/questions/52c892cc9d29c9d1e0000005

http://preview.askthem.io/ny/questions/52a25f54d2a57dd9b2000006

**Comment by walter** [comment]
Done, plus also cleared out http://preview.askthem.io/pa-philadelphia/questions/528d210ed2a57ddd6300000c as it was clearly test data.
