### ISSUE TITLE
zip code field reads as "can't be blank" in Chrome, can't proceed with submission

### ISSUE THREAD

**Issue by maryamgunja** [opengovernment/askthem-legacy#263]
@davidmooreppf 
![screen shot 2014-01-20 at 10 55 35 am](https://f.cloud.github.com/assets/5739030/1955666/bb79dbc4-81eb-11e3-907f-8e2a72ca873e.png)

**Comment by walter** [comment]
@maryamgunja is this always doing this in Chrome for you or just intermittently? Do other zip codes work?

**Comment by walter** [comment]
I just tried this address and found that behind the scenes the Google Civic API is returning this error:

```
GoogleCivicInfo::NoStreetSegmentFoundException (GoogleCivicInfo::NoStreetSegmentFoundException):
```

This is likely what's causing this error. Basically @237 should put an end to this error. So closing this issue as a duplicate.

Thanks for reporting it though. We actually may want to report the specific address to Google Civic API team as being problematic.

**Comment by maryamgunja** [comment]
It happens intermittently, sorry for not making that clear...
