### ISSUE TITLE
add small "help" link to bottom of /questions/new

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#268]
Some visitors might arrive on http://preview.askthem.io/ny/questions/new and then have questions about what to do. 

We're not giving many tips next to the fields, so how about a small link under (1 of 3) at bottom of form that reads simply: Help

...  and links to: https://askthem.desk.com/ for @maryamgunja & user support. Would go on each page of the form, I think.

**Comment by walter** [comment]
This seems like something that we should wait to see is a problem first and A/B test it.

I.e.
- get metrics of people that are starting on new question page and not completing the form
- add version with help link
- see if it improves our form completion ratio (and/or whether people are actually clicking on the help link)

From my experience "help" pages are very rarely actually used. I'm happy to be proven wrong with A/B testing.

**Comment by walter** [comment]
Closing. Create an issue later if we notice users not converting on questions/new.
