### ISSUE TITLE
only display "interest groups" tab on /people pages for state legislators, or hide for now

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#269]
Currently, every elected official page in the app displays "interest groups" ::

http://preview.askthem.io/ny/people/S000148

... but we only have data for that in the app for state legislators :: 

http://preview.askthem.io/ny/people/NYL000074

... easier to hide it for everyone for now, or only display it for state legislators? If we need to hide it now, that's all right, we can bring it back.

**Comment by walter** [comment]
Part of what is outlined in opengovernment/product/issues/29.
