### ISSUE TITLE
add Google plus sharing code to modal

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#270]
http://preview.askthem.io/pa-philadelphia/questions/529f3a8fd2a57dafb7000001?share=true

**Comment by walter** [comment]
Added the code implementing this in the following commits:

https://github.com/opengovernment/askthem/commit/0313af8f68b829c244a6030475cc83eb6a29dc7a

https://github.com/opengovernment/askthem/commit/0313af8f68b829c244a6030475cc83eb6a29dc7a

https://github.com/opengovernment/askthem/commit/0313af8f68b829c244a6030475cc83eb6a29dc7a

There is some more polish needed for Google+ and Facebook's preview of the site. Mostly this has to do with what are in meta tags describing each page.

**Comment by walter** [comment]
Just tested on the live site. The only remaining issue is the image that comes up for the question is the PPF logo rather than AskThem.io's.
