### ISSUE TITLE
process for confirmation emails stuck in spam

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#272]
This can be post-launch, but noting: 

Just thinking, a good number of new users may sign a question and the confirmation email will go to spam folder, unconfirmed.  

Best is for the app to try to re-send before deleting the account after a set time.

**Comment by walter** [comment]
Yeah, I was thinking a reminder email 8 hours before expiring the account.

**Comment by walter** [comment]
No longer relevant.
