### ISSUE TITLE
change sender name & subject heading for confirmation emails

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#273]
Currently, when a new user signs a Q, the confirmation email is name support@askthem.io and subject heading "Reset your AskThem.io password". 

Preference is for sender name ::

AskThem.io - Support 

... w/ subject heading ::

Confirm your new AskThem account

---

Would be ideal to keep subject heading Reset your AskThem.io password" for those cases when a user initiates from users/password/new.

**Comment by walter** [comment]
> Confirm your new AskThem account

When a use signs up in the process of adding their signature to a question, they get 2 emails:
- "Confirm your AskThem.io email address" -- to get them to confirm their account, by answering the email's prompt to click a link
- "Reset your AskThem.io password" -- what is suggested to change to "Confirm your new Askthem account"

So a bit of a name collision if we change "Reset…" to "Confirm…".

I think a better subject would be "Set a password for your AskThem.io account".

Barring any objections, running with that.

**Comment by walter** [comment]
@davidmooreppf thinking about it, "Set a password for your AsThem.io account" works for both when we are asking people to set their password for their first time OR if they hit "forgot password".

Good enough?

In other news I have implemented a delay for setting the "Set password" email and the user has to have confirmed their account first. The idea being that we don't want to send two emails immediately after signing in support of the question.

**Comment by walter** [comment]
Actually using "Set your AskThem.io password" as I think it is explanatory and concise.
