### ISSUE TITLE
add terms of service & privacy policy checkbox to users/sign_up

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#277]
On bottom of :: 

http://preview.askthem.io/users/sign_up

... below "sign up" button but above "sign in" links, 

please add checkbox w/ copy: 

By joining, or logging in via Facebook, you accept AskThem's terms of service and privacy policy.

... as on sidebar, checkbox is default checked, and must be checked to proceed w/ sign-in button.

**Comment by walter** [comment]
Did this along (sans Facebook wording, because you still have to do sign up step for address, etc.) with #276. See commits there.
