### ISSUE TITLE
create static pages for terms of service & privacy policy

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#278]
Under /pages, or /about, we need to add same kind of basic pages for :: 

/terms-of-service

/privacy-policy

... I have the copy. HTML for each can look just like the existing simple template ::  

<section class="static">
  <h1>About AskThem</h1>
  <div class="related_data">
    <p>AskThem is a free, open-source, non-profit and non-partisan platform for questions and petitions with public figures. AskThem is a project of the Participatory Politics Foundation, a 501(c)3 non-profit organization with a mission to increase civic engagement. Previously, PPF created OpenCongress.org, the most-visited non-profit website in the world for tracking the U.S. Congress.</p>
 </div>
</section>

... if I can just add these by adding new files, reassign back to me, I think there was an issue with me doing that.

**Comment by davidmooreppf** [comment]
Moving this up in priority please. I recall I can't just copy the HTML and add them using GitHub, correct? If I can, I can do this, of course.

**Comment by walter** [comment]
New files that you can edit are at the following:
- app/views/pages/terms_of_service.html.erb
- app/views/pages/privacy_policy.html.erb

The answer to web requests at /terms-of-service and /privacy-policy respectively.

**Comment by walter** [comment]
@davidmooreppf commit:

https://github.com/opengovernment/askthem/commit/1aa69c0d498e19cbd1225b70e7e4ef1eb3f9f364

**Comment by walter** [comment]
Closing these. They are in place on production. Anything in the future should be handled by issues for specific revisions.
