### ISSUE TITLE
All avatar photos broken when supplied by ballotpedia.org

### ISSUE THREAD

**Issue by walter** [opengovernment/askthem-legacy#28]
As discovered in #13, ballotpedia has changed their URLs for images of elected officials without putting a redirect in place.

Thus all of our Person#image results that rely on ballotpedia are wrong.

We have URLs recorded that look like this:

http://ballotpedia.org/wiki/index.php/Images/ElectedOfficialName.jpg

but ballotpedia.org has changed the URLs to look like this:

http://ballotpedia.org/wiki/images/c/c3/ElectedOfficialName.jpg

Good on them for getting rid of that terrible index.php. Too bad they didn't go the extra distance and put a redirect in place.

The correct way to solve this is to contact ballotpedia.org and ask them to put redirects in place.

Problems with other solutions:
- correcting the URL in our database - we get our image URL data from other sources and if we simply rewrite it our database, once we sync our data it could go bad again
- writing custom Person#image method that overrides db's URL with correct one - a brittle hack, nice to avoid if we can

Both of the above are still options and can have their issues addressed, but if we can get ballotpedia.org to do the right thing, that would be best.

**Comment by derekeder** [comment]
Cool - I can reach out to ballotpedia.org. Do we have a contact there?

**Comment by walter** [comment]
@davidmooreppf or @jpmckinney might, I don't.

**Comment by jpmckinney** [comment]
I've never looked at ballotpedia.

**Comment by davidmooreppf** [comment]
Sorry just seeing this - try geoff.pallay@ballotpedia.org, I emailed w/ him back in June '11 when we were developing OG. 

Feel free to 'cc' me. At the time he was in his email sig :: 

Geoff Pallay
Project Director, State Legislatures
Ballotpedia
www.ballotpedia.org
www.lburnsinstitute.org

**Comment by derekeder** [comment]
Email sent. Awaiting response ...

**Comment by walter** [comment]
After getting your email with their response, I took it upon myself to see what whether they could use mod-rewrite to handle the pattern (rather than a redirect per se).

First thing to determine is whether they serve their site with Apache:

http://toolbar.netcraft.com/site_report?url=http://ballotpedia.org

Looks like they do.

So what they need to do is put this in their vhost config in their Apache config:

```
RedirectMatch 301 /wiki/index.php/Images/(.*)\.jpg$ http://ballotpedia.org/wiki/images/c/c3/$1.jpg
```

However, looking at the pattern of the second part again, I see "c/c3" in the path. Does that part of the path change on depending on the elected official? That may screw up the redirect match OR our own handling if it comes to that.

**Comment by walter** [comment]
Ugh. According to this guy:

http://ballotpedia.org/wiki/images/2/23/Max_Maxfield.jpg

what comes after "/wiki/images/" in the path may vary which we have no of knowing from the original URL.

So we can't do URL hacking on our end or get them to do a simple RedirectMatch on their end.

Seems we have to actually get the data correctly updated in OpenStates (since we periodically rebuild our data from OpenStates).

**Comment by walter** [comment]
It's worth experimenting with whether we can get the photos locally through OpenStates. See notes here:

https://www.pivotaltracker.com/story/show/50147951

**Comment by derekeder** [comment]
Temporary patch: add a bit of custom logic to show placeholder image when the image path contains ballotpedia.org

**Comment by walter** [comment]
Worked around in other ways.
