### ISSUE TITLE
tweaks to Twitter recipient lookup & selection on /questions/new

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#281]
Searching by Twitter name isn't quite user-friendly, due to issues outside us, didn't realize the API would be so slow. 

We can address it in copy by adding "(may take a long time, up to 30 seconds)" or whatever.

On the slight UI tweaks ;:

a) is it easy to replace "loading" with a bigger spinner? I think that would help. If we don' t have a spinner handy, loading will be OK.

b) Once it finds a matching verified Twtr name, can it advance automatically to content step ?

c) If not (b), then is it easy to add the green "check" selection when a visitor clicks the name, as when visitor selects an elected? Realize this seems small but would help a lot I think. 

@maryamgunja

**Comment by walter** [comment]
> a) is it easy to replace "loading" with a bigger spinner? I think that would help. If we don' t have a spinner handy, loading will be OK.

Please choose a spinner in the size and style you would like and I can put it in place.

**Comment by walter** [comment]
> b) Once it finds a matching verified Twtr name, can it advance automatically to content step ?

As far as the logic of how I built it, it should be advancing right away. For some reason there is a significant delay...

> c) If not (b), then is it easy to add the green "check" selection when a visitor clicks the name, as when visitor selects an elected? Realize this seems small but would help a lot I think.

I'll see what I can do.

**Comment by davidmooreppf** [comment]
Flexible with anything, this seems to work - flexible on placement as well ::

http://fgnass.github.io/spin.js/#?lines=13&length=14&width=4&radius=30&corners=1.0&rotate=0&trail=60&speed=1.2&direction=1

**Comment by walter** [comment]
Hmm. This seems like a lot a complexity to add a simple spinner. Holding off on this aspect.
