### ISSUE TITLE
@ symbol for Twitter recipient lookup on /questions/new

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#283]
I should have gotten this in to Amanda, just kept forgetting about it. 

Seems that questions/new works whether a user includes the @ symbol, e.g. @chrislhayes or chrislhayes - but if lookup is faster with the latter, for any reason, we should display a big @ sign to the left of the form. I'll have to find an image for such.

**Comment by walter** [comment]
It has no effect on relative speed of lookup.

**Comment by walter** [comment]
Closing. If we see users not "converting" on questions/new for asking questions of Twitter people, maybe A/B test this.

Until, seems like anticipating a problem that may not exist.

**Comment by davidmooreppf** [comment]
Seeing if Amanda can get this in under the wire .... 

under "their twitter name" on q creation form, first step :: 

http://www.askthem.io/ma/questions/new
