### ISSUE TITLE
on pages for verified Twitter accounts, design tweak to "(Not In Office)"

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#284]
Little HTML here - On pages such as :: http://preview.askthem.io/people/52e6cd6e46efa7b354000001

Sometimes the copy "Not In Office" may be confusing, as with gov't entities like FCC, so changing it to "Verified Twitter account". 

... in questions/show, line 20, can we use, say,  <div class="attr"> to display those words below the name, but above or next to the "3 questions 4 answers" line? In the smaller gray type, that is.

**Comment by walter** [comment]
What if they don't have an office, we only showed their name?

**Comment by davidmooreppf** [comment]
Works for me- it could confuse the 'AskThem verified' too. That would be great.
