### ISSUE TITLE
from twitter recipient selection in /questions/new, make "next" button active

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#285]
Currently, when Twitter finds a match, the only way to advance the screen is to check the person's face & name. 

That's great, but some visitors have been clicking "next" to advance, which currently results in "recipient cannot be blank" error. 

https://www.dropbox.com/s/mvo2bai8n4xmi73/Screenshot%202014-01-28%2015.02.28.png

Can we make the "next" button active on the questions/new form in such cases?

**Comment by walter** [comment]
I understand the problem, but making the Next button automatically select the recipient is iffy and pain in the ass to implement.

What I've done instead is replace the Next button when doing a name lookup or a Twitter lookup after a list of recipients are returned with the message "Click on recipient for the next step".

We can tweak the message if you want, of course.
