### ISSUE TITLE
When logging in or signing up, HTTPS should be required

### ISSUE THREAD

**Issue by walter** [opengovernment/askthem-legacy#286]
Encrypt login and signup for end users' security.

**Comment by walter** [comment]
In testing on staging site, https was not being forced. Investigate.

**Comment by walter** [comment]
Spoke too soon. Staging site just hadn't been restarted yet.

**Comment by konklone** [comment]
If you're going to have HTTPS somewhere, you may as well have it everywhere. It's less engineering work if you don't have to worry about the site working on either of two protocols, and the more encrypted the Internet is on the wire, the better. This is part of why we recently began [encrypting Sunlight's Congress API by default](http://sunlightfoundation.com/blog/2014/01/28/encrypting-our-congress-api-and-protecting-your-location/).

**Comment by walter** [comment]
> It's less engineering work if you don't have to worry about the site working on either of two protocols

This isn't always true. Sometimes it is more engineering work.

It depends on the site and how many third party resources it relies upon and whether the third party resources provide HTTPS.

If you can't get HTTPS for a single third party resource on a page you are relying upon, you get the dreaded "mixed protocol" warning.

In our case we rely heavily on image urls from many different providers. Many of these, perhaps most, will not have an HTTPS version of the resource.

There are workarounds, such as mirroring resources on a CDN serving over HTTPS, but that can be problematic, too.

In any case, I ran an experiment to see if HTTPS everywhere was viable for us immediately and it resulted in mixed resource error on our content pages. So it will take some doing to make it work. We have other higher priorities at the moment.

> and the more encrypted the Internet is on the wire, the better.

Agreed. It's definitely a goal for us in the near term, but not in the next month.

**Comment by konklone** [comment]
That's all well understood. FWIW, while I haven't used this myself, Github made and uses a nice simple proxy app called [camo](https://github.com/atmos/camo) to avoid mixed content warnings. It looks real easy, and doesn't have to involve a CDN - you just give it a URL as a query param and it serves it right back for you over HTTPS. You could run it on Heroku, without even needing a custom domain.
