### ISSUE TITLE
After submitting a Q to a verified Twitter Address, receive "whoops, not quite right" message

### ISSUE THREAD

**Issue by maryamgunja** [opengovernment/askthem-legacy#287]
@davidmooreppf 

I submitted Q and then filled out name and address before arriving at this message. I've encountered this a few times. 
![screen shot 2014-01-29 at 12 27 24 pm](https://f.cloud.github.com/assets/5739030/2032135/ea615f68-890a-11e3-9adb-42b3cd4c790b.png)

**Comment by walter** [comment]
Hmm. Then next time this happens @maryamgunja, can you update this issue with the full steps you took to receive the message, please?

That will help us track down what the problem is.
