### ISSUE TITLE
support page not embedding form correctly

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#289]
Do we need to embed this form still? Reckon so :: 

http://www.askthem.io/support

... I can help on my local copy.

**Comment by walter** [comment]
It's "there", but there is actually a JavaScript error with the chartbeat set up that is having cascading failure.

Here's the JavaScript error that it's choking on:

```
ReferenceError: Can't find variable: askthem
```

Commit to fix it coming soon...

**Comment by walter** [comment]
@davidmooreppf this should be fixed after next deploy to production.

**Comment by walter** [comment]
The functionality works on ask them.io/support, but has a weird artifact. Almost like the email icon is repeating, but gets cut off. Not sure what to do about it.

**Comment by davidmooreppf** [comment]
@acacheung maybe you can take a look? This isn't as priority as a few others... 

Error w/ embed :: 

http://www.askthem.io/support

**Comment by davidmooreppf** [comment]
If we don't have time to get this fixed, I'll just change the link in sidebar & in footer to askthem.desk.com. Sorry this is so late-breaking.

**Comment by davidmooreppf** [comment]
Walter, assigning to you, to probably re-direct the link in the sitewide footer & right-hand sidebar to askthem.desk.com, unless we're close to a fix. 

Linking to that is fine.
