### ISSUE TITLE
user account avatars not displaying on question profile pages

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#291]
In Chrome, on pages ::

Q to elected :: 

https://www.askthem.io/ny/questions/52e68797f92ea16b0a00000e

... or Q to Twitter acc't :: 

https://www.askthem.io/questions/52e959fdf92ea1ca7e000002

... my account image is not found, though it's showing here still :: 

https://www.askthem.io/users/52e67ec0f92ea1fe64000006

... maybe a known issue. 

FF doesn't show any avatar at all on Q pages, not even a broken image, .png ::

https://www.dropbox.com/s/7cwil8ondwq71g2/Screenshot%202014-01-29%2014.50.09.png

**Comment by walter** [comment]
Ok, found the issue. It has to do with us now using HTTPS for login/sign up in #286. Need to force back to normal HTTP after login.

Will do that tonight.

**Comment by walter** [comment]
https://github.com/opengovernment/askthem/commit/b39dee8d682ab3065dcc70417a45041328d783a0 should fix this when deployed to production.
