### ISSUE TITLE
/map image doesn't always load 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#292]
In Chrome & FF, on page :: 

https://www.askthem.io/map

... big U.S. map image doesn't always appear, even after a cache-refresh. 

This is the second time this afternoon I've noticed, though after the first time, it did appear on a later visit. Now gone again. Been hitting lots of pages so would have to start fresh to reproduce the issue. 

Not sure what's up with that JS.

**Comment by walter** [comment]
@davidmooreppf are you still having this problem. Sometimes I get a delay, but it loads consistently for me.

**Comment by maryamgunja** [comment]
same with me, I've only experienced delays.
