### ISSUE TITLE
make signature progress bar 2-3x thicker & bigger, both

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#296]
Per trusted feedback. When we get a chance. Realize this is design.

**Comment by acacheung** [comment]
![screen shot 2014-02-06 at 11 48 39 am](https://f.cloud.github.com/assets/1054686/2100997/8e40c0f8-8f4e-11e3-93fe-b0e18fc6f5e9.png)

**Comment by davidmooreppf** [comment]
Def. looks better. 

Any thicker, do you advise?

**Comment by acacheung** [comment]
I think it looks good at this thickness
