### ISSUE TITLE
font for signatures and needed should be bigger. 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#297]
On pages re:: 

http://www.askthem.io/pa/questions/52e67369f92ea1c1c3000017

**Comment by acacheung** [comment]
![screen shot 2014-02-06 at 12 07 21 pm](https://f.cloud.github.com/assets/1054686/2101254/3ba1ca4c-8f51-11e3-9228-32086b7069a7.png)

took away the bold bc i still wanted to keep the same hierarchy

**Comment by davidmooreppf** [comment]
Good !
