### ISSUE TITLE
darken color on light-gray text fields in right-hand sidebar

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#298]
Gray around Text Field labels & borders both is still too light on trusted testers' laptop screens. 

![askthem_text_fields_too_light](https://f.cloud.github.com/assets/116819/2068931/d2a38e40-8d11-11e3-9804-f6877b75ee01.png)

**Comment by davidmooreppf** [comment]
And on homepage, "Enter City and State" copy in main text box above-the-fold. Try darkening.

**Comment by walter** [comment]
@davidmooreppf, can you confirm that this is still a problem for the person, please?

**Comment by davidmooreppf** [comment]
In FF on my MacBook Air - still a bit light, as below :: 

https://www.dropbox.com/s/wznpzhdvbtzftsv/Screenshot%202014-02-06%2019.22.34.png

cc @holmesworcester, our buddy & Board member & product manager, who can take more screengrabs from his older laptop screen. 

His recommendation, checking it out now on his Nexus 4, is to make field label text 40% darker. He'll be online tonight or tmw for further testing of the issues. 

![askthem_fields_too_light](https://f.cloud.github.com/assets/116819/2105988/7018a942-8f99-11e3-8cff-bb702d20c877.png)

**Comment by davidmooreppf** [comment]
Happy Friday @acacheung ! Think you can jump in to darken the text on the field labels? We'll be happy to pay for your time of course. 

Realize you're not nec. on Dockyard clock now, just wanted to follow-through if you're still online and have a moment. I'm on Skype for another two hours before catching a flight.
