### ISSUE TITLE
on question pages, left-justify "499 signatures needed to deliver"

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#299]
Let's try reversing my previous idea & going with a left-justify, instead of right-justify, of "4998 needed to deliver" :: 

http://www.askthem.io/pa/questions/52e67369f92ea1c1c3000017

**Comment by davidmooreppf** [comment]
Maybe try this? See which we prefer. not imperative.

**Comment by acacheung** [comment]
![screen shot 2014-02-13 at 2 51 57 pm](https://f.cloud.github.com/assets/1054686/2164170/518572fe-94e8-11e3-8970-d603b3ed799b.png)

**Comment by davidmooreppf** [comment]
Over to @holmesworcester & @reville - preferences on this, left- or right-justified "signatures needed to deliver"?  

I think I prefer right-justify, but weigh in.

Have separate issue for copy change to "92 needed for response" with verified electeds.

**Comment by holmesworcester** [comment]
I don’t think I have an opinion.

**Comment by davidmooreppf** [comment]
OK let's keep it right, that's what NPR thought too. Don't implement.
