### ISSUE TITLE
question page right-hand sidebar - vertical elements

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#300]
On page :: 

http://www.askthem.io/pa/questions/52e67369f92ea1c1c3000017

a) under zip code, sign button - per #307, we'll aim to strip out 'share' link for now on Q's both signed (putting #240 on ice probably, per @walter & unsigned too).

b) under sign button, our trusted testers HW & NPR suggested we add a "How It Works" section title 

c) Under that, copy as ::

All US elected officials and verified Twitter users can respond to questions that reach the threshold. Many are pre-committed to reply. 

d) Under that, issue areas, etc. 

e) Terms of Service copy as exists.

**Comment by davidmooreppf** [comment]
zip code

sign button 

How it works

Copy: "All US elected officials..."

Issue areas 

By signing, you accept AskThem's terms of service and privacy policy.

**Comment by acacheung** [comment]
![screen shot 2014-02-06 at 12 40 52 pm](https://f.cloud.github.com/assets/1054686/2101738/d97a1cde-8f55-11e3-99c6-767712b900aa.png)

**Comment by davidmooreppf** [comment]
This is perfect - let's shorten to "terms of use" and then close.
