### ISSUE TITLE
add arrow to "sign button" 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#302]
On pages ::

http://www.askthem.io/pa/questions/52e67369f92ea1c1c3000017

add arrow after "sign" in button, as on :: http://grab.by/u0MU

**Comment by acacheung** [comment]
![screen shot 2014-02-06 at 1 18 55 pm](https://f.cloud.github.com/assets/1054686/2102166/4ecf2bdc-8f5b-11e3-9596-bcdf9f452d88.png)
