### ISSUE TITLE
improve circle image clipping

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#303]
For Q targets, e.g. :: 

http://grab.by/u0Mk

**Comment by davidmooreppf** [comment]
E.g. : 

http://www.askthem.io/questions/52e959fdf92ea1ca7e000002

**Comment by walter** [comment]
@acacheung this is specifically for avatars that are imported from Twitter. They come in as small squares already.

**Comment by walter** [comment]
@acacheung fix works when the CDN isn't involved (i.e. development mode). I'll see if I can adjust it to place nicely with the CDN.

**Comment by walter** [comment]
Workaround for CDN is good on staging. Fix should be in place next deploy to production.
