### ISSUE TITLE
strip out "share this" link from unsigned Q pages. 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#307]
Going against my #220 of two mo's ago, I've been encouraged to go leaner & test. 

Mea culpa. Please strip out "share this" link from unsigned Q pages. We'll test the conversions of signing & sharing. 

We can keep buttons exposed for Q pages that have been signed, that work is still great.

**Comment by walter** [comment]
> We can keep buttons exposed for Q pages that have been signed, that work is still great.

Meaning when the user has already signed the question or the question has had any signatures?

I'm assuming meaning that the user has already signed the question. If that is the case #240 will cover this.

So I'll strip out the "share this" completely at this point.
