### ISSUE TITLE
better spacing around Question For: [Recipient] on Q pages

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#308]
E.g. on pages ::

http://www.askthem.io/il-chicago/questions/52f0569af92ea14989000003?share=true#

... seems like the target name needs some spacing :: 

https://www.dropbox.com/s/1zcdaix9iad5tdy/Screenshot%202014-02-03%2020.55.39.png

**Comment by acacheung** [comment]
![screen shot 2014-02-06 at 3 32 40 pm](https://f.cloud.github.com/assets/1054686/2103745/24227248-8f71-11e3-8f5a-583f66a7f37e.png)
