### ISSUE TITLE
Redundant "city" in "Kansas City City" council members

### ISSUE THREAD

**Issue by maryamgunja** [opengovernment/askthem-legacy#311]
![screen shot 2014-02-04 at 1 35 57 pm](https://f.cloud.github.com/assets/5739030/2079536/a19417d8-8dcb-11e3-92dc-e13a8f8f30d4.png)
![screen shot 2014-02-04 at 1 36 07 pm](https://f.cloud.github.com/assets/5739030/2079537/a67643ca-8dcb-11e3-8454-8b2d63f36abe.png)
![screen shot 2014-02-04 at 1 36 32 pm](https://f.cloud.github.com/assets/5739030/2079538/aa0c5998-8dcb-11e3-8b9c-e989c68087d6.png)

**Comment by walter** [comment]
It was a problem coming from data in a third party API. I've let them know and fixed the data in our local cache. Should be ok on our end now.
