### ISSUE TITLE
not signed-in visitor, signing question page directs to /users

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#314]
Maybe still being deployed - not signed-in, on page ::

http://www.askthem.io/la/questions/52f2ace2f92ea1f1ea00002b

.. entering name & email & zip & clicking sign directs to :: 

http://www.askthem.io/users

... error.

**Comment by walter** [comment]
I know the reason (https redirect). Will have fix shortly.
