### ISSUE TITLE
link to New York (Mayor) profile page from Q page

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#316]
From :: 

http://www.askthem.io/ny-brooklyn/questions/52f262d5f92ea109e1000060?share=true#

... as well as :: http://www.askthem.io/ny-brooklyn/questions/52f262d5f92ea109e1000060

.... clicking on de Blasio's name from that Q page goes to ::

http://www.askthem.io/people/52e3e3b6f92ea1272b000011

... which doesn't exist from that path. 

But from ::

http://www.askthem.io/ny-new-york

... this page for him is fine ::

http://www.askthem.io/ny-new-york/people/52e3e3b6f92ea1272b000011

.. the unique identifier in URL is the same, obvs. 

From other Q pages ::

http://www.askthem.io/pa/questions/52e67369f92ea1c1c3000017

... clicking on federal senator there is fine :: 

http://www.askthem.io/pa/people/T000461

... for this Chicago city official Q ::

http://www.askthem.io/il-chicago/questions/52f0569af92ea14989000003

.... this page is fine for him ::

http://www.askthem.io/il-chicago/people/52e2c2f9f92ea11dd800001e

**Comment by walter** [comment]
Yeah, this is a unique situation for NYC data because of the five boroughs… I'm on it.

**Comment by walter** [comment]
I've moved the questions for Bill de Blasio to the New York jurisdiction rather than Brooklyn:

http://www.askthem.io/ny-new-york/questions/52f262d5f92ea109e1000060

Hopefully you haven't shared any questions for him under ny-brooklyn.
