### ISSUE TITLE
On /users/sign_up, add note next to Zip Code field for international users

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#318]
cc @walter 

On :: 

https://www.askthem.io/users/sign_up

... please add a note on right-side, same style, that reads: 

Non-U.S. users, please enter: 00000 for now. You can still ask Q's, especially to Twitter recipients, and we'll update you when we have more international support.

**Comment by acacheung** [comment]
![screen shot 2014-02-06 at 4 00 45 pm](https://f.cloud.github.com/assets/1054686/2103789/c4b635be-8f71-11e3-8ef1-759b27825194.png)
