### ISSUE TITLE
"ask this person a question" button width

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#319]
On person pages :: 

http://staging.askthem.io/pa-philadelphia/people/5284b8f3d2a57d193200000d

... "Ask this person a Question" button is a bit tight. @walter noticed and thinks it's squeezed in a class. 

Give a fix for more space?

**Comment by davidmooreppf** [comment]
Similar here, "ask a question" button, just adding :: 

http://staging.askthem.io/pa-philadelphia

**Comment by acacheung** [comment]
![screen shot 2014-02-13 at 2 48 28 pm](https://f.cloud.github.com/assets/1054686/2164132/e425cccc-94e7-11e3-9937-e70093ee105a.png)
