### ISSUE TITLE
when asking a question, recipient list doesn't show up 

### ISSUE THREAD

**Issue by derekeder** [opengovernment/askthem-legacy#32]
Looks like the recipient list is being triggered by a callback on the zip code field. This is bad UI, especially if I have an account and my address info is already populated.

**Comment by walter** [comment]
I agree, but is it "good enough for MVP"?

Happy to go with an alternative implementation if you have one that is quick to do, otherwise I would say we keep this issue open, but not work on it for now.

**Comment by walter** [comment]
Also, can you clarify the scenario where you encounter the bug. I.e. take us through the steps to reproduce the bug.

**Comment by derekeder** [comment]
Sure! Steps to reproduce:
- create an account
- navigate to [new question page](http://oglocal.herokuapp.com/ny/questions/new)
- address is already pre-populated because I'm logged in and no recipients are listed
- can't proceed to the next step without selecting a recipient
  ![screen shot 2013-08-05 at 9 12 44 am](https://f.cloud.github.com/assets/919583/910373/1eee1284-fdd9-11e2-8e3d-39019a7a4309.png)

Looks like you can trigger the recipients callback by pressing enter while the zip code field is selected.

**Comment by walter** [comment]
Thank you! That definitely solves the mystery for me.

It's not just a matter of bad UI (though it still is), it's a matter of functionality being broken.

So yeah, this does need to be fixed. I think it is fastest for me to take care of it.
