### ISSUE TITLE
add staff & advisory Council photos to /about page

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#320]
If you have time, please add staff & advsiory council photos from /splash page to /about. Anywhere is fine. 

To Advisory Council, please add photos & a placeholder bio line from ::

https://twitter.com/antheaws

https://twitter.com/_svila

https://twitter.com/amichel

...and headshot from :: 

http://davidkarpf.com/

I can refine the bios once the copy is in there.

**Comment by acacheung** [comment]
![screen shot 2014-02-06 at 4 48 51 pm](https://f.cloud.github.com/assets/1054686/2104233/80141852-8f78-11e3-944d-7ecb2fa57fea.png)

**Comment by davidmooreppf** [comment]
Looking great, thx. 

Can you add the four new Adv. Counc. members in same format?

**Comment by acacheung** [comment]
![screen shot 2014-02-06 at 5 00 10 pm](https://f.cloud.github.com/assets/1054686/2104339/165f8778-8f7a-11e3-9c8f-6c1403ed4b9c.png)
