### ISSUE TITLE
broken image in sign up confirmation email

### ISSUE THREAD

**Issue by derekeder** [opengovernment/askthem-legacy#326]
Signed up today and the AskThem logo didn't load in my confirmation email. 

Email client is Gmail. Could be because of their recent [cached images updates](http://gmailblog.blogspot.com/2013/12/images-now-showing.html)

![screen shot 2014-02-07 at 11 14 33 am](https://f.cloud.github.com/assets/919583/2112218/6c333a68-901b-11e3-8753-e2ce4c17520c.png)

**Comment by walter** [comment]
@davidmooreppf let me know if you have questions on this...

**Comment by walter** [comment]
We have a duplicate with a bit more detail.
