### ISSUE TITLE
add "ask a question" button to user's "My Questions" page

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#329]
Add to ::

http://www.askthem.io/users/52e67ec0f92ea1fe64000006

... in usual place.

**Comment by walter** [comment]
Before questions listed or after?

**Comment by davidmooreppf** [comment]
Was thinking parallel with "16 signatures", above the Q's asked, tucked in here along the right :: 

https://www.dropbox.com/s/lbqxm9skugyk5c9/Screenshot%202014-02-08%2017.10.06.png

... button size like this one, I guess :: 

http://www.askthem.io/ny-new-york

**Comment by acacheung** [comment]
![screen shot 2014-02-13 at 3 06 02 pm](https://f.cloud.github.com/assets/1054686/2164311/6029cec0-94ea-11e3-957d-16a098fed3f1.png)

**Comment by acacheung** [comment]
@walter added the generic ask question but can be changed to what you'd prefer
users/show.html.erb line 51

**Comment by walter** [comment]
That should work. It will look up the user's address and direct to the correct state for them. So yeah, generic ask question is good.

@acacheung or @davidmooreppf anything else on this? If not, please close.

**Comment by davidmooreppf** [comment]
Works!
