### ISSUE TITLE
Media url accepts non-image and presents it as video

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#333]
Update: See @walter's comment for description of the Twitter status being accepted as valid media url.

---

Original Title:  videos in Q's: not playing back; when I submit, error, "Media file url is invalid"

Original Description follows:

Noticed on popular Q that video embed isn't playing :: 

http://www.askthem.io/wa/questions/52f582a5f92ea1870b00001a

Attempted to submit Q to two diff. recipients w/ URL :: 

https://vimeo.com/40887087

... got error message in subject above.

When I go back to start a new Q, the content is saved, and this appears in the video line below :: 

//player.vimeo.com/video/40887087 

... if we need to disable video for launch, and debug, that's better than embedding non-playable videos. Over to you. 

cc @maryamgunja

**Comment by walter** [comment]
So http://www.askthem.io/wa/questions/52f582a5f92ea1870b00001a is a link not to a video, but a Twitter status that contains an image:

https://twitter.com/Lisa4horses/status/426759121329606656/photo/1/large

So there are two problems. 

The first is that Twitter statuses shouldn't be presented as a playable video at all. We actually are not handling embeds right now. So it should have rejected the URL (diplomatically stating that we don't support embedded images at this time).

The second is that of an actual Vimeo video being rejected as as invalid. I've found the cause and think I can fix it pretty easily.

However accepting free form URLs for media will likely always be tricky. There are open standards for this sort of stuff, but it's basically fallen out of favor. So we're dealing with the wild west.

I'm going to move the discussion of the second issue back to the original implementation issue #245.

I'm going to edit this issue to be about the first problem.
