### ISSUE TITLE
Twitter recipient finding working as expected?

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#334]
In Chrome, logged in as my admin acc't :: 

http://www.askthem.io/users/52e67ec0f92ea1fe64000006

... from refreshed :: 

http://www.askthem.io/ny/questions/new

... app just keeps loading, not returning, when searching for verified Twitter acc'ts ::

mikeallen

tanlines

sammybananas

---

chrislhayes, who exists already in production, was not found either. 

---

This shouldn't matter, but realdonaldtrump, who's in staging but I don't think in production, is found right away. how about that. 

Some links from my acc't :: 

http://www.askthem.io/users/52e67ec0f92ea1fe64000006

... let me & @maryamgunja know how to test, she was pulling up a number of Twitter accounts even today. Maybe this is a temporary glitch, just submitting while I have this written up.

**Comment by davidmooreppf** [comment]
Unpredictably, was able to pull up Tanlines a few minutes ago - though he flickered in, and had to delete his last "s" to get him to reappear, as have with chrislhayes in the past - maybe we can't control more on this now, and will have to try post-launch :: 

http://www.askthem.io/questions/52f6da03f92ea1642c000019

**Comment by walter** [comment]
It seems like it must be intermittent connectivity problem with Twitter.

I tested all those names plus a few others not in the system and they all came up for me on production using Chrome and logged in (and logged out).

We definitely want to add better handling of Twitter errors and connectivity issues.

**Comment by maryamgunja** [comment]
I've noticed that the lag time is the same for someone who is already in
our system, like Mike Allen, realdonaldtrump, etc... Yesterday I played
around with adding/removing the "@''  and that was pretty responsive....
not sure if we should write copy about this for users because it's only a
problem for me intermittently

**Comment by walter** [comment]
Closing this. It seems to be in working order generally.
