### ISSUE TITLE
run AskThem links in Twitter share through shortener

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#338]
After launch : 

http://www.askthem.io/ia/questions/52f25ec2f92ea109e1000006#

... Q copy when shared to Twitter, see about services to run long AskThem link through ::

Support my question to @ChuckGrassley on @AskThemPPF: How do you feel about the exponential growth in the role of private contractors in nat’l security?
 http://www.askthem.io/ia/questions/52f25ec2f92ea109e1000006

**Comment by walter** [comment]
All links posted to Twitter get run through Twitter's shortener, I believe. I'm pretty sure the length of URLs don't count against character count.

**Comment by davidmooreppf** [comment]
Re-opening #295 for this fix. Cool.
