### ISSUE TITLE
hard-code link to Hayes' profile above-fold on homepage before show tonight

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#341]
Goal is to show Hayes' page :: 

http://www.askthem.io/people/52e958f1f92ea1cfe8000014

... somewhere above fold before his 8pm show tonight. Whatever's easiest - if above the top national & near-you Q's, that's fine, if that's doable. 

The banner could be a fallback, but that's not really ideal, as ppl won't be looking for it there really. 

We'll shout-it out on FB & Twitter, but still.

**Comment by walter** [comment]
Instead of hardcoding we're going to try for a down and dirty implementation of two featured people.

On the left is national and on the right is actually not "featured" per se, but someone that hasn't had a question asked of them yet near the person.

Just spitballing. We'll see how it develops.

**Comment by walter** [comment]
To be clear, whether the national person is featured would not have an admin UI yet. Simply done via the console like so:

First make the last featured person unfettered if there was someone featured.

``` ruby
person = Person.find("the_id")
person.featured = false
person.save!
```

Then make your new featured person featured.

``` ruby
person = Person.find("the_id")
person.featured = true
person.save!
```

**Comment by walter** [comment]
On production and tweaked styles in place!
