### ISSUE TITLE
Facebook share - new formatting bug, or inconsistent behavior

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#348]
Urgent fix of course - found by @reville - from Q page to a verified Twitter acc't ::  

http://www.askthem.io/questions/52faaef79d29c9bff1000009

... logged-in user clicking FB share button (in Chrome & FF) goes to URL ::

https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.askthem.io%2Fquestions%2F52faaef79d29c9bff1000009

... which is missing good formatting ::

https://www.dropbox.com/s/u9az0vlb7yf1hm7/Screenshot%202014-02-11%2018.54.32.png

![screenshot 2014-02-11 18 54 32](https://f.cloud.github.com/assets/116819/2143764/ed64dc36-9377-11e3-84f1-d52ce75e19f8.png)

... previous Q to elected official in our DB has proper formatting ::

http://www.askthem.io/wi/questions/52f26053f92ea109e1000031

https://www.dropbox.com/s/y4wgokotb37zpp2/Screenshot%202014-02-11%2018.58.30.png

... new question to a verified Twtr user not in system has proper formatting ::

http://www.askthem.io/questions/52fab9cb9d29c9f120000002

https://www.dropbox.com/s/pd327wy3bodnbtf/Screenshot%202014-02-11%2019.01.56.png

**Comment by walter** [comment]
Twitter accounts do not have large enough avatars to have recipient's image be used. I defaulted to the previously generic image.

Since the Twitter avatar is out, what would you like to use instead?

**Comment by walter** [comment]
As far as formatting… there may be a delay for Facebook to generate it since they must request the page being linked to behind the scenes and then parse, etc.

Then they cache the results and the next person sharing the page should have a properly formatted preview.

In regards to the Fight for the Future question. If a question has an uploaded or linked to image, we suggest that to Facebook as the preview image, if there isn't, we use the recipient's avatar, if the recipient's avatar is too small (all verified Twitter accounts), we use the default.

So far it looks to me like it is working by design. Happy to change default image, but there isn't much more we can do.

**Comment by davidmooreppf** [comment]
Word. So for Q :: http://www.askthem.io/questions/52faaef79d29c9bff1000009 ... 

... we'll see if it resolves itself in a bit, as FB generates it & parses it. As of now, the just-above question is appearing w/out an image on FB share.

... seems like our logic is sound, then, for FB sharing :: 

If Q has image, use it.

If Q is to elected official in our DB, use avatar photo. 

If Q is to verified Twitter user, use standard share "badge". 

... so seems like we'll take another look at above instance later. Thx Walter.

**Comment by reville** [comment]
this seems very strange to me, are we really saying that the first person to share on Facebook will see no headline, text, or image?

**Comment by reville** [comment]
I would also suggest using the askthem circle logo as the default image if we don't have anything else.  it conveys the idea of a question pretty clearly

**Comment by walter** [comment]
> this seems very strange to me, are we really saying that the first person to share on Facebook will see no headline, text, or image?

No, in most cases FB will parse the page pretty quickly and it will be done by the time their sharing page loads.

We are following the OpenGraph spec to the best of my current knowledge.

However, there are variables:
- how long the page takes to load on our side (i.e. if the particular page, or our hosting situation, are suboptimal, then it could in their time out)
- something is wrong between our page and FB over the network (least likely)
- something is wrong on FB's end

We are paying attention to general and specific performance, but it is a work in progress and of course factors (like spikes in traffic) come into play. It's inherently a process of learning and tweaking.

**Comment by walter** [comment]
> I would also suggest using the askthem circle logo as the default image if we don't have anything else. it conveys the idea of a question pretty clearly

I'm not opposed. I've noticed the cityscape with text sometimes get's partially cut off by FB. I think the question mark logo, even if cut off, is more communicative at a glance.

**Comment by walter** [comment]
@davidmooreppf can you let me know if you would like me to change the default image, please?

**Comment by walter** [comment]
Reassigning to @davidmooreppf for deciding on default image. Assign back to me when decision is made.
