### ISSUE TITLE
formatting on Lander Q response

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#349]
http://www.askthem.io/ny-brooklyn/questions/52f7eba9ec8d83370b000002

**Comment by walter** [comment]
Fixed in 

https://github.com/opengovernment/askthem/commit/34efed8ab2fc38897b536026e4d1a6778e58f3fb

and

https://github.com/opengovernment/askthem/commit/626e056537e2021b06435ddb4cb8871cf435fd08
