### ISSUE TITLE
'Question reaching threshold not sticking to "people page" 

### ISSUE THREAD

**Issue by maryamgunja** [opengovernment/askthem-legacy#351]

**Comment by walter** [comment]
To clarify for future reference:
- questions on person's page (people#show), are not paginated 
- whether the question has reached threshold or not is not taken into account in how the questions are listed

The combination of those two factors mean that questions that have reached threshold may be pushed of the person's page.

**Comment by walter** [comment]
This has been addressed by other issues at this point.
