### ISSUE TITLE
Errors on "Interest Group" copy _ E. Warren

### ISSUE THREAD

**Issue by maryamgunja** [opengovernment/askthem-legacy#353]
Redundant/outdated copy and spelling issue:
http://www.askthem.io/ma/people/W000817/ratings

*I'm not sure where we pull copy from for this content, but let me know if you want me to find different info for her
    "Bsed on legislative votes, sponsorship of legislation not voted upon, and endorsements of special "dear colleague" letters that the NumbersUSA [Americans for Better Immigration] considered to be the most important in 1989-2013, Senator Elizabeth Warren supported their preferred position percent of the time."

**Comment by walter** [comment]
We grab this from Project Vote Smart (http://votesmart.org), but we don't update it regularly yet.

You could check whether their data is up to date. If it is, I can possibly do an update for her.

If it isn't up-to-date on their site, you should alert them.

**Comment by walter** [comment]
Assign this back to me after all the details upstream are tracked down.
