### ISSUE TITLE
bug w/ hyperlinks on Brad Lander response page 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#359]
Whoopsers, display didn't quite come out right :: 

http://www.askthem.io/ny-brooklyn/questions/52f7eba9ec8d83370b000002

<p>I&#x27;m a strongly &quot;pro-growth&quot; progressive, for reasons I outline here: &lt;a href=&quot;<a href="http://21c4all.org/neighborhoods&quot;&gt;http://21c4all.org/neighborhoods&lt;/a">http://21c4all.org/neighborhoods&quot;&gt;http://21c4all.org/neighborhoods&lt;/a</a>&gt;. 

![brad_lander_hyperlinks_issue](https://f.cloud.github.com/assets/116819/2154512/f8378280-9435-11e3-8c9b-03041a51cb6f.png)

**Comment by walter** [comment]
Fixed.
