### ISSUE TITLE
rake tasks for importing openstates need access to private methods

### ISSUE THREAD

**Issue by rchekaluk** [opengovernment/askthem-legacy#36]
The rake tasks for importing OpenStates JSON (lib/tasks/openstates.rake) currently require access to these private methods:
- Metadatum::State.api_key
- Metadatum::State.api_base_url

The rake tasks had been working but (presumably) stopped working with commit 9ac2e492a

**Comment by walter** [comment]
I'm cool with making those two public. Feel free to commit change necessary.
