### ISSUE TITLE
Add "marijuana" or "marijuana reform" to issue list

### ISSUE THREAD

**Issue by maryamgunja** [opengovernment/askthem-legacy#363]
![screen shot 2014-02-13 at 1 26 39 pm](https://f.cloud.github.com/assets/5739030/2163224/68e3dc30-94dc-11e3-8e88-fd7d71893c01.png)

**Comment by davidmooreppf** [comment]
Word; Committed, will be live in next deploy.

**Comment by walter** [comment]
https://github.com/opengovernment/askthem/commit/4296dcfd3dc767d80b305b195ca3ecee31b7f7cf should do it.
