### ISSUE TITLE
banner for homepage showcasing official response from elected official

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#365]
cc @walter, goal is to promote our first answered Q by an elected official on homepage above the fold. 

So thinking we could add a banner to homepage, above the "featured" and "elected official near you" row in white, in this space ::

https://www.dropbox.com/s/aqn877xq5dfqb07/Screenshot%202014-02-13%2015.21.53.png

...thinking a thin banner with copy about 2/3 the size of the <h1> type. 

Elements to include: 

Copy as : 

Answered question from NYC Council member Brad Lander 

(Potential sub-hed copy to include, if we go with two lines in banner) 

On the issue of affordable housing

---

(or, if one line, Answer to a public question by NYC Council member Brad Lander) 
## 

...include his avatar, if if fits in there, even very small. It may not fit, even our tiniest view of his face, but would be good. 

---

Some part of above copy should link to the Q page in question :: 

http://www.askthem.io/ny-brooklyn/questions/52f7eba9ec8d83370b000002

... the hyperlink could be "Answered question". 
## 

So realize I don't know how much copy can fit in a thin banner, so can edit on the fly.

**Comment by acacheung** [comment]
![Uploading Screen Shot 2014-02-13 at 6.53.09 PM.png . . .]()
