### ISSUE TITLE
from /people pages of Q listings, new behavior when user clicks "sign" 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#369]
From pages ::

http://www.askthem.io/ny-brooklyn/people/52e6914bf92ea10b3900000a

... for logged-in users, currently clicking "sign" button on that Q listing page keeps user on that page, and button just flips to "signed". 

... preferred behavior when user clicks sign : 
- Q is signed, and detail page loads with sharing modal enabled, e.g.: 

http://www.askthem.io/ny-brooklyn/questions/52e6957ff92ea19a1a000002?share=true

**Comment by walter** [comment]
https://github.com/opengovernment/askthem/commit/896212d8e37bcaeefd7b098cbdcf51c5c17803af finishes implementing this.
