### ISSUE TITLE
change twitter handle for state rep - and generally, Google Civic Info issue reporting

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#370]
Tip from user, on state rep page :: 

http://www.askthem.io/ny/people/T000469

Twitter shows username paultonka, should be reppaultonka. Assign over to Google Civic Info if appropriate. (I can check w/ our contacts there to confirm their preferred issue reporting workflow.)

**Comment by walter** [comment]
Changed locally and report to Google Civic Info.
