### ISSUE TITLE
prioritize question-mark image over user profile image in FB sharing image selection

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#374]
Hearkening back to #348, FB today grabbed Maryam's profile photo as its image: 

https://www.dropbox.com/s/5q86f8iyc38agam/Screenshot%202014-02-18%2017.30.36.png

... to avoid such, can we seek to prevent FB from doing that, i.e. if the attached image to the AskThem Q is too small / low-res, falling back to setting our question-mark image as the accompaniment on FB? Not sure what's poss. in code.

**Comment by walter** [comment]
Until we can figure out a way to fix the larger issue, is there an alternative image with a larger resolution that I can swap into place for this question?

**Comment by walter** [comment]
Also, in the case that there is a recipient with a good enough image, would you prefer that over the AskThem mark?

**Comment by maryamgunja** [comment]
Can we use the badge jpg in the mean time?

**Comment by walter** [comment]
I have an experimental fix. Facebook allows declaring more than one thumbnail image. I believe if we always declare the mark image (question mark logo), if the other image specific to the question is too small for FB, it will use the mark instead.

That's my hope anyway. Going to have to test this on production to know for sure.

Will let you know what the result is.

**Comment by walter** [comment]
I've put in place the multiple images with the question mark as the default solution and it now works as expected.
