### ISSUE TITLE
create About page

### ISSUE THREAD

**Issue by derekeder** [opengovernment/askthem-legacy#39]
@davidmooreppf could you flesh out what should go on it here?

Requirements:
- static page located at /about
- link to it in the footer

**Comment by walter** [comment]
Seems like a lot of the splash page can be repurposed for this @davidmooreppf.

**Comment by acacheung** [comment]
Made more sense to use the application layout because of all the header and footer links. @davidmooreppf Let me know if you would rather it use something more similar to the splash page layout

![Uploading about.png . . .]()

**Comment by acacheung** [comment]
@davidmooreppf you can edit the content at /views/pages/about.html.erb

**Comment by walter** [comment]
@davidmooreppf is this done? Please close is so.

**Comment by davidmooreppf** [comment]
Still need to add copy & images. Just haven't gotten to it yet.

**Comment by walter** [comment]
Was done earlier today.
