### ISSUE TITLE
add editorial blurb to person pages

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#392]
Short-term goal is to add a note atop GG page :: 

http://www.askthem.io/people/52f82b59f92ea1782c000011

... about Mon. event. Medium-term solution would be a "blurb" feature for every Q recipient page, for editors to make notes, but short-term is fine for now. 

What's easiest - a link above-the-fold (as opposed to a badge or something) that goes to our latest blog post? 

http://www.participatorypolitics.org/ask-glenn-greenwald-anything-hell-be-answering/

... there's room under the 'ask a question' button obvs. : 

https://www.dropbox.com/s/mpplde3c1gl6nz5/Screenshot%202014-03-07%2017.11.14.png

... w/ copy as "Crowdsourced Q&A with Glenn Greenwald, Monday March 10th at SxSW" - or shorter.

**Comment by walter** [comment]
I would say a mini banner not unlike the homepage blurb that goes above Glenn Greenwald and the "ask a question" would be simplest.

What do you want the copy to be? I can do a short term hack just on the GG's page.

**Comment by davidmooreppf** [comment]
Nice. Any variant of :: 

Crowdsourced Q&A with Glenn Greenwald - Monday, March 10th at SxSW 

Glenn Greenwald answers your questions from AskThem - Monday, March 10th 

Glenn Greenwald has agreed to answer some popular questions on AskThem!

... if we have HTML ability, we could link to - but that's def. not necessary: 

http://www.participatorypolitics.org/ask-glenn-greenwald-anything-hell-be-answering/

**Comment by walter** [comment]
I'm piggybacking off the homepage blurb functionality and adding the same functionality for people pages.

A staff member can go to a person page and click "add blurb" and will get form to enter one specific to the person's page.

Only one blurb can be active (to be displayed) per person page at a time.

**Comment by walter** [comment]
http://www.askthem.io/people/52f82b59f92ea1782c000011

You can add a different blurb as a staff member by using the "add blurb" button on his page.
