### ISSUE TITLE
disable auto-play of videos in Q responses

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#393]
In pages w/ YT videos e.g. this answer from last night :: 

http://www.askthem.io/tx-austin/questions/52f10ca2ec8d83660000000e

... or just snip it out for now. My bad, should have tested on staging before pushing. Ooff.

**Comment by walter** [comment]
de6b784a8db89d9cd614e5f30fa2a9effe8d0377 switches to auto play false. Running a rake task to update all existing items with videos.

**Comment by walter** [comment]
Damn. This is going to take a little more work. Will be later today.

**Comment by walter** [comment]
Ok, I had missed turning autoplay off for answers. Now done and moved to production.
