### ISSUE TITLE
on recipient profile pages, link "answered questions" to /have_answers view

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#394]
On GG page ::

http://www.askthem.io/people/52f82b59f92ea1782c000011

.. in space "4 answered questions", we can now link that to ::

http://www.askthem.io/unaffiliated/questions/have_answers?person=52f82b59f92ea1782c000011

... of course we don't have those filtering views for other Q recipients yet, but we do for GG in the short term.

**Comment by walter** [comment]
It will actually work for anyone at this point.
