### ISSUE TITLE
Change default sharing copy for answered Q's

### ISSUE THREAD

**Issue by maryamgunja** [opengovernment/askthem-legacy#395]
When a question is answered change the sharing copy on FB/Twitter to reflect answer rather than to encourage signatures...

Current:

![screen shot 2014-03-13 at 6 16 05 pm](https://f.cloud.github.com/assets/5739030/2416021/27e9cc30-aafd-11e3-8346-1d46cab176e1.png)
![screen shot 2014-03-13 at 6 16 20 pm](https://f.cloud.github.com/assets/5739030/2416023/2cc55508-aafd-11e3-8b85-9ea645090326.png)

**Comment by davidmooreppf** [comment]
So in /questions/show, I see       <%= twitter_question_share( in line 140, and the copy for email sharing subject in 152, but I don't know if I see the place to change it where Q status is answered. Little help @walter?

**Comment by walter** [comment]
This functionality requires some additional logic added to it.

I'm planning on doing this today. Will close this when it is done and let you know when it is deployed.

**Comment by walter** [comment]
We should probably go through each sharing piece of text.

Here's what we have now for mail:

https://github.com/opengovernment/askthem/blob/master/app/helpers/questions_helper.rb#L44-L56

Here's what we have for Twitter:

https://github.com/opengovernment/askthem/blob/master/app/helpers/questions_helper.rb#L44-L56

(hopefully you can get the gist of the programming)

For Facebook and Google+, we can't do much unfortunately for long convoluted reasons.

**Comment by maryamgunja** [comment]
Revised Sharing Copy
_-_

_Twitter_

Current:

Support my question to @TexGov on @AskThemPPF: Why are we subsidizing oil
companies for stealing our resources and polluting our air, land and wate
http://www.askthem.io/tx/questions/532712b3d535cfa1dd00004b

_Change to:_

Share (name/handle of official's) answer on @AskThemPPF to "(question
title)" (Question)URL

_FB_

Current:

Ask Rick Perry: "Why are we subsidizing oil companies for stealing our
resources and polluting...
www.askthem.io
_Click to support this question on AskThem.io and get a public response._

_Change to_:

Share (name/handle of official's) answer to: "(question title)"
www.askthem.io
_Click to support this answer on AskThem.io._

_Google +_

Current: Ask Rick Perry: "Why are we subsidizing oil companies for stealing
our resources and polluting our air, land and wate" - Texas - AskThem.io

Change to:

Share (name/handle of official's) answer: "(question title)" - (State)-
Askthem.io

**Comment by maryamgunja** [comment]
...with capped twitter characters on copy to 60 instead of 100 (current)

**Comment by walter** [comment]
@davidmooreppf & @maryamgunja this is now in place on the live site.

Note that FB & Google+ text is a bit different, but does indicate there is an answer rather than call for signatures.
