### ISSUE TITLE
formatting of URLs in answers

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#396]
I have to test this but I think @maryamgunja said that plaintext URLs bleed out of the answer space but link-shorteners work, e.g. here :: 

http://www.askthem.io/tx-austin/questions/531cdb12ec8d8383bf00009a

... Walter, should we just recommend that Q recipients use shorteners in their answers?

**Comment by walter** [comment]
We probably can do some CSS to truncate long URLs if necessary with a "…".

I'll look into it.

**Comment by walter** [comment]
Weird. I've tried to recreate this issue with the exact content that originally had the problem, but can't.

The long urls just wrap to a new line if they are longer than 1 line long.

It may have be some other CSS or JavaScript was causing the problem at the time, but it has changed and it is now fixed. Hard to know.

So I'm going to go ahead and close this and we'll create a new issue with specific instance of the problem if it occurs again.
