### ISSUE TITLE
create Support page

### ISSUE THREAD

**Issue by derekeder** [opengovernment/askthem-legacy#40]
@davidmooreppf is this a page for taking donations? Please flesh out content here.

Requirements:
- located at /support

**Comment by acacheung** [comment]
@davidmooreppf You can edit the content at views/pages/support.html.erb

**Comment by walter** [comment]
I believe this is basically done once desk.com has been put in place in opengovernment/ops/issues/98.

**Comment by davidmooreppf** [comment]
Switching to debugging in #289.
