### ISSUE TITLE
draft blog post with links to city council overview pages

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#401]
Kudos @walter! Bringing in county electeds from the API captured a couple more cities 

Maryam, from http://www.askthem.io/map, create a new PPF Blog post with links to the city council overview pages, in their current shape, following this format :: 

<a href="http://www.askthem.io/wa-seattle#">Seattle city council</a> - 8 council members & Mayor Murray.

Sound good?

**Comment by walter** [comment]
In the future I think I would add this in askthem-admin.

**Comment by maryamgunja** [comment]
Cool, will do.

So is the plan to only list those that are populated?

**Comment by davidmooreppf** [comment]
Yeah just those that are there now, via the "change" link. If you have any luck populating some other major cities by address, that's great, but not sure that's working now.

**Comment by maryamgunja** [comment]
Below is a comprehensive list of cities we have data for. Cities in red are
available to view but don't have any reps. listed on the site yet.

I'm not having any luck populating cities by address, but I'll experiment a
little bit more. Before we post I want to add Q's for the major cities &
check to confirm that electeds office status is correct for every city (per
"Assign new titles for Mayor/city council #32)
https://github.com/opengovernment/askthem-admin/issues/32

https://github.com/davidmooreppf

@davidmooreppf https://github.com/davidmooreppf, let me know what your
preferred timeline is on this..

_Alabama_

Birmingham city council- Mayor Bell, Sr.http://www.askthem.io/al-birmingham

Mobile city council- Mayor Stimpson http://www.askthem.io/al-mobile

_Arizona_

Phoenix city council http://www.askthem.io/az-phoenix-3 council members &
Mayor Stanton

Mesa city council http://www.askthem.io/az-mesa\- 1 city council & Mayor
Smith

_California_

Los Angeles city council http://www.askthem.io/ca-los-angeles-\- 4 council
members & Mayor Garcetti

San Jose city council http://www.askthem.io/ca-san-jose\- 10 council
members & Mayor Reed

Oakland city council http://www.askthem.io/ca-oakland\- 2 council members
& Mayor Quann

San Francisco city
councilhttp://www.askthem.io/ca-county-san-francisco%20%20%20-
Mayor Lee

_Colorado_
Aurora city council http://www.askthem.io/co-aurora\- 4 council members &
Mayor Hogan

Denver city council http://www.askthem.io/co-county-denver\- 12 council
members & Mayor Hancock

*Delaware *

Wilmington city council http://www.askthem.io/de-wilmington\- 5 council
members & Mayor Williams

_Florida_

Miami city council http://www.askthem.io/fl-miami*- *Mayor Regalado

Melbourne city council http://www.askthem.io/fl-melbourne\- Mayor Meehan

Duval city council- http://www.askthem.io/fl-county-duval 5 council
members
Jacksonville city council http://www.askthem.io/fl-jacksonville-5 council
members & Mayor Brown

_Hawaii_

Honolulu city council http://www.askthem.io/hi-county-honolulu\- Mayor
Caldwell

*Illinois *

Chicago city council http://www.askthem.io/il-chicago\- 51 council members
& Mayor Emanuel

_Indiana_

Grant city council http://www.askthem.io/in-county-grant\- 3 council
members

Marion city council http://www.askthem.io/in-county-marion

*Louisiana *

Parish:calcasieu http://www.askthem.io/la-county-parish:calcasieu

Parish: iberia http://www.askthem.io/la-county-parish:iberia

Parish:ouachita
 http://www.askthem.io/la-county-parish:ouachita

_Maine_

Portland city council http://www.askthem.io/me-portland*- *3 council
members & Mayor Brennan

_Michigan_

Detroit city council http://www.askthem.io/mi-detroit\- 2 council members
& Mayor Duggan

_Minnesota_

Minneapolis http://www.askthem.io/mn-minneapolis\- Mayor Rybak

_Missouri_

Kansas city council http://www.askthem.io/mo-kansas-city\- 5 council
members & Mayor James

*Mississippi *

Jackson city council http://www.askthem.io/ms-jackson\- Mayor Lumumba

_Montana_

Billings city council http://www.askthem.io/mt-billings\- Mayor Hanel

_North Carolina_

Raleigh city council http://www.askthem.io/nc-raleigh\- 2 city council
members & Mayor McFarlane

Charlotte city council http://www.askthem.io/nc-charlotte\- 5 city council
members & Mayor Cannon

_New Jersey_

Newark city council http://www.askthem.io/nj-newark\- 3 council members &
Quintana

_New Mexico_

Albuquerque city council http://www.askthem.io/nm-albuquerque\- 2 council
members & Mayor Berry

_Nevada_

Las Vegas city council http://www.askthem.io/nv-las-vegas\- Mayor Goodman

_New York_

New York city council http://www.askthem.io/ny-new-york\- 10 council
members & Mayor De Blasio

Brooklyn city council http://www.askthem.io/ny-brooklyn\- 14 council
members

Bronx city council http://www.askthem.io/ny-bronx\- 2 council members

Queens city council http://www.askthem.io/ny-queens\- 1 council member

Staten Island city council http://www.askthem.io/ny-staten-island\- 1
council member

Buffalo city council http://www.askthem.io/ny-buffalo\- Mayor Brown

Syracuse city counci http://www.askthem.io/ny-syracusel- 3 council
members

Ohio

Cincinnati city council http://www.askthem.io/oh-cincinnati\- 7 council
members & Mayor Cranley

Columbus city council http://www.askthem.io/oh-columbus

_Oklahoma_

Oklahoma city council http://www.askthem.io/ok-oklahoma-city\- Mayor
Cornett

Tulsa http://www.askthem.io/ok-tulsa city
councilhttp://www.askthem.io/ok-tulsa-
Mayor Bartlett

_Oregon_

Portland city council http://www.askthem.io/or-portland\- Mayor Hayes

_Pennsylvania_

Philadelphia city council http://www.askthem.io/pa-philadelphia\- 17
council members & Mayor Nutter

_Rhode Island_

Providence city council http://www.askthem.io/ri-providence\- Mayor Taveras

_South Carolina_

Columbia city council http://www.askthem.io/sc-columbia\- 2 council
members & Mayor Benjamin

_Texas_

Austin city council http://www.askthem.io/tx-austin\- 6 council members &
Mayor Leffingwell

Houston city council http://www.askthem.io/tx-houston\- 5 council members
& Mayor Parker

_Virginia_

Virginia Beach city council http://www.askthem.io/va-virginia-beach\- 3
council members & Mayor Sessoms, Jr.

Newport News city council http://www.askthem.io/va-newport-news\- 5
council members

Richmond city council http://www.askthem.io/va-richmond\- 1 council member

Charlotte city council http://www.askthem.io/nc-charlotte\-  5 council
members & Mayor Cannon

_Washington_

Seattle city council http://www.askthem.io/wa-seattle - 8 council members
& Mayor Murray

Spokane city council http://www.askthem.io/wa-spokane\- 1 council member

*Wisconsin *

Milwaukee city council http://www.askthem.io/wi-milwaukee\- 1 council
member

**Comment by maryamgunja** [comment]
@davidmooreppf https://github.com/davidmooreppf,

No luck in filling out Miami...

Going to submit Q's to CM's in cities w/ decent coverage:

Charlotte, Cincinnati, Houston, Kansas city
