### ISSUE TITLE
"Change" city function error

### ISSUE THREAD

**Issue by maryamgunja** [opengovernment/askthem-legacy#402]
@davidmooreppf 

City viewing was distorted and I was unable to select "Change" & the pop-up window didn't show up. I experienced this problem with all states (not just VA), but the problem was only temporary....

http://www.askthem.io/va

![screen shot 2014-04-04 at 4 54 15 pm](https://cloud.githubusercontent.com/assets/5739030/2620259/75bcd32c-bc3b-11e3-8eb6-494ddde79a73.png)

**Comment by maryamgunja** [comment]
whoops, I'm still experiencing this problem:

http://www.askthem.io/tx-houston#

![screen shot 2014-04-04 at 5 01 04 pm](https://cloud.githubusercontent.com/assets/5739030/2620314/43d4efba-bc3c-11e3-9a9b-00e3a4be5468.png)

**Comment by davidmooreppf** [comment]
Yeah, Chrome has all sorts of odd behavior around this now. 

Initially the "change" link was same size as city name and parallel with it. 

On a reload of /tx, "change" was displaying correctly, and opens the modal, but the modal is unresponsive and can't be closed, and keeps the browser window frozen & foregrounded. 

https://www.dropbox.com/s/8mrhfrkzers45ya/Screenshot%202014-04-04%2017.13.10.png

... then I checked in Safari and it worked as expected. 

Checked back in Chrome and the "change" link is big again, and parallel - but allows clicks ::

https://www.dropbox.com/s/yfgd6ayfj9b0h74/Screenshot%202014-04-04%2017.16.27.png

... and now, checking again in Chrome, all working as expected.

**Comment by walter** [comment]
Yeah, it is definitely strange. Looking into it.

**Comment by walter** [comment]
I am experiencing the problem with the change not being placed correctly in Safari as well as chrome.

**Comment by maryamgunja** [comment]
Same here...

**Comment by walter** [comment]
I think this may have been due to reintroduction of an app server (had 2, reintroduced a 3rd) that needed its css cache updated.

When I did a deploy it updated all the app servers' css caches and I think the problem is now gone.

@maryamgunja, @davidmooreppf please confirm that this is showing up as expected for you. Reopen if not.

Note that this is separate from opengovernment/askthem-admin/issues/34 which is still occurring.
