### ISSUE TITLE
create FAQ page

### ISSUE THREAD

**Issue by derekeder** [opengovernment/askthem-legacy#41]
This page is referenced in the email sent out when a new question is posted (#19). Sounds like it should include info 'For more info about how to gather support for your question'

@davidmooreppf content?

Requirements:
- located at /faq
- linked to in question_posted email

**Comment by acacheung** [comment]
@davidmooreppf edit content at view/pages/faq.html.erb

**Comment by walter** [comment]
The copy looks like it should be derived from #194, https://docs.google.com/document/d/1oA552J5GFOo9I6fAUoCWtzAyjnEJqjKykpqEZkV1Ixw/edit#.

**Comment by walter** [comment]
Related, #39, #40.

**Comment by walter** [comment]
app/views/shared/faq.html.erb in place with copy, but needs serious styling!

**Comment by walter** [comment]
@acacheung styles should also be useful for #40 & #39.

**Comment by acacheung** [comment]
![screen shot 2013-12-19 at 5 16 15 pm](https://f.cloud.github.com/assets/1054686/1786811/33fe2046-68fb-11e3-82ce-9a31a4dbacb3.png)
