### ISSUE TITLE
Add images for VA Senators

### ISSUE THREAD

**Issue by maryamgunja** [opengovernment/askthem-legacy#411]
Timothy Kaine 
http://www.askthem.io/va/people/K000384
http://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Tim_Kaine%2C_official_113th_Congress_photo_portrait.jpg/220px-Tim_Kaine%2C_official_113th_Congress_photo_portrait.jpg

John A. Cosgrove 
http://www.askthem.io/va/people/VAL000177
http://dela.state.va.us/dela/MemBios.nsf/a2f5951900d28c0d8525738a00664b71/e27f24fd1759af2685257535005773f3/Photo/0.84?OpenElement&FieldElemFormat=jpg\

Bryce E. Reeves 
http://www.askthem.io/va/people/VAL000153
http://apps.lis.virginia.gov/senatepics/Reeves.jpg

**Comment by walter** [comment]
Cosgrove and Reeves are done.

For Kaine, he's federal, and I'm going to cover him with the work I do on Cory Booker soon.
