### ISSUE TITLE
issue w/ old session? 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#417]
Logged-in to my admin acc't on Chrome, this morning I'm noticing the "We're sorry" error when I try to load AskThem pages. 

In a fresh browser window, site works fine. And I can login fine to my david@askthem.io acc't. 

Everything works fine in a different browser, Safari. cc @maryamgunja

**Comment by maryamgunja** [comment]
I'm logged in as admin on chrome. I'm not experiencing "we're sorry" error, but askthem pages won't load... All works fine in Safari and Firefox...

@davidmooreppf

**Comment by walter** [comment]
I just ran a deploy to fix an earlier problem. Could you both try again, please?

**Comment by maryamgunja** [comment]
Loading for me now, thanks.

**Comment by davidmooreppf** [comment]
Up late, Walter! My Chrome sessions still won't load in the same browser as was logged-in. But new browser still works fine.

I can quit Chrome or I can capture Console if you prefer.

**Comment by walter** [comment]
@davidmooreppf I think you'll need to clear out your cookies for askthem.io in Chrome.

See this article:

http://www.tech-recipes.com/rx/3016/google_chrome_how_to_delete_individual_cookies/

**Comment by davidmooreppf** [comment]
Ha cool, wasn't thrown off, just mentioning in case it was useful for other users.
