### ISSUE TITLE
Internet slowdown day modal

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#418]
Paste into head, pls. -- for tmw's action, which starts at midnight tonight - but you can activate it whenever ::

< script src="//widget.battleforthenet.com/widget.min.js" async></script >

https://www.battleforthenet.com/sept10th/

**Comment by walter** [comment]
Hmm. In my development set up even after dismissing the modal, the askthem doesn't load.

I'm going to go ahead and deploy it in case it doesn't like a development env and test it on the live site. However, I may roll it back if it's not working there.

**Comment by walter** [comment]
Deployed. I changed it to the footer and that allowed the content to be present when the modal is dismissed.
