### ISSUE TITLE
Homepage blurbs not being set as default

### ISSUE THREAD

**Issue by walter** [opengovernment/askthem-legacy#419]
Now that we have individual page blurbs with a target_url attribute, blurbs created from /blurbs need to have target_url set to be the homepage, i.e. /.

Update so that the default target_url is "/".

**Comment by maryamgunja** [comment]
From askthem.io/blurbs, I tried to add a hyperlink & wasn't successful. Now I'm unable to edit the first blurb...

![screen shot 2014-11-05 at 12 20 13 pm](https://cloud.githubusercontent.com/assets/5739030/4922215/29331d9e-6510-11e4-84d6-4b4482e8d386.png)

**Comment by walter** [comment]
Got a temporary fix in place. More to come.

The headline and body for blurbs are raw HTML. They don't have any safeguards. If there is a problem is can mess up the rest of the homepage, etc. It's good to triple check it.

**Comment by walter** [comment]
Ok, it looks like you wanted to create a link to /candidates. What I've done is split the headline to be the following:

```
During Louisiana's Senate Runoff,
```

and the body to be the following HTML:

``` html
<a href=\"http://www.askthem.io/candidates\">ask Incumbent Mary Landrieu & Challenger Bill Cassidy Anything!</a>
```

That way "ask Incumbent..." becomes a link to /candidates.

There were a couple problems with what you had before.
1. <a href=\"http://www.askthem.io/candidates> was missing the closing \" and that left everything else on the page it was displayed on as a link up until the next double quote. That through off links and styling.
2. There was no value in the link tag which meant it wouldn't display at all.

That is why I may the second part of the sentence the body and wrapped in the HTML link.

Hope that does the trick!

**Comment by walter** [comment]
I bumped up the font size for the body by putting in an inline style.
