### ISSUE TITLE
when logging in or after signup, should redirect you to proper page

### ISSUE THREAD

**Issue by derekeder** [opengovernment/askthem-legacy#42]
After logging in I always get kicked back to the home page.

Some standard practices:
- After sign in: redirect me to the last page I was on
- After sign up: redirect me to my state questions page based on my address (for example - http://oglocal.herokuapp.com/il/questions)

**Comment by walter** [comment]
http://eureka.ykyuen.info/2011/03/10/rails-redirect-previous-page-after-devise-sign-in/ 

Basically what is missing is that resource_return_to cannot find a stored location (aka a session[:return_to]) in the session.

I'm actually surprised that Devise doesn't do this for us. Will do more digging.
