### ISSUE TITLE
on /map, some city names show Q's, but none listed in /questions

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#421]
On :: 

http://www.askthem.io/map

... city questions, major cities do indeed link to Q content as expected :: 

http://www.askthem.io/ny-brooklyn/questions/recent

http://www.askthem.io/il-chicago/questions/recent

(24 listed, I count 21 Q's there) 

... but some smaller cities, the data shows Q's, but none on /questions or /questions/recent :: 

El Paso - 2 listed :: http://www.askthem.io/tx-el-paso/questions/recent

Columbus - 3 :: http://www.askthem.io/oh-columbus/questions/recent

Tulsa - 1 listed :: http://www.askthem.io/ok-tulsa/questions/recent

SF - 6 listed :: http://www.askthem.io/ca-county-san-francisco/questions/recent

... maybe catching other state Q's?

**Comment by walter** [comment]
Fixed and deployed and checked that it's working. All good now.
