### ISSUE TITLE
name alignment with profile photos got a little wonky

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#426]
Hm, seems a little glitch where names of question recipients got bumped down and to the right of their photo image, whereas before I think they were on same level

E.g. on question listing pages :: 

http://www.askthem.io/us/questions/recent

http://www.askthem.io/ny-new-york/questions

![trump_name](https://cloud.githubusercontent.com/assets/116819/9915873/8dab4cf0-5c87-11e5-9736-67617e2a93d2.png)

**Comment by walter** [comment]
Yeah, I'm seeing the weird alignment in Chrome and Firefox, but not in Safari. So you can see the old style in Safari for comparison.

Will take a look.

**Comment by walter** [comment]
Hmm. I'm wondering if we should just wait on this for a bit. Seems like it might be a rendering bug introduced by the browser and might just be fixed for us if we wait.

How much does this bug you?

**Comment by davidmooreppf** [comment]
Oh, not a big issue. Just noting. I'll leave this open for now.
