### ISSUE TITLE
old verified Twitter avatars not displaying as expected? 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#429]
Not urgent, just if you have bandwidth sometime this week. No need to drop anything. 

Error with image on Lessig page in both Chrome & Safari (though different errors) - his person was created on AskThem early last year for launch so maybe something changed:

http://www.askthem.io/people/52e93987f92ea1709d00000c

... Hillary's page has a blank avatar, but her Twitter image would be preferable to display there of course - also created early, maybe I need to create her page again :: 

http://www.askthem.io/people/5307853dec8d83040f000001

... but this institution's image is coming through OK, hmm, I just created this ::

http://www.askthem.io/questions/561bfd42d535cf0d1800004d

... I'd try to create them again, or try with more new Twitter accounts, but I'm stepping away for a second. So just starting thought on this, somewhat as a reminder to myself. 

These are generally working, the old Twitter pages created back here ::

http://www.participatorypolitics.org/qa-for-every-public-official-with-a-verified-twitter-account-on-askthem/

... so maybe just Lessig?

**Comment by walter** [comment]
Just off the top of my head... if the Twitter person changes their image on Twitter, our local avatar becomes out of date and has to be manually updated. Just a downside of relying on Twitter for the avatars unfortunately.

So later this week I'll take a look and update their avatars manually. Might be worth going through http://www.askthem.io/people and collecting the URLs for the people that have bad avatars and list them here. Also if you have an alternative avatar image URL list that as well. Twitter's avatars are low quality and as I said can change, so alternatives are good.

If you provide those two things, I should be able to update them pretty quickly. Remind me Saturday if I forget.

**Comment by davidmooreppf** [comment]
Makes total sense. Will do, thx.
