### ISSUE TITLE
HTML for verified responders to answer questions on their own pages

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#45]
Re: 9 on G-doc dev roadmap, implement design for verified responders / responses into HTML to be able to answer questions on a question page. cc @walter

**Comment by walter** [comment]
Also a bit of UI tie-in for #22 on the person's page (if they are the person) if they have questions that are have met their threshold and are waiting to be answered.

I.e. this scenario:
- user asks person a question
- other users sign the question and it reach its threshold
- recipient person is sent notification of question
- person views their person page and can see that there is a question awaiting an answer with link to question (where they can answer it as per this issue)

The above should be able to handle more than one question awaiting an answer as well as "plain" questions (not yet at threshold, basically what we have now wherever we show questions).

**Comment by walter** [comment]
@acacheung is this what you talking about handing over?

In future, add issue number (e.g. #45) to bottom of commit messages to have them show up under issue. Even when not closing them.

**Comment by acacheung** [comment]
@walter yes, sorry about that. will remember for the future

**Comment by walter** [comment]
Making sure that @derekeder and @evz see that this has been done.

**Comment by walter** [comment]
@derekeder & @evz if you have what you need which I suspect is the case.

**Comment by derekeder** [comment]
@walter yup I think we're ready to dive in to this one.

**Comment by walter** [comment]
Ok, the HTML for this is actually what is causing our failing test. As @evz there are two #new_user forms on the page and the test fills out the wrong one as we result.

Not a big deal, but it led me to take a closer look at the HTML for this and I have a couple points of feedback that I think @derekeder and @evz can handle in their work.
- for now, we'll wait and see if we need it in the future, let's drop the new user creation as a part of the answer form and wrap the form in logic that only shows it to a verified responder for the question (i.e. a user account that has an identity for the person that is the same as question.person as I emailed about)
- the answer form should appear above the comments!

Until you guys get into the work, I'm going to disambiguate test to use 'within ".signup" do' to fill out the correct form.

**Comment by derekeder** [comment]
Closed by #72
