### ISSUE TITLE
edits to question-and-answer detail page

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#47]
SLIDE 14 (“Question and Response Page”) on :: 

https://www.dropbox.com/s/tv22bmn22cpqpzx/OpenGoverment-Product-and-Strategy.pdf

smaller changes

On the side of this slide, let’s say 437 supporters with 139 needed.
change councilman to senator

change tag a, tag b, tag c to agriculture, farm bill, wyoming

change list of supporters to different random names, not anyone famous, random photos  (David Owens, Julia Doran, Brittany Shaw, Mariko Ha, Juliana Rincon, Raj Indra, Nasser Saleh, Isadora Roski)

US Senator Mike Enzi
Q: What are your accomplishments and stances related to Wyoming farmers?

A: I have been working for Wyoming’s ranchers and farmers since before I came to the Senate. We scored major victories in 2008 with the passage of the new Farm Bill. This is the first Farm Bill to contain a specific livestock title to promote competition and fairness in agricultural markets. It included language to implement Country of Origin Labeling (COOL). COOL provides consumers with important information about the source of food and allows our livestock producers, who produce the highest quality meats in the world, to remain competitive in a growing global marketplace.

The 2012 drought has hurt many crops and threatens yields in 2013. I have worked with my colleagues in the Senate to ensure that producers have tools available to them to help mitigate risk when it comes to adverse weather and other agricultural disasters.  

I was an original cosponsor of legislation that would lift a ban on interstate commerce by the U.S. Department of Agriculture's Food Safety and Inspection Service (FSIS) and ensure that meat that has been state-tested can be sold across state lines. We already allow meat from foreign countries to be sold in our nation based on a promise that those foreign nations’ standards are the same as ours. This law has prevented Wyoming producers from selling their beef or lamb across state lines in the past, even when our state standards are stronger than federal standards. 

Wyoming’s livestock producers can compete in a fair market, but they are at a disadvantage now to the large meat packers.  We still need to amend the Packers and Stockyards Act passed in 1921 to prohibit continually growing practices that allow meatpackers to manipulate cattle prices.

The 2012 Farm Bill also includes language that helps the nation’s investment in animal health programs by making brucellosis and other livestock diseases a high-priority research initiative in the U.S. Department of Agriculture. 

For conservation, we’ve made significant improvements to the incentives and financial assistance offered to landowners who use the Environmental Quality Incentives and Conservation Reserve programs. I am especially pleased to see that the program offers additional assistance to beginning farmers and ranchers since we all know that one of the greatest challenges to the future of agriculture is attracting young people into the industry. 

Wyoming’s farmers and ranchers are some of the best caretakers of the land and help preserve critical wildlife habitat.  We must continue to provide voluntary incentives so Wyoming’s open space can be protected in perpetuity.  

I have fought to open and keep open U.S. agricultural markets to other countries including Korea and Japan. As a member of the Senate Finance Committee, I will continue to work to ensure that the United States continues to improve its market share for Wyoming beef overseas. 

I am also the sponsor of a bill the U.S. Senate passed for the ninth year in a row that honors the late Senator Craig Thomas and cowboys all over the nation. The bill designated July 27, 2013 as “National Day of the Cowboy.”

**Comment by kidfribble** [comment]
![slide14](https://f.cloud.github.com/assets/241320/958403/8324c712-0463-11e3-98f3-a8c70d215e9d.jpg)

I believe this is what we're looking for - let me know if otherwise!

**Comment by davidmooreppf** [comment]
Totally almost there, two small tweaks if you have it open ::

a) change tag a, tag b, tag c to agriculture, farm bill, wyoming

b) Can you add some line breaks in the answer copy, to make it more readable? 

... if you don't have the image open anymore, it's not imperative, this is workable.

**Comment by kidfribble** [comment]
We had actually removed tags entirely from the site, I thought. I can readd them.

For line breaks I didn't add because I noted that much of that space is being cropped in the slide, so it wouldn't be visible. I'll add em anyway.

**Comment by kidfribble** [comment]
![slide14](https://f.cloud.github.com/assets/241320/958623/035b8d8e-046a-11e3-9dc0-c07e4935808d.jpg)

Round two!
