### ISSUE TITLE
edits to user dashboard slide

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#48]
Slide 29 (“User Dashboard”)

https://www.dropbox.com/s/tv22bmn22cpqpzx/OpenGoverment-Product-and-Strategy.pdf

Change “Your Representatives” to:

Brian J. O’Neill, Philly City Council, 10th District (R)
Michael Nutter, Philly Mayor, (D)
State Rep Brian Sims (D) District 182
State Sen Lawrence M. Farnese Jr. (D) District 1
US Rep Chaka Fattah, (PA 2nd district) (D) 

Select “Questions You’ve Supported” instead of “Question’s You’ve Posted”

Replace the three questions we have on the slide now with ::

US Senator Lisa Murkowski (R)
Q: What do you see as your biggest accomplishments since you’ve been in the Senate?  
How do your accomplishments compare to your campaign promises?  

(712 supporters, progress bar should be nearly full, 95% complete, question by Lorena Andrus)

US Rep John Delaney (D)
Q: Will you support H.R.1114, the End Political Kickbacks Act of 2013?  
The bill prohibits for-profit recipients of federal funds from making contributions to any political party, committee, or candidate for public office, or to any person for any political purpose or use.  

(635 supporters, progress bar should be 85% full, question by Nelson Gresham)

US Rep Jamie Herrera Buetler (R)
Q: Do you support tying student loan interest rates to financial markets?  If not, what would you do to lower student loan interest rates?

(2134 supporters, progress bar completely full, question by George McPeak)

**Comment by kidfribble** [comment]
![dashboard_round1_1c](https://f.cloud.github.com/assets/241320/958591/a3a1164e-0468-11e3-9a10-32f579eacea7.jpg)

Again, let me know if we've got any adjustments we need to make to these.
