### ISSUE TITLE
Update Devise to latest version of gem

### ISSUE THREAD

**Issue by walter** [opengovernment/askthem-legacy#49]
See new version announcement:

http://blog.plataformatec.com.br/2013/08/devise-3-1-now-with-more-secure-defaults/

It makes sense to try to do this before launch so that the new ways of handling confirmed users are in place from the start.

**Comment by walter** [comment]
3.1 is only in release candidate at this point. Use 3.0.2 as current stable release.

**Comment by walter** [comment]
3.0.2 breaks things and so far is hard to debug. Holding at 2.2.6 for the moment.

**Comment by derekeder** [comment]
Looks like there's a bit of a difference in registrations_controller#create
that I overrode

https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L12

On Thu, Aug 15, 2013 at 6:32 PM, Walter McGinnis
notifications@github.comwrote:

> 3.0.2 breaks things and so far is hard to debug. Holding at 2.2.6 for the
> moment.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/opengovernment/opengovernment-app/issues/49#issuecomment-22738463
> .

## 

Derek Eder
@derekeder https://twitter.com/#!/derekeder
derekeder.com
derek.eder@gmail.com

**Comment by walter** [comment]
Yeah, that's probably it. Thanks for digging that up. I may take a stab at bumping it up and see if that does the trick.

**Comment by walter** [comment]
Yep, making the change (passing params as method call) here did the trick:

https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L13

So 3.0.2 will be coming with other gem updates when I merge in some other work.
