### ISSUE TITLE
Splash page issues

### ISSUE THREAD

**Issue by rchekaluk** [opengovernment/askthem-legacy#50]
- Wrong pictures for Advisory Council
- NewsChallenge proposal should be a live link
- #39 
- sign up here: (field)

**Comment by rchekaluk** [comment]
- Notify Me form has no id or name for email input element

**Comment by rchekaluk** [comment]
- OpenGovernment logo has moved to righthand side.

**Comment by acacheung** [comment]
Can I get a screenshot that the logo has moved to the righthand side? I don't seem to be getting the same thing over  here.

**Comment by rchekaluk** [comment]
screen shot is at http://postimg.org/image/4akes70br/
Firefox 23.0 Ubuntu Linux

**Comment by davidmooreppf** [comment]
Quick tweaks to : http://askthem.io/splash.html#
1. Substitute new AskThem logotype from Logan & Steve for OpenGovernment logo in upper-left. 
2. Add in an optional zip-code box on signup page for individuals and elected officials. The "notify me" button can be on the second line with that zip code lookup. 
3. Add in a third type of entity above the text field: Organization. Has two fields: Name of Org., Email and Zip. 
4. Move up the "about" jump-down to be more prominent. It's lovely as it is designed, but too miss-able.

**Comment by walter** [comment]
@acacheung some further work as mentioned in IRC.
- About and Get Notified links not working (i.e. clicking doesn't do anything)
- clicking "elected official" or "individual" should change which is "selected" in the sense that the arrow indicator and the text opacity should change accordingly

@rchekaluk, who is working on https://github.com/opengovernment/ops/issues/14, is then going to adjust the HTML form to submit to where it needs to. However, the transition between the "elected official" or "individual" forms will also need to change a form parameter (aka a hidden field value).

If y'all can coordinate to get this going tomorrow that would be great.

**Comment by acacheung** [comment]
@walter got everything looking right, but the form isn't real yet. Let me know if you have any questions!

**Comment by walter** [comment]
Making sure @rchekaluk sees this.

@rchekaluk, do you need anything more to get the form working?

**Comment by walter** [comment]
Making sure @rchekaluk sees this.

@rchekaluk, do you need anything more to get the form working?

**Comment by rchekaluk** [comment]
Notify Me button does not trigger form when page is scrolled to the top. You have to scroll page down a tad (the button goes gray) to make it live.

**Comment by rchekaluk** [comment]
Need this pull request or equivalent: https://github.com/opengovernment/opengovernment-app/pull/65

**Comment by rchekaluk** [comment]
I'd suggest displaying "District Zipcode" for elected officials (if that's what you're looking for). 

Let me know if that's not what you're looking for, because I'll tag the database differently in that case.

**Comment by rchekaluk** [comment]
Clicking on Elected Official the first time, the pointer spontaneously moves back to Individual when attempting to enter email address.

**Comment by walter** [comment]
Works as expected in Safari and I would bet Chrome.

Are you using Firefox? Would be good to know the browser for debugging.

**Comment by rchekaluk** [comment]
Yes, Firefox 23.0.
Mozilla Firefox for Ubuntu.

**Comment by walter** [comment]
I've recreated the issue with Firefox 21 on a Mac (clicking Elected Official a second time made it "take"), but then updated to 23.0.1 and the issue went away.

Looks to be a bug in versions of Firefox before 23.0.1. Since there is an upgrade path I don't think it is worth addressing with a workaround.

**Comment by rchekaluk** [comment]
I do want to point out that in this particular use case (quickly capturing contact information, splash page only, for the limited timeframe that it constitutes the site), no users are going to be aware of an issue or upgrade FF. Consequently we should be aware that there's a risk that CRM may be populated with some elected officials and/or organizations incorrectly labeled as "Individual".

**Comment by walter** [comment]
Some ideas:
- capture user agent in CRM
- review logs of splash page for user agent
- serve a different form to user agent with issue

It's worth testing the page with IE as well.

**Comment by davidmooreppf** [comment]
Raised some of these issues in new #82

**Comment by walter** [comment]
Is there anything remaining on this? 

Since this issue has become long and convoluted, I would say that this issue should be closed and new specific issues should be opened.

@davidmooreppf I'll leave closing this to you.
