### ISSUE TITLE
When creating a question in Firefox, can't get past the select a recipient stage

### ISSUE THREAD

**Issue by evz** [opengovernment/askthem-legacy#54]
Despite having filled out the form properly and selected my recipient, Firefox always thinks I haven't chosen a recipient. Each time I hit the "Next" button, it duplicates the error message (See screen shot). This same functionality works for me in Chrome and Safari on OS X.

![screen shot 2013-08-16 at 3 46 33 pm](https://f.cloud.github.com/assets/551491/978143/25305fb4-06b5-11e3-8356-0bbb7fd9a4c5.png)

**Comment by walter** [comment]
Good catch. Is this something up your alley to debug?

**Comment by derekeder** [comment]
sure, @evz and will take a look

**Comment by evz** [comment]
I think I found the [offending line](https://github.com/opengovernment/opengovernment-app/blob/master/app/assets/javascripts/questions.js.coffee#L210) of coffee script. 

Firebug reports that length as 0 even when there is something selected:

![screen shot 2013-08-16 at 8 46 35 pm](https://f.cloud.github.com/assets/551491/979135/01561046-06df-11e3-9a49-52d356425446.png)

Webkit (in this case Safari) gets a value there:

![screen shot 2013-08-16 at 8 46 57 pm](https://f.cloud.github.com/assets/551491/979136/22e909c0-06df-11e3-8cb1-d5e212936a88.png)

That's about as far as I can take this tonight (brain is running out of juice).

**Comment by evz** [comment]
So, I'm pretty sure I came up with a solution for the [bad jquery selector](https://github.com/opengovernment/opengovernment-app/blob/master/app/assets/javascripts/questions.js.coffee#L210):

``` coffeescript
$('input[name="question[person_id]"][checked="checked"]').length is 0
```

Subtle difference but it seems to make at least Firefox happy. However, now that I'm past that step, and I complete the process of filling out the question, I end up back at the beginning, only with the old layout:

![screen shot 2013-08-17 at 8 49 38 am](https://f.cloud.github.com/assets/551491/981106/b98a2782-0744-11e3-811f-616bc42c3807.png)

If I go through the process again, I get all the older layouts (only the forms are already filled out with the stuff I put in earlier) and then when I hit the "Publish" button again, I end up back at the beginning again. This is only true for me in Firefox. Safari, Chrome, etc perform as expected.

Anyways, I'll probably have a bit of time in a few hours to take a deeper look here. If someone @derekeder or @walter happens to get to it before me, I won't be offended.

**Comment by walter** [comment]
So a few things are happening here. Let's step through them.
- see #59 about the old layout popping up (and the lack of informative flash message)
- even though your solution allows Firefox to pass client side validation (recipient shouldn't be blank) it actually preventing client side validation from doing its job... we should not allow recipient to be blank!

```
$('input[name="question[person_id]"][checked="checked"]').length is 0
```

Shouldn't this be length is 1? Basically the user should not be able to proceed unless they do have a checked input.

I'm a tad confused about this actually as it looks to contradict "things are working in Safari and Chrome".

What it boils down to is that question[person_id] has to have a person's id passed to questions#create or server side validation will fail. If your solution has the side effect of unsetting a value for question[person_id], it's not complete.

We may need to backburner this. I don't want to eat too much more or your limited time on a browser compatibility issue.

**Comment by evz** [comment]
Actually, if that line evaluates as true, the `personError` function is triggered and the `valid` flag is made false so the form won't submit (that's why it wasn't working in Firefox because that line was always evaluating as true in Firefox). 

I'll back off on this stuff for now and we can focus on other stuff. I'll just go ahead and make sure I'm doing my dev work in Chrome/Safari so it actually works for me.

**Comment by walter** [comment]
One thing we could have tried is running questions_spec with selenium under Firefox as Capybara's driver. That would, in theory, recreate the issue in probably a number of tests.

**Comment by walter** [comment]
@evz, worth double checking this is still an issue.

**Comment by evz** [comment]
Yup, still appears to be an issue (assuming oglocal is up to date)

![screen shot 2013-09-12 at 9 06 49 am](https://f.cloud.github.com/assets/551491/1131085/9db7e20e-1bb4-11e3-9288-c4e69313c0fd.png)

**Comment by davidmooreppf** [comment]
Yep, still a bug in FF. As we know, haha.

**Comment by walter** [comment]
23.0.1 still has issue, as does newest 25.0.1. @acacheung is this something that dockyard could help sort out?

**Comment by maryamgunja** [comment]
@davidmooreppf 

Experiencing same problem when looking up twitter account on Firefox:
![screen shot 2014-01-22 at 11 28 20 am](https://f.cloud.github.com/assets/5739030/1975834/869712a8-8382-11e3-9b50-41b2ff88d944.png)

**Comment by walter** [comment]
I've already started looking into all of the issues related to recipients. I'll keep you posted.
