### ISSUE TITLE
signing on to my own question?

### ISSUE THREAD

**Issue by derekeder** [opengovernment/askthem-legacy#55]
When a new question is posted, should the person who asked it automatically be signed on to it? Right now, I can post a new question, and then sign on to it as a separate action. 

Here's an example: http://oglocal.herokuapp.com/il/questions/520e9587e78e4bbf31000002

**Comment by walter** [comment]
@davidmooreppf @acacheung,

What do you think is the expectation?

**Comment by davidmooreppf** [comment]
Good Q - Change does not have the creator as the first signature, so let's follow that practice now. So no, not automatically signed.

**Comment by derekeder** [comment]
Ok - sounds like the desired behavior is what we currently have implemented. Closing.
