### ISSUE TITLE
No way to sign in during question creation process

### ISSUE THREAD

**Issue by evz** [opengovernment/askthem-legacy#58]
In the older layouts, there was a "Sign in" link and form on the right side of the page during the question creation process. In the newer process if you're not signed in and you get to the third step (the "Your profile" step) and already have an account, you basically have to go back to the home page, login and then start the process over again. I'd say that's a bit less than optimal. Since the form is intelligent enough to know that your email is already taken, could it just sign you in? (since you're putting a password, too) Or maybe you could either sign in or create a new account at that stage?

**Comment by walter** [comment]
#96, when done, should satisfy this. Closing this.
