### ISSUE TITLE
Email or tweet reminder of unanswered question to recipient after a week

### ISSUE THREAD

**Issue by derekeder** [opengovernment/askthem-legacy#61]
If no response in a week to a question that has reached its threshold, send reminder email. 

This same job could also be used to generate a follow-up tweet once #60 is implemented.

Enhancements after launch will include more specific reminders to staffpeople and administrative dashboards for verified responders & elected officials. 

Relates to #21

**Comment by walter** [comment]
I'm hoping we'll be able to notify staff people for launch, but yeah, a separate issue for it and admin dashboard post launch.
