### ISSUE TITLE
tweak to splash page re: organizations

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#66]
Miscommunication on my part - on splash :: http://askthem.io/

... Organization should be a header category to the right of "Elected official". Not a field below. 

Under Organization, still only two fields: email & zip-code, as current. No change there.

**Comment by acacheung** [comment]
oops! forgot to attach the commit on to here. Here's the sha commit 92e26a3cd9208d2a69dd98bc44f62ecae74e8f06
