### ISSUE TITLE
tweaks to first page of /questions/new 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#7]
On http://oglocal.herokuapp.com/ny/questions/new, I think we should try :: 

a) Default to address lookup instead of Twitter field. I think most people won't know how to search by twitter name. 

b) Change "Home Address" to "Enter Your Home Address". Change "Where You Live..." to "We'll find and display your elected officials".  

c) Get rid of "address" above address text field. If it's in text field, that's sufficient, don't you think? Input welcome on this. 
### 

re: Twitter, we'll see where we stand with the lookup of verified accounts and / or name lookup.

**Comment by kidfribble** [comment]
a) probably true

b) check

c) I would either go all with or all without. I think in this short form it's possible that all the inputs placeholder text can properly ask for the content without difficulty, so **I'm for all inputs not having labels**. If this were a long form I would worry about users forgetting what the field was for (it can happen even after they've entered the requested information, sadly).

**Comment by davidmooreppf** [comment]
c) yes, all without. All fields without.

**Comment by walter** [comment]
Closing this as other work has superseded it.
