### ISSUE TITLE
User profile should reflect live data for user

### ISSUE THREAD

**Issue by walter** [opengovernment/askthem-legacy#71]
Currently a user's profile page is mostly design mock up HTML. Tie-in live data in accordance with mockup.

**Comment by walter** [comment]
@evz if you get blocked on any other issue, this is a good one to tackle as backup.

**Comment by walter** [comment]
Here's an example from the staging site (may break in the future):

http://oglocal.herokuapp.com/users/5205100e9a43d51b97000003

**Comment by davidmooreppf** [comment]
Over to you to close, if done, Walter.

**Comment by walter** [comment]
Work completed in #125.
