### ISSUE TITLE
Staff member can get contact info csv for people in database

### ISSUE THREAD

**Issue by walter** [opengovernment/askthem-legacy#76]
As a logged in staff member (for now, user.add_role :staff_member from console to grant this role), can request /contact_info.csv to get csv of state legislators and council members by default.

To limit to one or more jurisdictions, use limit_to_jurisdictions=pa,ma,ny etc. as query parameter. To get FederalLegislators use type=FederalLegislators.

**Comment by davidmooreppf** [comment]
Just need a helping hand with the console part of this. In meantime, can you send the .csv to me on Dropbox or even just over email?

**Comment by walter** [comment]
So here's the process:
- potential staff member signs up to the site
- let me know
- i'll do the console bit for confirming them and making them a staff member
- person logs into site and is good to view the page /contact_info page

I'm assuming you only want to do this for one or two user accounts and so doing it manually is ok.

**Comment by walter** [comment]
Closing this as an issue. There is still a problem with timeouts on staging site, but that's an ops specific deal.
