### ISSUE TITLE
design on "are you [elected official]" link on question pages

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#77]
Following up on #72, refinement to "first state" as described by @evz -- 

-- currently the button is too centrally placed, "are you Elected Official? Sign up here to answer." 

-- goal is instead to have it as a smaller link, perhaps on right-hand sidebar. All totally cool, there wasn't a layout or wireframe or spec for this, just figuring it out now. So all OK.

Over to @acacheung to implement next week Tuesday-Friday! Can chat more. cc @walter.

**Comment by walter** [comment]
A note encouraging elected officials to sign up... rather than giving them an answer form combined with sign up.

**Comment by walter** [comment]
Perhaps wait a little on this until #72 is merged in.

**Comment by walter** [comment]
Also, I think we should reuse whatever design widget we come up with (thinking tooltip style ala sign up forms "your email address will remain private") on person's detail page if they are not already verified.

My feeling is that in both cases (question detail page, person detail page) the "are you x? sign up, get verified, and answer this question." tooltip should be by the avatar.

Which reminds me, do we need an avatar by the recipient's name on the question detail page by "To:", not just the name?

**Comment by walter** [comment]
#72 merged to master. @davidmooreppf, take a look at the last screenshot in that issue. Is that "good enough" now that it isn't a button or do we want to keep working on wording/design here?
