### ISSUE TITLE
background color palette

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#78]
We can loop in Logan & Steve if they like - my team would like to try approx. three different color palette backgrounds on the staging site, as the blue-gray mix now is considered a bit deadening. We are wondering if a more solid background page color will be more exciting. 

Can we please try :: 
- more blue 
- more gray 
- white (as on Change.org) 

... we're not insistent on making a change, but would like to see options and it's worth time on sample pages. Sorry for the broad description here; I should go into ColourLovers and pick some samples, but running into the office now. Can chat voice later.

**Comment by acacheung** [comment]
![current](https://f.cloud.github.com/assets/1054686/1081215/03ce769a-1573-11e3-8772-24e87fb57577.png)
![gray](https://f.cloud.github.com/assets/1054686/1081216/066e163a-1573-11e3-9ce5-6d707a0a34d8.png)
![lighter-blue](https://f.cloud.github.com/assets/1054686/1081217/08761220-1573-11e3-9efc-809067f3646f.png)

@davidmooreppf  I'm liking this lighter blue, which is taken from the splash page background color. What do you think?

**Comment by acacheung** [comment]
@davidmooreppf my favorite so far
![blue-gray](https://f.cloud.github.com/assets/1054686/1081760/ed857cf4-157b-11e3-8458-ca9082069fd1.png)

**Comment by davidmooreppf** [comment]
Yeah the one directly above is nice, maybe more chill than brighter blue. Do any other background ideas come to mind? I don't know, maybe try ::  

http://www.colourlovers.com/color/02779E/Smooth_Sailing

http://www.colourlovers.com/color/1693A5/dutch_teal

... I don't know for certain. If some other options don't look nice, we can use the blue above for now. 

Have additional questions re: the header design - I know this is a lot of tweaking, so let me know if you're OK with this :: 
- can we try different colors on the logo to make it livelier? The gray type isn't seeming exciting to some of my test group.
- this may be overkill, with a brighter logo, but we're also open to trying a ribbon in the header to liven things up. 

... again, we can chat - if you don't want to fiddle with this design anymore, you don't have to, but we do want to pursue these tests. Thanks Amanda.

**Comment by davidmooreppf** [comment]
Starting new issue for logotype. Great work Amanda.
