### ISSUE TITLE
question listing page, change "read more" button back to "sign" 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#79]
On question listing pages ::: http://oglocal.herokuapp.com/ny/questions?type=Person

... please change "Read More" button back to "Sign". This is the action we want to signal users can take, and it's what Change does.

Clicking the button should take the visitor to the question detail page to enter her info and click the "sign" button again, as on Change.

cc @walter.

**Comment by acacheung** [comment]
Changing all "Read More" / "Sign On" buttons to "Sign". Is it cool if I update the tests to reflect this?

**Comment by walter** [comment]
Yes, please do.
