### ISSUE TITLE
add-in Twitter button to follow the creator of a question

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#8]
On pages for questions, e.g. ::

http://oglocal.herokuapp.com/ny/questions/51b7763e3be48a6507000003

... goal is to allow users to follow the Twtr acc't of the creator of the question/petition. This creates incentive to publish & share Q's. 

When in the user registration process should we allow a user to choose to attach a Twitter profile to her account? 

Should it just be on personal profile page, and prompted with an email asking them to flip the setting? 

Or should it be an option during standard user registration - to attach a Twtr acc't?

**Comment by kidfribble** [comment]
I would give the use the option to add it during registration as well as before a question is posted as an option to share via twitter (saving their twitter creds). In the future they would have a toggle for sharing on twitter which would default to false.

**Comment by walter** [comment]
I wonder if during the registration, i.e. #12 , it would be worth differentiating what is a private part of the user's profile and what is public. We should tie-in to that for Twitter handle.

**Comment by kidfribble** [comment]
@walter I think you're right about that. I would probably note things that are private, making it clear that all other things may not be.

**Comment by walter** [comment]
Closing in lieu of #238. I think that gives users the option to go to twitter and decide for themselves if they would like to follow the person.
