### ISSUE TITLE
nav changes - pull out page title and make nav options bigger

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#80]
Somewhat-significant UI change here - on federal/state pages, e.g. ::

http://oglocal.herokuapp.com/ny?type=FederalLegislator

... w/r/t navs ::

http://cl.ly/image/2z0w290l393r

... the problem is that the "New York Federal" & "New York State" links are too subtle. 

And also the page title, e.g. "Questions", is often a duplicate of sub-nav "Questions". Obvs. 

Let's try pulling out the dark blue page title "Questions", making the regional nav bigger & the sub-nav bigger, making both darker, and of course moving the "ask a question" button up to be parallel with the sub-nav. 

This will require re-naming "Overview" in the sub-nav, but @Walter and I can work that out. Amanda feel free to 'cc' Steve here if he has bandwidth to comment or disagree. Open to input.

**Comment by davidmooreppf** [comment]
ccin'g @Walter, as he may have to implement this first. 

OK problem with this suggestion, as Amanda & I discussed yesterday, is that some city names are long, and so if you're on an Overview page, e.g. ::

http://oglocal.herokuapp.com/ma

... you might not know what page you're on without the large title. Gov't entites have longer names, sometimes, obvs. 

So what if we moved "overview" to the top-most nav? 

In top-most nav, then, it would read: CT Federal Gov't / CT State Gov't / [CityNameInConnecticut] ... then depending on which one was highlighted, it would display "overview" to the right. 

The "overview" would show the two chambers of the leg. branch in question, as well as the exec. branch in state gov't, viz. the Governor. 

Sub-nav items need some finalizing on avail data, but to try it here :: 
- for federal, it could be Questions / People / Hot Bills / Issues. (This doesn't include Committees.) 
- For state, Questions / People / Bills / Issues. 
- For City, Questions / People / Meeting Agendas / Issues. 

... still tinkering but hitting comment now.

**Comment by acacheung** [comment]
@davidmooreppf 

Trying a couple things out. What do you think? This doesn't take into account much from your latest comment.
![questions-index-edits](https://f.cloud.github.com/assets/1054686/1083388/8d3fea60-1598-11e3-8bcf-d2ac15d8a640.png)

**Comment by davidmooreppf** [comment]
this may be in your notes Amanda - on pages :: http://oglocal.herokuapp.com/ny/questions?type=Person

...let's make region nav bigger - New York Federal & New York State & City. Make 'em bigger.

**Comment by acacheung** [comment]
@davidmooreppf what do you think about these sizes?
