### ISSUE TITLE
on question listing pages, make question titles more clickable

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#81]
On pages e.g. :: http://oglocal.herokuapp.com/ny/questions

... currently our feeling is that individual question titles seem more like static content and don't seem clickable to new visitors. 

Change is pretty close to us in design right now, w/ a hover highlight on petition title, so not sure what exactly to suggest - but can we experiment with, say, a hover-underline state? Open to ideas.

**Comment by acacheung** [comment]
Hover underline combined with the change in color seemed like a lot going on. Would you prefer the underline over the color change?

**Comment by davidmooreppf** [comment]
Yes let's try underline - thx for talking this out
