### ISSUE TITLE
splash page design finalization 9-3-13

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#82]
On :: http://askthem.io/splash.html#
1. Change page title in the Chrome to :: AskThem - question-and-answer and petitions with public figures 
2.  Cross Browser! Amanda, what IE testing capacity do you have? On IE 9.0.8, the gray type in the text fields is invisible & "Notify Me" button has a red outline and faint coloring. 

a) All seems fine in Chrome

b) Safari seems fine, the 'email' and 'zipcode' fields are a bit off in the text fields

c) In Firefox 22, formatting bug - the text fields are on top of each other. 
1. Signups - the confirmation page is dark text on a dark background in Chrome & Safari, but not in FF:: 
- OK, we added the individual a121381@drdrb.com.
  See you soon!

or :: 
- OK, we revised the existing entry to individual davidrussellmoore@yahoo.com. 
  See you soon!

I'll tweak that copy, but Amanda, let's see whether we can have the confirmation message display in lighter type, or in the sky, above the big background image. 
1. Speaking of big background image - are we certain that image is optimized for web? I checked on a previous version and it was a huge image file. Can we re-save that in Photoshop and display a smaller version? I can dive back into the CSS and try to find the background image (mountains etc.). 
2. Amanda, would appreciate your help with styling on the text at left - making bullets appear properly - I could play with this but not sure what's best. 
3. I need to add another name & image to the right-hand side advisory council, will do that shortly. 
4. Need to specify email confirmation of signup on splash page with @rchekaluk. Simple text email should be fine, I can write copy for each case.

**Comment by davidmooreppf** [comment]
More slight tweaks :: 
- please make form text darker for "email" and "zipcode" - hearing it's too light. This gray is an issue around the site, we'll have to take a look at it on staging too. 
- in layout copy below-the-fold, please make text for links darker. Currently it's too light. e.g. "AskThem is supported by a generous grant from the Knight Foundation's Tech For Engagement initiative.", where Tech For Engagement is a link, please make darker. 
- Above there's a note about displaying post-signup confirmation page. Let's add-in social sharing icons there - hopefully you can grab them from production.

**Comment by acacheung** [comment]
@davidmooreppf 
- I don't think I'm seeing the same issues in Safari. Can I get a screenshot?
- Can we go over the confirmation page changes? I'm not quite sure what is going on here. Also, where to put social icons?

All the other changes should be taken care of.

**Comment by davidmooreppf** [comment]
Safari issue seems fine now, maybe I wasn't updated. 

Yep we can go over confirmation page - right now it displays dark text on dark background :: http://cl.ly/image/1B1l3b1D0f2t

... we can move the copy to the sky and move the image down, or whatever you think, to make it legible. And place the sharing buttons below the copy "OK, we added..."

**Comment by davidmooreppf** [comment]
Social sharing icons!

**Comment by davidmooreppf** [comment]
OK, the confirmation copy is now legible and links back to splash homepage, which is fine. Amanda I think you can close this when you're ready on Monday.
