### ISSUE TITLE
info display for profile pages for exec branch

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#89]
For now, MVP is to just display, for US state governors & mayors :: 

Available info for that person: name, title, links, official contact info 

... and user-generated questions to them. 

No need to assume 'vote' equivalent to them now. Maybe a slight enhancement is possible.

**Comment by walter** [comment]
@davidmooreppf it would be good to spell out the things that might be different from the existing profile pages that we already have for senators and representatives (obviously lack of votes, etc.).

**Comment by davidmooreppf** [comment]
Back to me to specify before handing over to Walter.

**Comment by walter** [comment]
Closing this. Mayors and governors now display with information that is available for them from Google Civic Info API or other sources.
