### ISSUE TITLE
On Government page when FederalLegislator, disable Bills and Key Votes from subnav, adjust design

### ISSUE THREAD

**Issue by walter** [opengovernment/askthem-legacy#93]
On a government page like http://oglocal.herokuapp.com/ny?type=FederalLegislator,  we won't be displaying federal bills or key votes yet and will be disabling these elements from the navigation when displaying federal information.

Actually, for state level info, we'll be able to disabling Key Votes for the time being as well.

@acacheung & @davidmooreppf, does the current design look alright with these "blocks" dropped from the subnav?

**Comment by davidmooreppf** [comment]
Well in a more ideal world I'd like to retain these, but I understand we need to strip them now. 

So reassigning to Amanda to remove "bills" and "key votes" from all "Government" pages, under federal or state. 

But @walter, we'll still need to add-in executive branch info there in that horizontal box - at least for state & city levels, if not federal Exec. Branch. So we'll have a third box there still in every case. After the legislative branches, upper & lower chambers.

**Comment by walter** [comment]
@acacheung I would say commenting out is sufficient rather than deleting the code.

**Comment by acacheung** [comment]
@walter @davidmooreppf Talked to Steve and he said it looks bare, but it can work. How much later until bills and key votes are reintroduced? 

Handing over to walter to add in executive branch info into horizontal box

**Comment by walter** [comment]
Bills are currently available through an individual person's sponsored bills. So the data is there.

When we are ready, which is not now, I would like a debate about where Bills and Key Votes are handled navigationally.

If it looks bare without out them, could we come up with an alternative look for that navigation? Reassigning for you to have a play with how else that navigation bar might look with lesser number of areas.

**Comment by acacheung** [comment]
@walter What do you think about having Bills and Key Votes there but then statically typing "Coming soon" and looking disable and unclickable?

**Comment by davidmooreppf** [comment]
Good suggestion - let's stake that turf - as you suggest Amanda. @walter I'm excited to signal they're coming soon, even though I know it's not strictly best practice. Let's see if it makes the page feel more solid.

**Comment by davidmooreppf** [comment]
Haha although my comment above forgot that we're adding in Exec. branch box, so Amanda is going to experiment with breaking them up into three, or having a fourth that's inactive for combined Bills & Issues.

**Comment by walter** [comment]
It's sort of just kicking the can down the road, but I can live with it.

**Comment by walter** [comment]
Ah, yes, and the exec branch box. Cool.

**Comment by acacheung** [comment]
@walter styles are fixed. we're gonna go with having the three boxes for now and no disabled fourth box. handing it off to you to make the "Governor" link real.

**Comment by walter** [comment]
Since the design work is done, closing this leu of #89 and  #24 for making the data live.
