### ISSUE TITLE
styling on AskThem donate page on PPolitics.org 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#94]
Quick design & styling on page ::

http://www.participatorypolitics.org/?page_id=65&preview=true

... I'll give you the WP logins over Skype again. 

Please ::
1. Cleanup the donation boxes HTML to make it look normal. I can go over this on Skype with you for efficiency if that helps. 
2. Add AskThem logo somewhere up top 
3. Add in social sharing buttons on that page - for sharing that page specifically, as opposed to the generic ones in header. 
4. Any other "AskThem" elements - feel free to bring in. Don't need to spend much time on this.

**Comment by acacheung** [comment]
Just added the sharing buttons. Take a look!
