### ISSUE TITLE
on third page of question creation process, offer link to login

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#96]
Quick one for Amanda & @walter. 

On third step of Q creation, where visitor enters her name & email & pw ::  

http://cl.ly/image/3E3C1J1t3Z0F

... we should have a little link to allow visitors to login if they already have an account. 

I'm thinking a small link at bottom, below "3 of 4", w/ copy :: 

(Already have an AskThem account? Login.) 

... styled faintly.

**Comment by davidmooreppf** [comment]
Assigning to Amanda.

**Comment by walter** [comment]
This is basically the same as #58, but with more details of how to do it. Closing that one.

I think that this is good... but we also need something on address portion as well as this can be filled out for the user if they are signed in.

So I would also design something for the first page (address lookup) as well as the third.

**Comment by acacheung** [comment]
Added the link but not clear as to what I should be doing on page 1

**Comment by acacheung** [comment]
@walter let's chat about page 1 when you have a chance

**Comment by walter** [comment]
@acacheung right now on page one, it prompts you for your address, but there is nothing that gives you the opportunity to login (which would pre-fill your address for you, thus saving time).

I was thinking a "already a member, but signed out? login and we'll get your info" in the header of the address form. What do you think?
