### ISSUE TITLE
Pagination for overview pages broken in Safari

### ISSUE THREAD

**Issue by evz** [opengovernment/askthem-legacy#98]
Steps to replicate:

1) Launch Safari on OS X
2) Navigate to an overview page (like [this one](http://oglocal.herokuapp.com/il/), for instance)
3) Scroll to the bottom of the Person listing.
4) Click a page number or the next button to navigate to another page
5) Notice that nothing happens

According to the Inspector in Safari, it's complaining about not being able to animate something(??)

![screen shot 2013-09-06 at 2 37 18 pm](https://f.cloud.github.com/assets/551491/1098941/d843d46a-172b-11e3-992a-df97a2949df2.png)

Anyways, FWIW.

**Comment by walter** [comment]
Maybe we need "respond_to :js" in place?
